### ISSUE TITLE
Search engine addition request

### ISSUE THREAD

**Issue by Boo-Guy** [dessant/search-by-image#10]
Please add reddit image search engines karmadecay.com and i.rarchives.com.

Thanks.

**Comment by dessant** [comment]
Thanks for the suggestions, I'll look into them.

**Comment by Netanyahu** [comment]
The addon doesn't work on Yandex when searching for local pictures, just opens the page Yandex Images.

**Comment by dessant** [comment]
@Netanyahu, please reproduce the bug with a public image which you can share and open a new issue for it, searching for local images on Yandex works on my part.
https://github.com/dessant/search-by-image/issues/new

**Comment by dessant** [comment]
Karma Decay will be available in the next release.
