### ISSUE TITLE
Option to open Google to the page with the actual images instead of the normal results page

### ISSUE THREAD

**Issue by EraYaN** [dessant/search-by-image#100]
**Is your feature request related to a problem? Please describe.**
Google requires an extra click when search for larger sizes of the current image. Click on "All Sizes"

**Describe the solution you'd like**
I'd like to set an option to open that page by default for the Google search engine from at least the context menu

**Describe alternatives you've considered**
Adding an extra search enige that deeplinks that page might work as well, if it saves on engine specific settings, but I feel like there are probably more engines that have something like that. Or might have some configurability.

**Comment by dessant** [comment]
There's a plan to make search engines customizable, let's track the issue here: https://github.com/dessant/search-by-image/issues/68

**Comment by EraYaN** [comment]
That doesn't not cover this fully, since the google engine will need some changes to actually generate the right url for image search deeplinking. The searchbyimage endpoint does not seem to have any options natively to directly go to the All sizes page.

**Comment by dessant** [comment]
Engine configuration won't be limited to URL parameters, we do what needs to be done to implement the desired feature, in this case probably by clicking on the all sizes link on the results page.
