### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by donnje** [dessant/search-by-image#101]

**Comment by donnje** [comment]
> **System**
> 
> * OS name: Windows
> * OS version: 10
> * Browser name: Chrome
> * Browser version: 87.0.4280.66
> * Extension version: 64 bit
> 
> **Bug description**
> 
> 
> ```

> ```
> 
> Searching for all sites together doesn't work on Facebook while it works for every single site

**Comment by dessant** [comment]
Thanks for reporting the bug, let's track this at https://github.com/dessant/search-by-image/issues/102.
