### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [dessant/search-by-image#104]
https://addons.mozilla.org/en-GB/firefox/addon/search_by_image/versions/3.1.0/updateinfo/ included notes (thanks). 

https://addons.mozilla.org/en-GB/firefox/addon/search_by_image/versions/3.4.1/updateinfo/ is empty and so notes can not be viewed at about:addons e.g. before deciding whether to update: 

![image](https://user-images.githubusercontent.com/192271/101245731-bb802100-3706-11eb-96e6-4588cba10849.png)

For reference: https://github.com/dessant/search-by-image/compare/v3.1.0...v3.4.1

**Comment by dessant** [comment]
Thanks for noticing, I will link directly to the changelog for the respective release in the future.

**Comment by dessant** [comment]
The link has been added for 3.4.1.

**Comment by grahamperrin** [comment]
Thanks again for fixing this.

**Comment by SteegHobland** [comment]
Takes an extra step, don't like that.
