### ISSUE TITLE
Search By opens multiple tabs for every run

### ISSUE THREAD

**Issue by Morasiu** [dessant/search-by-image#106]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 84.0
* Extension version: 3.4.2

**Bug description**
When using Search By for the first time it opens one Google search in the background. But doing it the second time (without restarting extension or browser) it opens two the same searches. Doing it the third time opens 3 searches etc. It doesn't happen on all sites and images. 

![ScreenToGif](https://user-images.githubusercontent.com/19236279/102363078-5ef9ed00-3fb5-11eb-8e5d-88d5e2abec6a.gif)

1. Right Mouse Click on image
2. Choose "Search By "
3. Choose any search engine
4.  Do steps 1-3 again. 

**Logs**

```
None?
```

**Comment by dessant** [comment]
Thanks for the bug report! Have you found an image or method to reliably trigger the bug, or does it only appear randomly?

**Comment by Morasiu** [comment]
It happens on a specific site.  But I cannot send you the link. If I find some site which is publicly available and an error occurs on it I'll add a link here.

**Comment by dessant** [comment]
Thanks, it would be important for reproducing the issue. Are you able to trigger the bug every time on that site with the *same* image between browser sessions, or does it only happen sometimes?

**Comment by Morasiu** [comment]
Yes. It appears to happen every time with multiple images. I mean:
1. Open Firefox
2. I Search By using `Picture A` - open 1 new tab with Picture A
3. I Search By using `Picture A` second time - open 2 new tabs with Picture A
4. I Search By using different `Picture B`  - open 3 new tabs with Picture B
5. etc.

After I close the session it starts from opening 1 tab again and then goes to opening 2 tabs, 3 tabs etc.

**Comment by dessant** [comment]
Thanks for the details, this should be easy to reproduce once there's a public site to test. Btw, you've been referring to "Search By" the whole time, are you sure you're using this extension, and not something else? This extension adds a context menu item with the "Search by Image" label.

https://addons.mozilla.org/en-US/firefox/addon/search_by_image/

**Comment by Morasiu** [comment]
I'm using Search By Image. I was just making it short because I'm lazy.

**Comment by dessant** [comment]
I haven't managed to reproduce the issue so far. If anyone finds a page URL that can be shared, please post it here. It the URL is sensitive, there's an email on my GitHub profile to share it in private.

**Comment by Morasiu** [comment]
Fixed now!
