### ISSUE TITLE
Extension pseudo protocol URL stopped working

### ISSUE THREAD

**Issue by tijtij** [dessant/search-by-image#108]
**System**

* OS name: macOS, Windows, Android
* OS version: n/a
* Browser name: Chrome, Firefox
* Browser version: latest
* Extension version: 3.4.2

**Bug description**

I kept a bookmark to `.../src/browse/index.html?engine=allEngines` so that I could quickly look up pictures pasted from the clipboard or uploaded from storage without having to constantly use the extension icon menu and change away from *Capture*.

In the latest version of the extension the above URL displays a page with the message `The page URL is not valid. Try searching again for the image.`

Is it possible that the old behavior can be restored with the current URL implementation?

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
The way the extension works has completely changed. That page is no longer stateless, now there's a session ID that references a search task that holds settings related to the search. This will be further abstracted in the near future when search engine [customization](https://github.com/dessant/search-by-image/issues/68) is implemented, and at that point adding a special case of recognizing an engine name from the URL would not work either.

Going forward, you could configure the context menu and toolbar popup differently to make things a bit easier. For example the toolbar button could be set to the `Upload` search mode from the extension's options, and the `Search all engines` option set to `From browser toolbar`. This way you'll be able to open the upload page with a single click on the extension icon to search with all engines, while still being able to use the `Capture` search mode from the context menu.

You could even install a second instance of the extension and configure a second toolbar button to open the upload page directly. These are the latest unsigned extension packages from the release page, if you opt to install a second instance:

https://github.com/dessant/search-by-image/releases

There's a possibility of adding completely independent configuration for the context menu item and the toolbar button in the future, independent engine list etc., but for now you'll have to use a workaround.

Keyboard shortcuts will also be added at some point: https://github.com/dessant/search-by-image/issues/83
