### ISSUE TITLE
FR: support for legacy (XPI/XUL) Mozilla-based browsers

### ISSUE THREAD

**Issue by LigH-de** [dessant/search-by-image#109]
Firefox once discarded a previous add-on API and switched to WebExtensions instead.

The "legacy" codebase is still maintained with all recent and even more security fixes and other technical updates, avoiding superfluous features many users don't care about or dislike, in web browser projects like [Pale Moon](https://www.palemoon.org) or [Basilisk](https://www.basilisk-browser.org/). Regarding add-on management, they are based on the [Unified XUL Platform](http://thereisonlyxul.org/), and still support the XPI archives.

Many "legacy" add-ons don't work in a modern Firefox version anymore because the WebExtension API does not support access to required browser features for them, and support for the XUL API got dropped.

When I try to navigate to the Firefox add-on database with such a browser, it does not offer me your add-on to be installed, instead it suggests me to download Firefox instead.

**Comment by dessant** [comment]
The extension needs to be completely rewritten to support the XUL API, which is unlikely to happen, unless someone will pay for it. If anyone would like to sponsor two months of dev time (about 10k EUR) for a Pale Moon port of the extension, feel free to reach out.
