### ISSUE TITLE
Shift-RightClick and select Search... in Google Doc at the picture does nothing

### ISSUE THREAD

**Issue by desirepl** [dessant/search-by-image#110]
Latest Chrome. Each update changes nothing. Problem exists about a month +/-. (And it is happened almost the same time when I changed Win7x64 to Win10x64)
Latest extension. 3.4.3.

When clicking at the picture and trying to search for... I always see "no picture" and now after trying to change settings just enabled "Open new tabs in the background" at the bottom and always receive "Content scripts are not allowed on this page". Disabling "Open new tabs in the background" didn't reverted back to "no picture", now just "Content scripts are not allowed".
Nothing at console.

Reinstalled, edited preferences (disabled unneeded engines, enabled Open new tabs in the background, disabled Use local Google site) and now again "No image found. Try searching again by placing the cursor above the image".

**Comment by dessant** [comment]
Please share a public Google Docs document with an image in it.

**Comment by desirepl** [comment]
I've digged a little and found that.
My previous system (almost the same but Win7, now it's Win10) + Chrome + SearchByImage works ok. When I check sourcecode of image zone I see that link to the image is OK.
At current system link to the image is something like: image xlink:href="filesystem:https://docs.google.com/persistent/docs/documents/15q ... and a lot of "garbage" /image but on working system xlink:href is https://lh6.googleuser.... as expected. When trying "open in new tab" at the link in sourcecode then I get an errors because "filesystem:" is not a registered protocol and Chrome thinks that this is child directory and adds docs.google.com/... before "filesystem:", if I delete all that added by Chrome then it leads to error too, because this link is changed on the fly by the embedded script.

When searching page code for part of that "url" I've found new script, starting with "DOCS_timing['sac'] = new Date().getTime(); var KX_kixApp; var DOCS_warmStartDocumentLoader;" and so on, a lot of code. Searching for that part of code shows a lot of documents on the net, so something is putting this code there. I've deleted all googledocs extensions one after the one — nothing changed. Disabled virtual keyboard in KIS (Kaspersky) — nothing changed (I've thinked about KIS few times because time to time there was a choice when trying to select and search for image and first selection was always a thumbnail of something like virtual keyboard... — thumb attached)
). Disabled secured payments in KIS — nothing changed. Disabled everything in KIS — the same result. Disabled KIS totally, disabled scripts for checking secured traffic and everything that can change any byte in traffic — nothing, problem exists.
I don't know who is putting that code there. I'm trying to find out but with no luck for a current moment.

Any ideas?

![thumb](https://user-images.githubusercontent.com/18093731/109367609-33419000-789f-11eb-9da8-5c5d05270e2d.png

**Comment by desirepl** [comment]
![chrome_210227_0153_NiXqv2ygqh](https://user-images.githubusercontent.com/18093731/109368071-8bc55d00-78a0-11eb-8f3f-6802f2f4552f.jpg)

**Comment by desirepl** [comment]
I've found a problem. It's in "documents offline" mode.
I tried my firefox on new system, checked urls of images - they are ok, so it's a Chrome problem only.
Then I disabled any extension - problem exists. Then I changed security settings to none - problem exists.
When I disabled any extension docs page alerted me that there is a problem with offline mode (I disabled everything and "Google documents offline" too, currently v1.21.0). I've disabled it at the drive.google.com/drive/my-drive page clicking at the Settings icon then urls was fixed! I turned on extensions by pairs or triplets and problem is not raised. I've enabled offline mode and voila! Problem again with me. So it's a offline mode error.
If you can make your extension compatible with that it will be good (and little more peoples that thinks that extension didn't work and uninstalling it).

**Comment by dessant** [comment]
It seems this is a deprecated feature of the FireSystem API in Chrome.

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/toURL

I will look into handling this in the future, but please share a public Google Docs document that reproduces the issue in offline mode.

**Comment by desirepl** [comment]
> It seems this is a deprecated feature of the FireSystem API in Chrome.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry/toURL
> 
> I will look into handling this in the future, but please share a public Google Docs document that reproduces the issue in offline mode.

**dessant**, Hi, friend.
I've found a problem, read my previous message. If you can fix it - it will be very good.
Good luck!

**Comment by dessant** [comment]
I don't use Google Docs, that's why I've asked for a document link.

**Comment by desirepl** [comment]
Can I sent it to you directly to not to share link to the public?

**Comment by desirepl** [comment]
PS: If you don't use Google Docs then you don't use Google Drive I assume? So you can't enable offline mode and reproduce the error even if I give you the link to the document, because page code is generated every time someone enters the document/updates it and this links/script that leads to error is not reproduceable at your side, because my offline mode will not reflect your presentation of google document.
