### ISSUE TITLE
Opens multiple tabs at the same when reverse searching from specific sites.

### ISSUE THREAD

**Issue by pseudokawaii** [dessant/search-by-image#111]
**System**

* OS name: Windows
* OS version: 10 x64
* Browser name: Firefox
* Browser version: 85.0 (64-bit)
* Extension version: 3.4.3

**Bug description**
opens multiple tabs at the same time when reverse searching images from a specific site (https://csbmc.edu.bd). Repeating the same process of reverse searching results in more and more extra tabs to open.

![4CZmVSvTYu](https://user-images.githubusercontent.com/63403140/106713355-8881dd00-6624-11eb-9a88-f6167e571ba8.gif)

**Comment by dessant** [comment]
Thanks for the bug report, it means a lot that you've provided an example! This issue was reported [before](https://github.com/dessant/search-by-image/issues/106), but due to lack of an example, I could not reproduce the bug. I'll release a new version in the next few days.

**Comment by dessant** [comment]
Search by Image 3.6.0 is now live on Firefox Add-ons, please let me know if there are any other issues.
