### ISSUE TITLE
No other image size found on Google

### ISSUE THREAD

**Issue by LoicSuply975** [dessant/search-by-image#112]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 89.0.4389.40
* Extension version: 3.6.0

**Bug description**
I tried of found an bigger size of an small image on Google and he said that are no other image size found on this size but i can found different size image on the Pages containing identical images.

**Comment by dessant** [comment]
Do you get more results when you search for the image manually on Google by clicking on the camera icon?

https://images.google.com/
