### ISSUE TITLE
Add ability to download selected image

### ISSUE THREAD

**Issue by shape55** [dessant/search-by-image#116]
**Is your feature request related to a problem? Please describe.**
I'm unable to locate the URL for the image being used for the reverse image search.

**Describe the solution you'd like**
In cases where the selected image is hidden in CSS and pseudo-elements, a simple menu option to download the image as well as an option to copy its URL would be extremely helpful.  Often times it’s the highest quality one available in the search, and sometimes even manually searching thru the elements may not reveal the image URL.

**Describe alternatives you've considered**
I've tried web searching how this can be achieved but found no results.

**Additional context**
In the mean time, how do you find the URL in the extension for the selected image being used for the reverse image search if it’s hidden?  For ex, if I select "Search by Image -> Google" on this page: https://play.hbomax.com/page/urn:hbo:page:GWIvJowtJp8IapQEAAAAI:type:episode, it takes me here: http://bit.ly/Fantasmagorias and shows at the very top: “Image size: 3040 × 1710”, but doesn’t include this website or image if you click on “All sizes”.  This is a very large hi-res image but I can’t find a way to download it.  Normally, I can find it if I inspect the element, but not for the images on HBO’s site.  Other image download extensions I’ve tried or the Pinterest button can’t find it either on this page.

**Comment by dessant** [comment]
The HBO MAX page is geoblocked, so I can't tell you how your image was found, but here's the script that extracts images from a page:

https://github.com/dessant/search-by-image/blob/master/src/parse/main.js

**Comment by dessant** [comment]
I've been planning to add this as part of a new feature for opening images in a new tab, though it's deep in the backlog for now.

**Comment by shape55** [comment]
Glad to hear the feature is already on your list – opening in a new tab would be great.

Thanks for the script but I don't know any code, so I don't think it'll be of use to me.  Are you also not able to find the image link in the element inspector of that HBO page?  And do you know of a way to access the source URL of the image thumbnail at the top of the google search results page where it displays “Image size: 3040 × 1710”,  or is this not possible since it looks like a proprietary Google link?

**Comment by dessant** [comment]
The HBO page is geoblocked on my part, we don't see the same page, so I can't answer your question. I'm not sure about Google either, but when the extracted image is in the form of a URL, you could try searching with TinEye, it usually shows the searched URL at the top of the search results page.

**Comment by shape55** [comment]
Gotcha – I didn't realize at first that meant it was a regional block.  There isn't an HBO site for your region?

Thanks for the tip.  I'll give TinEye a try.

**Comment by shape55** [comment]
I attempted to "expand all" from the element inspector and copy the contents into Pastebin, but unfortunately it won't let me copy it.  So I copy/pasted the contents from "View Source" though I'm not sure if this will reveal the location of the background image, which should be 3040 × 1710: https://pastebin.com/x7P28e58

**Comment by dessant** [comment]
![1](https://user-images.githubusercontent.com/7513068/108876687-27d43780-7607-11eb-8e97-b2dfbfbd8d5d.png)

I've visited the page from a VPS, you can search for "background-image" in the Firefox inspector and repeatedly press enter in the inspector search bar until you select the right element, then right-click on the background image to copy the blob as a data URL, and paste the data URL in the address bar of a new tab to view the image.

I'll track this issue in a different feature request, since this thread is mostly about HBO. :yum:

**Comment by shape55** [comment]
Outstanding!  I found the image.  Thank you very much. :slightly_smiling_face:  The URL is "blob:https://play.hbomax.com/11c22740-dded-6540-9085-4162276cd52e" (which works in Firefox but produces a WebKitBlobResource error in Safari), so I would have never known this was a jpeg link.  I normally either use that search bar to enter jpg, png, or webp (and can find a lot of images that way), use the element picker to select the image, or scroll down thru the inspector until the image is highlighted and then look for links. 

Now I can apply this new method to other pages on HBO’s site and many other sites as well that have similarly difficult to locate images.
