### ISSUE TITLE
Yandex doesn't work anymore

### ISSUE THREAD

**Issue by raffaem** [dessant/search-by-image#118]
**System**

* OS name: [e.g. Windows, Ubuntu] Ubuntu
* OS version: [e.g. 10] 20.10
* Browser name: [e.g. Chrome, Firefox] Firefox
* Browser version: [e.g. 60]  86
* Extension version: [e.g. 1.0.0] 3.6.0

**Bug description**

1. Click on the icon extension -> Click upload icon -> Select upload
2. Click "All Search engines"
3. Click "Browse" and open image you want to search
4. BUG: The Yandex tab will open at [https://yandex.com/images/], instead of the tab that looks for the image

**Thank you for this fantastic extension!**

**Comment by dessant** [comment]
Thanks for the bug report, I have managed to reproduce the issue a couple of times, though it cannot be triggered reliably, and there is no error shown by the extension. I'll try to look into it next week.

**Comment by dessant** [comment]
Version 3.6.1 has been published on Firefox Add-ons, please let me know if there are other issues with Yandex.
