### ISSUE TITLE
Can't access preferences

### ISSUE THREAD

**Issue by Elaborendum** [dessant/search-by-image#119]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 87.0
* Extension version: 3.6.0

**Bug description**

Clicking the toolbar button only triggers the "Select" Mode and the context menu only shows "Search Google for Image". I can't access the preferences at all.

I've tried disabling all extensions, but it's still present. I've tried on a clean profile and it works perfectly, so maybe it's something in about:config. But I don't have something like "privacy.resistFingerprinting" on, never seen any other extension break before. No indication of it being an error anywhere either.

It's the first time I use the extension, so am I just doing something wrong here?

https://user-images.githubusercontent.com/71190696/113332461-d0e90e80-92e6-11eb-9e45-bdb77fc6b3f0.mp4

**Comment by dessant** [comment]
It looks like you've left only one search engine enabled. More than one search engine must be enabled for the intermediate popup to show up, visit about:addons and click the three dot menu button for the extension, there will be a menu item to open the extension's preferences.

![Screenshot from 2021-04-02 12-49-38](https://user-images.githubusercontent.com/7513068/113405398-76b57f80-93b2-11eb-9421-8c1c1b509d32.png)
