### ISSUE TITLE
Request: option to both have search option directly in context menu and a sub menu

### ISSUE THREAD

**Issue by alfakr0ll** [dessant/search-by-image#12]
In short I mainly use Google images search to search for the images, but sometimes I want to use alternative search motors. Would it be possible to have both "Search all engines from context menu" but only with one activate there and "Search all engines from submenu of context menu" for the rest of search engines?

**Comment by dessant** [comment]
Sounds like a nice feature, but adding more than one item to the top level context menu is not possible with the current API. Your best option is to open an issue and request the feature on your browser's bug tracker.

**Comment by alfakr0ll** [comment]
Can you merge them both into one item? If you press it then is is like the first option, and if you mouseover it expand to an sub menu for the rest like the second option?

**Comment by dessant** [comment]
That is not possible either with the extension API.

**Comment by alfakr0ll** [comment]
Oh well, thanks for the reply.
I'm using Firefox so I'll send an request to their bugtracker to make that option available in the API.
(for now I'll be looking at running to of these add-ons in parallel to get the functionality I want)

**Comment by EC-O-DE** [comment]
The pop-up with on-the-fly quick change of the providers would help with this issue.
