### ISSUE TITLE
Capture function not working on Yandex

### ISSUE THREAD

**Issue by Asteri0nisMaastrichtensis** [dessant/search-by-image#121]
* OS name: macOS
* OS version: 10.15
* Browser name: Chrome
* Browser version: 89
* Extension version: 3.6.1

**Bug description**
"Capture" search mode does not interact properly with Yandex image search but is fine with other search engines. "Select" search mode works with Yandex image search. Attempting to use "capture" search mode opens a new tab to https://yandex.com/images/ without loading the selected area of the screen.

**Comment by dessant** [comment]
I can't reproduce the issue on Chrome and Linux, are you sure the extension version isn't 3.6.0?

**Comment by Asteri0nisMaastrichtensis** [comment]
Is there a way I can double-check to confirm?

**Comment by dessant** [comment]
Visit chrome://extensions/ and click on the Details button of the extension, the version will be listed there.

You should also get an error popup after about a minute if the Yandex page is left open, please open the page console after the popup is shown and share the error message you see there.

**Comment by Asteri0nisMaastrichtensis** [comment]
I've confirmed that the version is 3.6.1 through the screen. After about a minute I get the message "Something went wrong. Searching on Yandex has failed" and the options to either close the notification or go to "settings". However, clicking the "settings" button does nothing. There are two types of errors I see in the console:

1. Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2. Uncaught (in promise) Error: DOM node not found: .cbir-panel_visibility_visible input.cbir-panel__file-input
    at script.js:1

**Comment by Asteri0nisMaastrichtensis** [comment]
Okay, so I've just checked and it seems to be working again. I no longer receive the "Something went wrong. Searching on Yandex has failed." message but it just takes quite a while for the image to load.

**Comment by Asteri0nisMaastrichtensis** [comment]
Scratch that, it seems to correctly input the captured image if you open the page console after searching. However, simply leaving the search engine alone after capturing the image will not let it search the image.

**Comment by dessant** [comment]
I've also tested on macOS with Chrome and searching with Capture works as expected, without user interaction. I'ts possible that your device is part of an A/B test run by Yandex where some page assets are only loaded after the first user interaction, but it's hard to tell what's really causing the issue on your end.

**Comment by Asteri0nisMaastrichtensis** [comment]
If it is A/B testing then could I expect the issue to be resolved eventually?

**Comment by dessant** [comment]
It could go away, but it could also be a permanent change that's served to your geographical location. I've tested from the US and the EU, and it worked.

I'll leave this issue open for now, in case someone else can also reliably reproduce the issue.

**Comment by Gamma-Velorum** [comment]
I'm in the APAC region on Chrome Version 89.0.4389.128 (Official Build) (64-bit) & Search by Image v3.6.1

`Error: DOM node not found: .cbir-panel_visibility_visible input.cbir-panel__file-input
 script.js:1 Uncaught (in promise) Error: DOM node not found: .cbir-panel_visibility_visible input.cbir-panel__file-input
    at script.js:1`

![yandex_fail](https://user-images.githubusercontent.com/77098567/115951257-5345a680-a512-11eb-8b6d-fe21b31c848f.png)

**Comment by Gamma-Velorum** [comment]
Works fine in Version 92.0.4486.2 (Official Build) canary (64-bit)

**Comment by dessant** [comment]
Can you do a quick test to help debug the issue? Search with Yandex using the extension, and wait for it to show an error. When the error is shown, please create a screenshot of the browser window so that the URL bar and page is shown.

**Comment by dessant** [comment]
It looks like #118 was only partially fixed. I have managed to consistenly reproduce the issue by setting up a VM and reducing the CPU speed, and then the bug became evident: on fast devices the CSS classes we look for are usually all available by the time the last HTML element is added, but on a bit slower devices the CSS class may not be added to the element when we check, and we weren't further listening to class changes on elements.

**Comment by Asteri0nisMaastrichtensis** [comment]
So the issue is a result of my computer being too slow then? Oh well then, tell users that viewing the console using the drop-down menu option "Inspect" will trigger the search as long as the search bar pops up. Thanks for looking into it.

**Comment by dessant** [comment]
> So the issue is a result of my computer being too slow then?

@Asteri0nisMaastrichtensis, no, the issue was a result of a bug in the extension that was mainly triggered when JS execution was slower, and the bug should be fixed by the commit above that closed this issue.
