### ISSUE TITLE
Please provide instruction from installation and deploy on mobile browsers

### ISSUE THREAD

**Issue by bunglegrind** [dessant/search-by-image#122]
Readme and wiki lack instructions for the deploy on mobile platforms (i.e., Samsung Internet Browser). 
Could you please update the documentation?

Cheers

**Comment by dessant** [comment]
Only Samsung partners can build extensions for Samsung Internet, and the partner agreement forbids sharing any information about the process.

**Comment by bunglegrind** [comment]
Ok thanks
