### ISSUE TITLE
Allow more customization of search engines

### ISSUE THREAD

**Issue by contextnerror** [dessant/search-by-image#126]
I've recently migrated over to this extension from a different one, and there's a couple features I miss:

-The ability to disable the "all search engines" function in the context menu
-The ability to add custom search engines with urls
-The ability to give custom names to search engines (this one's pretty minor, but would be nice. seeing IQDB in lowercase bugs me.)

Would any of these be feasible to implement?

**Comment by dessant** [comment]
> The ability to disable the "all search engines" function in the context menu

The "All search engines" menu item can be disabled from the extension's options.

![](https://user-images.githubusercontent.com/7513068/118081083-59b59880-b3c3-11eb-80e0-dba2f090cad1.png)

> The ability to add custom search engines with urls

This is unfortunately not planned at this time, but it may be implemented in the long term. You could share a list of the search engines you'd like to add, maybe we can include them directly.

> The ability to give custom names to search engines

It will probably be implemented this year, you can subscribe to this issue for updates: https://github.com/dessant/search-by-image/issues/68

I'll update the IQDB name, please let me know if there are any other naming issues.

**Comment by contextnerror** [comment]
Sorry, I should've clarified- I meant disabling the "all search engines" option in the submenu of the context menu while still leaving the individual search engines accessible. Since it's a feature I never have personally used, it'd be nice to reduce the length that the menu takes up.
Thanks for the spelling change though, I can now rest easy.

**Comment by dessant** [comment]
Yes, if you set the "Search all engines" option is the context menu section to "Disable", the "All search engines" menu item in the submenu should not appear.

Regarding search engines, feel free to email me a list if it's more comfortable that way, NSFW is fine as well. I have an internal to do list of engines that need to be implemented, so it would be useful to know about them even if they are not added right away. My email address is listed on my GitHub profile.

**Comment by contextnerror** [comment]
Oh! Sorry, I'm a bit slow. Thanks for that.
I don't have any particular search engines at the moment, it just seems like something that could be useful as an option. Being able to add things on the user side could allow for the addition of helpful related tools like ImgOps or metadata viewers that may be outside the scope of the default engines, seeing as they aren't really "search engines" per se.
