### ISSUE TITLE
Possible to add Image Ops?

### ISSUE THREAD

**Issue by RandomDeviation** [dessant/search-by-image#127]
**Is your feature request related to a problem? Please describe.**
I am a bit tech illiterate, I just found your amazing extension for edge and chrome. I use Image Ops (https://imgops.com/) and wanted to ask if you can add it to the list of search engines. It allows for images to be easily edited so data can be viewed as well as searched further. 

**Describe the solution you'd like**
The search settings for image ops say add https://imgops.com/ before the url of the image. 

Example, link of image of dog in Encyclopedia (https://cdn.britannica.com/60/8160-050-08CCEABC/German-shepherd.jpg)

Search with Image Ops (https://imgops.com/cdn.britannica.com/60/8160-050-08CCEABC/German-shepherd.jpg) 

**Describe alternatives you've considered**
There is a different extension but I prefer just to use this one for Image Ops as well

**Additional context**
Thank you so much for this amazing extension and for taking the time to read this. Its possible I may have unwittingly made a mistake so please let me know. 

Kind Regards

**Comment by dessant** [comment]
ImageOps is considered out of scope for now, you may be able to manually add it in the distant future, if adding custom search engines URLs is implemented.
