### ISSUE TITLE
Add the option to search SauceNAO in Safeish Search mode

### ISSUE THREAD

**Issue by ItzMichaelPhillips** [dessant/search-by-image#128]
**Is your feature request related to a problem? Please describe.**
I like using SauceNAO as part of this extension, but I don't like seeing NSFW art in the results, even if the art I'm searching for is always SFW.

**Describe the solution you'd like**
An alternate checkbox in the engine list under regular SauceNAO labeled something along the lines of "SauceNAO Safe" that uses their Safeish Search mode.

**Describe alternatives you've considered**
I could enter the image URL into SauceNAO manually and check the Safeish Search checkbox there, but I like being able to search with multiple engines at once with this extension.

**Comment by dessant** [comment]
Thanks for the feature request! Listing separate engines for option changes by default would have some major issues (what if you want safe results from Google, but in Swedish). There's a plan to allow customizing an engine and saving different presets of the same engine for searching. You can subscribe to this issue for updates regarding search engine customization: https://github.com/dessant/search-by-image/issues/68
