### ISSUE TITLE
Doesn't search local pictures on Yandex

### ISSUE THREAD

**Issue by Netanyahu** [dessant/search-by-image#13]
It's not quite clear what I was asked by the developer :)
The addon works with public images normally. It doesn't search for local pictures on Yandex when I use a local picture address like "file:///...jpg". All other search engines work fine with the addon.

**Comment by dessant** [comment]
Are you using Firefox 57?

**Comment by Netanyahu** [comment]
Yes, I am.

**Comment by dessant** [comment]
Ok, let's use the same image to reproduce the bug: https://i.imgur.com/bnm7PJP.jpg.
1) Save it locally, then open it in a tab, so the tab URL begins with file://.
2) Right-click on the image and search with Yandex.

For me the tab loads Yandex first, waits a couple of seconds until the page fully loads, then redirects to the search results of the image.

**Comment by Netanyahu** [comment]
It turned out the same (see screenshot).
![screenshot](https://user-images.githubusercontent.com/15788255/33043860-db61af90-ce57-11e7-85f8-4fe556c752d9.png)

**Comment by Netanyahu** [comment]
Maybe this is a problem with Unicode?

**Comment by dessant** [comment]
You mean there are unicode chars in the image path? That's unlikely to be the cause, the search engine tab is only opened if the local image has been already extracted sucessfully.

Meanwhile I've also tested in a Windows VM and it works there too. Try checking the browser console (Ctrl + Shift + J), do you see any error messages which could be related to the extension, like an error in yandex.js?

**Comment by dessant** [comment]
As a test you could also try searching for a data URI image, because that has to be uploaded in the same way. Do not download it, just search for the cat image from the page directly: https://dopiaza.org/tools/datauri/examples/index.php.

**Comment by dessant** [comment]
I'm assuming regular images can be searched from web pages with Yandex, right?

**Comment by Netanyahu** [comment]
1) Yes, regular images can be searched from web pages with Yandex normally.

2) Your cat image also leads to error as in the screenshot (the search does not work).

3) The browser console information is too complicated for me, sorry :) It seems that there is something connected with the security policy.

**Comment by dessant** [comment]
I can prepare a debug version tomorrow if you want to and explain how to run it, then you just copy the output of the console and share it here. I'd add logging so we get a better idea at which line does the extension stop.

I'm also seeing a Content Security Policy error when uploading with all engines btw, but that looks like a false positive, and the image is uploaded regardless.

As a last test for today 😋, you could either use a brand new profile with your Firefox, or just download the portable Firefox version which will come with a clean browser profile. At least we could rule out some setting in your existing profile causing issues, or a different add-on interfering.
https://portableapps.com/apps/internet/firefox_portable

If it doesn't work with a new profile either, the only way to learn more is to test the debug version of the extension.

**Comment by Netanyahu** [comment]
Firefox Portable with a brand new profile leads to the same result :(

**Comment by dessant** [comment]
Of 😞, I'll share tomorrow a debug version here.

**Comment by dessant** [comment]
@Netanyahu, I've prepared a development build for you, these are the steps to follow:

1) Download and unzip the development build of the add-on: https://www.dropbox.com/s/d6lvn3n3n5h2913/dist.zip?dl=0
2) Visit about:debugging in Firefox Portable with a fresh profile
3) Click on "Load Temporary Add-on", navigate to the unzipped add-on folder and open it
4) The add-on should be listed on the debugging page, click on the "Debug" link below the line with "Internal UUID" and follow the instructions to enable debugging
5) A window like this should appear: https://i.imgur.com/ovupPmO.png. Click on the "Network" tab.
6) Go back to the main browser window and open the browser console (Ctrl + Shift + J)
7) Switch back to the main browser window and load this page in a tab: https://dopiaza.org/tools/datauri/examples/index.php
8) Right-click and search for the image with Yandex, after the engine page has fully loaded, wait at least 30 seconds
10) Go to the Developer Tools window opened at step 4, right-click in the network tab and select "Save All As HAR", then save the resulting .har file
11) There is a text input in the upper-right corner for URL filtering, type in "yandex.com", maximize the window and create a screenshot of the network tab
9) Go to the browser console opened at step 6, right-click in it and click "Select All"
12) Paste the text from the console here in a comment, include the network tab screenshot image, and upload the .har file to https://send.firefox.com or somewhere else and share the download link here

**Comment by Netanyahu** [comment]
Unfortunately, right-click in the "Network" tab doesn't cause any action. Clicking the Reload button causes some action in the console, but saving anything as HAR is impossible. What am I doing wrong?
![screen](https://user-images.githubusercontent.com/15788255/33108833-517727da-cf4f-11e7-9fd6-ac8ae0f328aa.png)

**Comment by Netanyahu** [comment]
By default I use the website yandex.ru, not yandex.com. Maybe this is the problem? Some kind of conflict in the request?

![screen1](https://user-images.githubusercontent.com/15788255/33109229-68920c1c-cf51-11e7-8241-b4ff43d70e51.png)

**Comment by dessant** [comment]
You're awesome! The HAR will not be needed anymore, I didn't notice the change of domains in your first screenshot, that is definitely the cause. Either we'll have to prevent Yandex from redirecting or just use the country specific domain when it redirects. Besides Russia, this likely also affects users from Ukraine, Kazakhstan, Belarus and Turkey.

I think I'm leaning towards letting the redirection happen, what do you think?

**Comment by dessant** [comment]
This build should have the issue fixed: https://www.dropbox.com/s/nraqy5qn8k65ic0/dist.zip?dl=0.

Thanks for diagnosing the issue!

**Comment by dessant** [comment]
1.4.1 has been published with the fix.
