### ISSUE TITLE
Pimeyes is no longer working

### ISSUE THREAD

**Issue by robertheadley** [dessant/search-by-image#130]
**System**

* OS name: Windows	
* OS version: 10 Pro
* Browser name: Firefox
* Browser version: 89.0
* Extension version: 3.6.2

**Bug description**
Pimeyes no longer works
I get a pimeyes Oops! page

**Logs**

GEThttps://pimeyes.com/en/search
[HTTP/2 404 Not Found 758ms]

**Comment by robertheadley** [comment]
I am imaging that Pimeyes probably changed their search URL

**Comment by dessant** [comment]
Thanks for letting me know, I'll release an update next week.

**Comment by dessant** [comment]
Fixed in version 3.6.3.

**Comment by dessant** [comment]
Hi @robertheadley, does PimEyes still work for you? I see they have completely restricted search results to paid accounts, and there is a fake search progress bar when uploading an image from the home page, which is just scummy and manipulative. I'm thinking about removing support for their service.

**Comment by deltabravozulu** [comment]
@dessant  please don't 😅
Your ingenious implementation is a huge help in actually using a paid PimEyes subscription.

**Comment by dessant** [comment]
So the upload form continues to work the same way right now on the home when you are logged in?

**Comment by robertheadley** [comment]
Yeah, it's working fine.
