### ISSUE TITLE
Request: Support for RepostSleuth.com

### ISSUE THREAD

**Issue by 12thPower** [dessant/search-by-image#132]
Thank-you for the wonderful addon and all your hard work.

I would love if support for RepostSleuth.com could be added. It's a database for a Reddit bot which determines if an image has been posted to Reddit before.

**Comment by dessant** [comment]
Does this service have a public API where images can be uploaded and results are returned?

**Comment by dessant** [comment]
Ok, just tested it, and it seems to find duplicates for popular images.

https://repostsleuth.com/search

I need an SVG icon for their service, the rest of the integration seems straightforward.

**Comment by 12thPower** [comment]
While it's not an SVG, the bot's profile on Reddit uses this PNG:
https://styles.redditmedia.com/t5_vjmiw/styles/profileIcon_zriuxd3y6qn41.png

Hopefully the bot's creator has a nice vector image. I'm really stoked at the possibility of this search being added! Thank-you for the time you've taken so far.

**Comment by dessant** [comment]
Version 3.7.0 has been published for Chrome and Firefox, you can now search with Repost Sleuth by visiting the extension's options and enabling the search engine.

**Comment by 12thPower** [comment]
Excellent. Thank-you, again.

**Comment by grahamperrin** [comment]
Nice :-)
