### ISSUE TITLE
Local image does not load to Yandex

### ISSUE THREAD

**Issue by JGinSF** [dessant/search-by-image#133]
When I open a local jpeg file using Firefox [file:///C:/ ... .jpg] and request a Yandex image search from the context menu, Yandex does not receive the image and therefore does not perform the search, but instead opens a dialog box to accept either a url or a dragged image. If the image is dragged to Yandex from Windows Explorer, the search is performed. This happens consistently as of about two or three weeks ago. Local image transfer continues to be successful for Google and TinEye image searches.

**Comment by domainfun** [comment]
Very odd, I have done exactly what you described a couple of days ago (and just tested it again) - it works fine for me, using Firefox 89.0.2 with a local file:///C:/*.jpg file.  Do you see any errors in the Firefox Web Developer Tools?

Did you open the Context Menu whilst the mouse is located inside the image (I first made the mistake myself and clicked outside the image)?

Do you have any other Firefox Add-ons which may prevent this from working on your computer?

**Comment by dessant** [comment]
Yandex is A/B testing a new search layout which breaks the extension. Until a fix is released, you could clear cookies, which will bring you back to the old layout with a high probability.

**Comment by dessant** [comment]
I've added a preliminary [fix](https://github.com/dessant/search-by-image/commit/86ddce185aef17346630917517b5f301e59e5c7d) for the new layout. If you're being served the old layout, the new one can be triggered by deleting cookies and reloading https://yandex.com/images repeatedly, at some point after several tries you will be shown an onboarding popup for the new reverse image search layout.

When you are served the new layout while using the extension, there may be a short, 1 second delay after the page load before the search continues. I've been following the new layout's progress in the past week, and they are heavily iterating on things, a fix I've locally implemented a couple of days ago has stopped working today, so the current fix does not rely on the DOM to figure out if the search service has finished loading, but polls the local storage for an item that is expected to be set only after the search service is fully initialized.

The new layout may stop working again while they continue to work on releasing it for all users, so please let me know when the issue reappears, or if you see a significant, 10 second delay before the image begins to upload on the search page.
