### ISSUE TITLE
Apparent Security Flaw in Opera GX

### ISSUE THREAD

**Issue by bardubo** [dessant/search-by-image#135]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Opera GX
* Browser version: LVL3 (core: 77.0.4054.275)
* Extension version: Version 3.7.1

**Bug description**

In order to update the extension to the newest version, Opera GX asks me to approve the app to 1) see and 2) **change** all the data that I type on every textbox on every website, so I suppose that includes passwords, credit cards, you name it, as long as the extension is up to date and running.

**Logs**

No errors, just a concern.

**Comment by dessant** [comment]
Browsers lack the kind of granular control over permissions that you would want to have. The extension needs to have read and write access to tab content in order to function, and password inputs cannot be selectively excluded from that access.
