### ISSUE TITLE
Add custom image search engines

### ISSUE THREAD

**Issue by arelkin** [dessant/search-by-image#136]
https://github.com/dessant/search-by-image/wiki/Search-engines
I see this list, but it would help if users could add their own.
I use others along with some on your list:
pixabay.com
duckduckgo.com

**Comment by dessant** [comment]
This has been discussed several times before, adding custom reverse image search engines won't be supported in the forseeable future. For reasons please search the issue tracker. If you have a list of reverse image search engines that you would like to see implemented, please share them.

The engines you have listed do not have a reverse image search service, adding them wouldn't do anything.
