### ISSUE TITLE
Search only when over an image

### ISSUE THREAD

**Issue by reembar** [dessant/search-by-image#14]
I noticed both in the Firefox and Chrome versions that the context menu submenu appears when right-clicking anywhere on the page and not just over an image. If it's not intentional, I think it's better it will appear only when needed.
Also, I think it would be nice to have the favicons of the search sites also in the context menu's submenu.
Thanks for your great extension and especially for the option to upload local images!
Other image search sites I heard of (but not tested) are:
http://www.picsearch.com
http://www.revimg.net
http://karmadecay.com
http://i.rarchives.com

**Comment by dessant** [comment]
Other extensions only show the context menu item for <img> elements and are not able to search for images declared in CSS, while this extension parses the clicked area after a search engine is selected and finds images below it.

It's not possible to know in advance if any images will be found, unless all pages are preemptively parsed, which would be expensive and wasteful, so the context menu item must be present at all times.

**Comment by dessant** [comment]
Adding icons for context menu items is only possible on Firefox 56+ at this time, but it's something I've been thinking about and will do in the future. We have an [issue](https://github.com/dessant/search-by-image/issues/10) for Karma Decay, the rest do not seem to be a good fit for this extension.

**Comment by dessant** [comment]
Favicons in the context menu have been implemented for Firefox 56+ (https://github.com/dessant/search-by-image/issues/28).
