### ISSUE TITLE
Add back icons in front of search mode options in the pop-up menu

### ISSUE THREAD

**Issue by mikelei8291** [dessant/search-by-image#145]
**Is your feature request related to a problem? Please describe.**
Before the recent update, there were icons in front of each search mode options in the pop-up menu, as shown in this image from the README of the project:
![options with icons](https://camo.githubusercontent.com/3fe413ed4cddf978ce027b6e6caa2e470d9241d4fda12f4165ce72fd9ec436bf/68747470733a2f2f692e696d6775722e636f6d2f7277556365646b2e706e67)

However, these icons were removed after the recent update, as shown in this image:
![options with no icon](https://user-images.githubusercontent.com/9620335/138219301-cac80248-8eab-4a12-86d9-f83e419d48b0.png)

As a long time user of the extension, it was very confusing when I tried to change options for the first time after updating to the new version, especially when you have also changed the name of some options. These icons are very intuitive and easy to understand at the first glance, and I wonder why you decided to remove them in the recent update.

**Describe the solution you'd like**
Add these icons back please.

**Comment by neoOpus** [comment]
Yes please

**Comment by neoOpus** [comment]
having the website icons as well in the right-click menu can be useful too

**Comment by mikelei8291** [comment]
@neoOpus The website favicons were already there in the context menu.

**Comment by neoOpus** [comment]
It doesn't seem so on my side

https://i.imgur.com/Rvz64LU.png

**Comment by mikelei8291** [comment]
@neoOpus Extension version 4.4.0 is showing favicons on Firefox 96.0b5, maybe it's a bug of Edge. You should open a new issue for this.

**Comment by dessant** [comment]
The API for adding icons to context menu items is only supported by Firefox.

**Comment by mikelei8291** [comment]
@dessant Thanks for the reply. Any thoughts on the original issue?

**Comment by dessant** [comment]
@mikelei8291, I'll look into adding an option for bringing back the icons.

**Comment by dessant** [comment]
Here's a preview of the new extension popup with menu icons.

<img width="374" src="https://user-images.githubusercontent.com/7513068/232279860-946ad6ba-dc52-476f-8bb8-8544d16e7c4f.png">
<img width="374" src="https://user-images.githubusercontent.com/7513068/232279861-5e56122c-950d-48c2-a7bb-720ecf5fd932.png">

**Comment by neoOpus** [comment]
it would be great to have the option to show the icons only on top as a toolbar (one less click)

**Comment by dessant** [comment]
@neoOpus, that would be nice to have, though the UI needs to be redesigned for that feature because there is not enough horizontal space on mobile. You can subscribe to this related issue, they will probably be implemeneted together: https://github.com/dessant/search-by-image/issues/219

**Comment by dessant** [comment]
Fixed in version 5.5.0, the update should arrive in the next few days.

**Comment by neoOpus** [comment]
Thanks for addressing it. Excited for the update! 👍🎉
