### ISSUE TITLE
Waterfox G4

### ISSUE THREAD

**Issue by PiliJ** [dessant/search-by-image#146]
**System**

* OS name: [e.g. Windows, Ubuntu] Windows
* OS version: [e.g. 10] 8.1x64
* Browser name: [e.g. Chrome, Firefox]Waterfox
* Browser version: [e.g. 60] G4
* Extension version: [e.g. 1.0.0]  4.0.0

**Bug description** I use 2 search engines : Yandex & Bing
The results are invisible images ...

<!--
![Image 003](https://user-images.githubusercontent.com/33757855/138230343-78a3d79c-dc4c-45bc-a20c-aa4594640931.jpg)

![Image 001](https://user-images.githubusercontent.com/33757855/138230318-f372be62-149b-4e24-9e05-23a9be50c21b.jpg)

**Comment by PiliJ** [comment]
Hi dessant,
The image is on the PC. I did also a test 
- with others images (on the PC), same result
- with Firefox and the same images I had no problem
I activate "use deep search ...", also same result
Thank you.

**Comment by dessant** [comment]
Have you used the Browse search mode or was the local image opened in a tab before searching? Please share a screenshot of the search results.

**Comment by dessant** [comment]
For anyone seeing striped images in search results: Firefox and its forks may silently decline canvas use when "privacy.resistFingerprinting" is set to `true`.

To fix the issue, go to `about:config` and set `privacy.resistFingerprinting.autoDeclineNoUserInputCanvasPrompts` to `false`, search for an image, and allow the use of HTML5 canvas image data, when the search engine requests it. Your next search should show search results correctly.

**Comment by PiliJ** [comment]
This is indeed the solution Dessant. If it was easy to allow the use of HTML5 in Yandex, it was not the case in Bing.
The window appears only for a very short time. You have to "shoot faster than your shadow" as Lucky Luke (comic strip)
Thank you !

**Comment by dessant** [comment]
The config option has stopped working in recent Firefox versions. The next version of the extension will pause and wait for users to give the search engine access to the canvas data, so you no longer have to touch config options. You can read more about the feature here: https://github.com/dessant/search-by-image/issues/407
