### ISSUE TITLE
99 out of 100 times, it just doesn't work

### ISSUE THREAD

**Issue by MysticalOS** [dessant/search-by-image#149]
Really just don't know what else to say. Open any webpage, any image, right click on it, choose to search google and fails. that's all there is to it. Very rare once in a while it might actually work but it's unpredictable when or why it'll work that 100th time when other 99 it failed.

I can literally reload page, restart safari, disable enable, uninstall reinstall. Doesn't matter. Go to a page, right click image, search by google, get the "something went wrong" error almost every time.

If I change search method to capture, that works a lot better but is a royal pain in the ass when you literally have a valid image url. Hell, I have even right clicked image, and choose "open image in new tab" and then on the new tap, opened directly to source image, right clicked and done "search by image" and still "something went wrong
<img width="370" alt="Screen Shot 2021-11-16 at 9 31 26 AM" src="https://user-images.githubusercontent.com/1899149/142005271-569565f7-aad6-4865-a9e7-0506274cc83b.PNG">
"

Happy to further debug, but first the error code would actually have to be useful. Should probably be more verbose on reporting problem, so  you can get better reports in return.

**Comment by dessant** [comment]
Hi Adam, I'm testing with Safari 15.1 on macOS 12.0.1, what's your browser and OS version? During the permission request, did you allow the extension to run on the current website only or all sites? Is Google the only engine that almost always fails?

Let's do our tests with the large Wikipedia logo on https://www.wikipedia.org. The search mode for the context menu is left as the default (Search URL).

1. Visit Wikipedia, right-click on the page and select Inspect Element, switch to the Console tab.
2. Right-click on the logo and begin your search with Google.

When you have selected Google from the context menu, does the error immediately appear without any other action, or is a new tab also opened by the extension?

If there is no new tab opened, please check the console on Wikipedia for any error messages, If there is a new tab opened, open the console there too and see if an error has been logged.

You could also switch to the "Select image" search mode for the context menu from the extension's options and see if Google will begin working. If you change the search mode from the popup directly, that will have no effect on the search mode of the context menu.

The extension should always log an error message, which will be either in the console of a tab or the background page. If we won't learn anything from this test, we will also check the background page.

I've followed these steps with a freshly installed extension, the extension was allowed to always run on every website, and the search was successful every time on Google.

**Comment by MysticalOS** [comment]
Aww i tried to actually show it with screen recorder, but screen recorder disables notification center...

but no new tab opens it just straight up fails with immediate error message.

**Comment by MysticalOS** [comment]
[Log] Error: Touch target missing (script.js, line 2)

**Comment by MysticalOS** [comment]
MacOS 12.0.1, Safari 15.1 (17612.2.9.1.20), happens on both my Intel mac and M1 Max macbook pro, running same software versions.

**Comment by dessant** [comment]
Thanks for sharing these details, the error points to the base module not being executed on page load: https://github.com/dessant/search-by-image/blob/master/src/insert/main.js#L13

When the parse module is injected at your request, it misses that dependency and shows an error: https://github.com/dessant/search-by-image/blob/master/src/parse/main.js#L343

The base module should always run in every page, when permissions allow it: https://github.com/dessant/search-by-image/blob/master/src/assets/manifest/safari.json#L73

How are permissions set up for the extension, is "for other websites" set to "Allow" in Safari website preferences?

![screenshot](https://user-images.githubusercontent.com/7513068/142035610-8a92e3fe-e540-44de-bcbf-1f3af590edc2.png)

Are you using any extension/app or config change that interferes with requests and JS execution in the browser?

**Comment by MysticalOS** [comment]
Permission for all websites.

So I turned off other extensions that use js and it seems to be a conflict with stop the madness i believe

Maybe @lapcat (https://github.com/lapcat/) can assess?

**Comment by dessant** [comment]
This is great, we're getting somewhere! So does Google *always* work as expected if that extension is kept disabled?

**Comment by MysticalOS** [comment]
hard to say, i'll get back on that. but working more than 1% of the time is huge step up.

**Comment by dessant** [comment]
It sounds like you've found a bug in StopTheMadness, if it's capable to also block extension scripts, maybe it's the word "insert" in the script path that is being picked up, but I can't tell without having access to the extension source.

Adam, I'd like to ask you something. My extension was getting some traction on the Mac App Store, it has even started to rank in the top paid extension category. Your review completely killed that upwind, and I no longer have any purchases from the Mac App Store. There were daily new installs up until the date you posted the review.

Would it be possible to remove that review? It affects me finacially, and I feel it's a bit unfair to suffer such losses because of it.

**Comment by MysticalOS** [comment]
Done, well i think so anyways. It doesn't let me delete it, but I tried to update it and submitted it, but still see old one :\

**Comment by dessant** [comment]
I've had a couple of ratings, but yours was the first text review. I've looked it up and it's possible to remove a review, the feature is a bit hidden. If you were able to replace both the title and the body of the review, it's probably fine to leave it, I think it may take some time before Apple publishes the update for the review.

If you weren't able to update the title, see below how to remove a review, but it's really not necessary if it was possible to update it completely, removals also appear to be delayed for 24 hours anyway, and your changes should show up tomorrow.

> Open the Mac App Store, click on your account name in the lower-left corner, click View Information at the top of the page, scroll down to the Manage section, and click on the Manage button on the right-side of Reviews and Ratings.

> The review should be listed there with a Remove button.

**Comment by MysticalOS** [comment]
Yeah I did that. it just takes up to 24 hours to do so.

I also write a new text one and that didn't appear either. Either way I github sponsored for 50 to compensate at least a dozen lost sales.

**Comment by dessant** [comment]
Oh wow, thanks for the sponsoring! It really wasn't necessary, but I truly appreciate it. :yum:

**Comment by lapcat** [comment]
This is just the "Contextual menus" website option in StopTheMadness. Disable that, and it should work.

**Comment by dessant** [comment]
Hi @lapcat, what's the exact way it interferes, does it block the "contextmenu" event?

**Comment by lapcat** [comment]
> Hi @lapcat, what's the exact way it interferes, does it block the "contextmenu" event?

Correct.

**Comment by dessant** [comment]
That sounds destructive enough to be disabled by default. Would it be possible to show a notice when the option is enabled in StopTheMadness about the possible pitfalls? Informing users would help avoid some of these issues.

**Comment by MysticalOS** [comment]
Just to add, disabling just the contextual stuff made it work more often than 1% but still fail a lot unless stop the madness was completely off..

For example on Okcupid, i reverse image search pictures that look catfishy and that simply won't work with stopthemadness enabled at all, even if contextual for title is disabled and the open link with is blank.

**Comment by lapcat** [comment]
> For example on Okcupid, i reverse image search pictures that look catfishy and that simply won't work with stopthemadness enabled at all, even if contextual for title is disabled and the open link with is blank.

This is what I meant:
<img width="459" alt="Screen Shot 2021-11-16 at 6 44 23 PM" src="https://user-images.githubusercontent.com/56086/142088936-10d71c32-7fc8-4062-9df3-49dd2d6cf8a1.png">

**Comment by MysticalOS** [comment]
Ah ok. I'll disable that.

**Comment by dessant** [comment]
I wonder if it will be needed to test for this issue and warn users, but first I'd need to better understand how this option behaves.

@lapcat, is the "Contextual menus" option enabled by default when the extension is installed? I don't have access to the source code, but I assume it calls `event.stopImmediatePropagation()` from a  `contextmenu` event listener attached to `window`. Is this correct, and does it do anything else?

@MysticalOS, have you noticed any other option in StopTheMadness that was interfering with Search by Image?

**Comment by MysticalOS** [comment]
no, it works fine now with option lapcat posted turned off

**Comment by dessant** [comment]
I have tried several extensions in Chrome and Firefox that make sure the context menu can be opened, and none of them caused any issues when searching from the context menu. I think StopTheMadness should revisit the implementation of this feature, and also inform users about what options do, and their possible side effects.

We cannot let other extensions affect the stability of Search by Image, so starting version 4.4.0 touch coordinates are always saved at the first opportunity on `pointerdown`, and if the `contextmenu` event is dispatched, we update the saved touch data. When the `contextmenu` event is blocked, users with motor issues may see slightly different selection results in some rare cases because the end of the touch cannot be saved, but the extension should generally work as expected.
