### ISSUE TITLE
Support custom search engine rule defined by user

### ISSUE THREAD

**Issue by mikelei8291** [dessant/search-by-image#15]
I used to use this image search extension ([Chrome Version](https://chrome.google.com/webstore/detail/image-search-options/kljmejbpilkadikecejccebmccagifhl), [Firefox Version (support data uri)](https://addons.mozilla.org/en-US/firefox/addon/image-search-options/)) made by the admin of saucenao.com (an image search engine).

This extension provides the function of adding custom rules by users themselves. This function is really useful for people who want to search on sites that do not currently included in the extension, and will also reduce your work load of adding more search engines.

The reason of I'm asking to add this function in your extension is the extension I mentioned before is no longer under maintenance, and it doesn't support data uri so I cannot search on some engines that only support sending POST requests with image data. Also, the UI is quite simple and old-fashion, but I love material design!

**Comment by dessant** [comment]
I've been thinking about allowing to define custom search engines even before the extension was created, but after some tests and during implementing some of the engines it became clear that it's a can of worms.

Some of them require their cookies to be sent during the POST, others need a random token set upon page load by js etc, so the best outcome would be some custom engines working, while others only failing in certain cases.

I'd be happier to just add some of the engines and ensure that they work as expected. Karma Decay is likely to be released next week. so.com, SauceNAO and Iqdb are also planned to be added. What are the engines you'd like to see included?

**Comment by mikelei8291** [comment]
Thanks for replying, I understand that you want to make the extension works well, so let's just implement them by hand.

Including SauceNAO and iqdb as you mentioned, here are some other engines I would like to see included:
- ascii2d: [https://ascii2d.net/](https://ascii2d.net/)
- WhatAnimeIsThis: [https://whatanime.ga/](https://whatanime.ga/)

Thanks!😉

**Comment by dessant** [comment]
Thanks a lot for the suggestions, I have opened a couple of new issues for each of them.
