### ISSUE TITLE
Convert new image formats before uploading

### ISSUE THREAD

**Issue by dessant** [dessant/search-by-image#153]
Many sites now serve WebP and AVIF images in browsers that support these formats, but some search engines may not be able to process them. We should attempt to convert these images before uploading to search engines which do not support new image formats.

**Comment by robertheadley** [comment]
I was actually conisdering suggesting this, because Pimeyes for example does not support WebP and I know libraries exist for converting formats.

**Comment by neoOpus** [comment]
also having a tiny editor (from other open-source) would be great as it can save time

**Comment by dessant** [comment]
We're going to use the browser's decoder and convert images to PNG with canvas when the image is WebP or AVIF and the engine does not support the format. This way we will fix the most prevalent issue, without having to test engine support with a larger set of image formats. In the future we could switch to maintaining a complete list of supported formats for every engine, and converting the source image when needed.

**Comment by dessant** [comment]
The fix has been published with version 4.9.0. You should see a small delay when image conversion is attempted in Chromium variants due to a browser bug that limits the processing speed of the extension background page because it thinks it's a low priority process, even when it receives a new event. A hacky workaround is to inject an iframe with an empty document belonging to the extension in the active tab before converting the image so that the browser categorises the extension as active, or send the image in the active tab for processing. We'll implement a workaround if the bug will still be present with Manifest V3.
