### ISSUE TITLE
Add Google Lens

### ISSUE THREAD

**Issue by jomo** [dessant/search-by-image#154]
It would be great to add Google Lens, which tries to detect objects inside the image rather than just finding the same or similar images, like Google Images does.

The implementation seems quite simple: https://github.com/typeling1578/Search-on-Google-Lens/blob/a0d3ecc5e64e85884993577fc62411bc2d2c9269/background.js#L67-L71

**Comment by dessant** [comment]
Version 4.5.0 has been submitted to extension stores with support for Google Lens. The service requires a desktop user agent, and Safari has no extension API for modifying HTTP headers, so Google Lens is not yet supported on iOS. Please let me know if you discover a way to view Google Lens search results in a mobile browser.
