### ISSUE TITLE
Shorten CFBundleDisplayName on iOS

### ISSUE THREAD

**Issue by Taxyovio** [dessant/search-by-image#157]
**Is your feature request related to a problem? Please describe.**
The app name “Search by Image for Safari” on iOS/iPadOS is too long to be displayed in full on home screen or app library. It’s truncated as “SearchbyImagef…” on iPad at default font size. 

![1AC8DFAB-9B7F-45D4-831A-D23E17BBDACE](https://user-images.githubusercontent.com/38234151/147665132-a66ed674-e3de-40b6-aba9-d4920f213e6d.jpeg)

**Describe the solution you'd like**
Change CFBundleDisplayName to “Search by Image”.

**Comment by dessant** [comment]
Hi @Taxyovio, thanks for the feature request! I'll update the display name in the next release.

**Comment by dessant** [comment]
Version 4.5.0 with a shorter display name on iOS and iPadOS has been submitted for review.

![screenshot](https://user-images.githubusercontent.com/7513068/148654248-afff3e71-9270-4abf-8bc3-8e485b12dbd7.png)
