### ISSUE TITLE
Context menu doesn't work on local files

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#159]
When you right-click over a local image (file:///C:/...) it doesn't show Search by Image, FYI "Allow access to file URLs" checked...

**Comment by dessant** [comment]
The feature is only available on Firefox, Chromium does not allow extracting canvas data when an image wilth a `file://` URL is added, the issue is tracked at https://github.com/dessant/search-by-image/issues/93.

**Comment by dessant** [comment]
This issue was fixed, details in https://github.com/dessant/search-by-image/issues/173.
