### ISSUE TITLE
Ability to search images from clipboard

### ISSUE THREAD

**Issue by btnlq** [dessant/search-by-image#16]
I often need to search a screenshot. Currently, I have to save it to a file and browse or drag it. It would be more convenient to search an image from clipboard. For example, Windows 10 hotkey Win+Shift+S saves screenshot directly to clipboard.

Of course, this feature will be useful in general: copying file can be faster than browsing or dragging it.

**Comment by dessant** [comment]
@btnlq, thanks for this great idea! In the next release you'll be able to paste images from the clipboard with the usual shortcuts and by right-clicking in the Browse page.

![screenshot from 2017-12-18 19-57-52](https://user-images.githubusercontent.com/7513068/34125365-b49e4c4a-e43e-11e7-8977-5321f210ede7.png)

**Comment by dessant** [comment]
The update has been released for Chrome and Firefox.
