### ISSUE TITLE
Does not install in Safari

### ISSUE THREAD

**Issue by garyscott1** [dessant/search-by-image#160]
**System**

* OS name: macOS Monterey
* OS version: 12.1
* Browser name: Safari
* Browser version: 15.2
* Extension version: 4.5.0

The extension was working fine until my safari program became corrupted/unrepairable and I had to create a new admin user ID account and transfer all my files, etc. to my new Mac user account in order to run Safari. When I tried to reinstall this extension it does not install and there is no error message. I tried uninstalling & reinstalling several times, also deleting old safari account does not help. Please help

**Comment by dessant** [comment]
Hi, does the Search by Image app appear in the Applications folder after installing it from the Mac App Store?

**Comment by garyscott1** [comment]
Yes it's in the applications folder. It downloads normally, but when I get to the prompt "Quit and Open Safari Preferences..." I click on it and nothing happens. "Get info" says it was opened but like I said nothing happens, the prompt message is still there no matter how many times I click it.
    On Thursday, January 20, 2022, 01:20:56 PM PST, Armin Sebastian ***@***.***> wrote:  
 
 


Hi, does the Search by Image app appear in the Applications folder after installing it from the Mac App Store?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dessant** [comment]
Not sure why the button stopped working on your device, but you could try visiting Extensions preferences manually at Safari > Preferences > Extensions. If Search by Image is listed there, select the checkbox to enable the extension.

![screenshot1](https://user-images.githubusercontent.com/7513068/150698253-fcfd2fb6-59c5-4cd9-a75a-5485654460d4.png)

**Comment by garyscott1** [comment]
No it's not there -- the only extension in Safari preference is WayBack Machine which is not active. Since it worked on a previous user account that was disabled/corrupted is there a limit to how many times this may be installed? Only my 2nd time, but seems like some type of conflict with previous installation. I did uninstall and reinstall but did not help.
    On Sunday, January 23, 2022, 01:18:10 PM PST, Armin Sebastian ***@***.***> wrote:  
 
 


Not sure why the button stopped working on your device, but you could try visiting Extensions preferences manually at Safari > Preferences > Extensions. If Search by Image is listed there, select the checkbox to enable the extension.



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dessant** [comment]
I've found an issue that describes the same symptoms, and it appears to be a macOS bug, but there is a workaround. Call this command from Terminal and restart your Mac:

```sh
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Safari.app
```

https://github.com/refined-github/refined-github/issues/4216

https://github.com/refined-github/refined-github/issues/4216#issuecomment-817097886
