### ISSUE TITLE
Show context menu for only images

### ISSUE THREAD

**Issue by jtagcat** [dessant/search-by-image#164]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType

Currently, it thinks everything is an image: the current page, a link, etc.

It's annoying to have it bloat other menus.

**Comment by dessant** [comment]
https://github.com/dessant/search-by-image/wiki/Why-is-the-extension-always-visible-in-the-context-menu%3F
