### ISSUE TITLE
Default search engine

### ISSUE THREAD

**Issue by fpetrakov** [dessant/search-by-image#165]
**Is your feature request related to a problem? Please describe.**

The problem is that every time I have to choose a search engine when searching for a picture.

**Describe the solution you'd like**

It would be nice to be able to select a default search engine in settings so that you don't have to select the search engine from the dropdown context menu each time. So that way I will be able to just right-click on the picture and select "Search by Image" not waiting the dropdown to show up.

**Comment by dessant** [comment]
An extension can only add a single top-level item to the context menu. You can leave a single search engine enabled to search without having to open a submenu.
