### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by RayCist1608** [dessant/search-by-image#166]
Microsoft Edge
Version 98.0.1108.50 (Official build) (64-bit)

Clicking the extension does nothing (usually it would ask to select an image to upload for reverse image search)
And going to the extension options just shows a blank page.

**Comment by dessant** [comment]
Have you tried restarting the browser?

**Comment by RayCist1608** [comment]
Already restarted and apparently after loading an unpacked version by downloading from this repo, it says it's missing the manifest file.

**Comment by dessant** [comment]
The repository contents are not supposed to be used as an extension package, the unsigned release packages can be downloaded here: https://github.com/dessant/search-by-image/releases

I'd recommend to uninstall and reinstall the extension from the extension store instead, and test the issue with a different browser profile if that fails.
