### ISSUE TITLE
Suddenly Stopped Working

### ISSUE THREAD

**Issue by RayCist1608** [dessant/search-by-image#167]
**System**
* OS name: Windows
* OS version: 10 21H1 19043.1526
* Browser name: Microsoft Edge
* Browser version: 98.0.1108.50 (Official build) (64-bit)
* Extension version: 4.5.0

**Bug description**
No response from extension, extension is not appearing in the right click context menu. Disable and reenabling has no effects, which used to help when it doesn't appear in the right click context menu. Going to extension options page shows a blank page. Clicking on extension does nothing when it used to show a list of search engines to use to search an image.

Tried to install 4.5.0 from releases and is now working again. Something with the one download from Chrome webstore is wrong perhaps? For now I'll keep using this one.

**Comment by dessant** [comment]
I can't reproduce the issue, please follow my recommendation [here](https://github.com/dessant/search-by-image/issues/166#issuecomment-1037052683) and let me know if the issue is still present in a new browser profile.

**Comment by RayCist1608** [comment]
Oddly it has happened again, but this time it happened after the browser froze and crashed. I noticed the extension couldn't display it's options page. Currently I am reinstalling.
