### ISSUE TITLE
Add custom image search engines

### ISSUE THREAD

**Issue by Saectar** [dessant/search-by-image#168]
It would be quite useful if the add-on had the option to allow users to add their own custom image search engines.

Currently the [Image Search Options](https://addons.mozilla.org/firefox/addon/image-search-options/) add-on allows this possibility.

![Image Search Options](https://i.imgur.com/irWj8rg.jpg)

**Comment by dessant** [comment]
This feature has been requested a couple of times, but it's not on the roadmap, search between issues for previous discussions.

If you would like to see a reverse image search engine implemented, please share a link.

**Comment by dessant** [comment]
https://github.com/dessant/search-by-image/issues/15#issuecomment-352260554
https://github.com/dessant/search-by-image/issues/50#issuecomment-487301672

**Comment by Saectar** [comment]
Thanks for the reply.

I understand. Hopefully in the future they change their minds and can include that possibility.

And could the [Web Archives ](https://github.com/dessant/web-archives) add-on include the ability to add custom sites?

**Comment by dessant** [comment]
What archive or cache sources would you like to add to Web Archives?
