### ISSUE TITLE
Add ascii2d.net as a search engine

### ISSUE THREAD

**Issue by timescam** [dessant/search-by-image#170]
**Is your feature request related to a problem? Please describe.**

Add https://ascii2d.net as a search engine

**Describe the solution you'd like**

url format: `https://ascii2d.net/search/url/${imageUrl}?type=color`
example: https://ascii2d.net/search/url/https://i.pximg.net/img-master/img/2021/10/04/23/48/26/93229686_p1_master1200.jpg?type=color

**Additional context**

Useful for reverse searching weeb artworks on pixiv, twitter, etc

**Comment by dessant** [comment]
You can enable the search engine from the extension's options.
