### ISSUE TITLE
Cannot open private tabs on Firefox for Android

### ISSUE THREAD

**Issue by IanSzot** [dessant/search-by-image#172]
**System**

* OS name: Android
* OS version: 11
* Browser name: Firefox
* Browser version: 98.1.1
* Extension version: 4.5.0

**Bug description**

Very simple: When doing a search by image on a private tab, Search by Image will open another private tab BUT this tab will NOT be actually a private tab. It will appear as one but it is actually saving your search on your search history and on your Google account.

**Logs**

```
No logs
```

**Comment by dessant** [comment]
This is a long-standing bug in Firefox, and there does not appear to be any workaround.

You can subscribe to this issue for updates: https://bugzilla.mozilla.org/show_bug.cgi?id=1372178
