### ISSUE TITLE
Saves history when browsing incognito 

### ISSUE THREAD

**Issue by okwhynot1** [dessant/search-by-image#174]
**System**

* OS name: [android]
* OS version: [11]
* Browser name: [Firefox nightly(also happens with regular firefox)]
* Browser version: [100]
* Extension version: [4.6.0]

**Bug description**
When browsing in incognito mode and using this add-on to reverse search an image it will save the search to your history.

**Comment by dessant** [comment]
https://github.com/dessant/search-by-image/issues/172

**Comment by okwhynot1** [comment]
> https://github.com/dessant/search-by-image/issues/172

Thanks, I failed to find the post when I searched yesterday.
