### ISSUE TITLE
"Site" and other our preset parameters for Google Image Search

### ISSUE THREAD

**Issue by conderus** [dessant/search-by-image#175]
**Is your feature request related to a problem? Please describe.**

I need to search images with google, but only on particular marketplaces to compare them. So When I search by image, then I must add manually site parameter, for example, "site:amazon.com", and then I have only images from the amazon website or aliexpress for example

**Describe the solution you'd like**

The possibility to add some presets with parameters will be input to google search by image after search. Always after such search, we have an image there, and some text next to it describing the image (it's useless always) - I showed it on the print screen at the end. And then when we delete it and input our for ex. "site:" I have what I need. So it doesn't have to be a "site" only parameter, google has many such search parameters, so when we create our presets for Google, it should be available for easy use from the drop-down menu when we click on the image. So each preset would have a short name chosen by us, for easy use.

**Additional context**

How it looks like after search, and how I would like it to look with the "site" preset parameter for the particular marketplace for example (shopee here)

https://ibb.co/D5Qs7jj

**Comment by dessant** [comment]
This is definitely a feature that I want to implement, you will be able to set up the same search engine with different presets. The issue is currently tracked at https://github.com/dessant/search-by-image/issues/68, please subscribe to that thread for updates.
