### ISSUE TITLE
FEATURE: Remove copy/paste permissions

### ISSUE THREAD

**Issue by ivnnv** [dessant/search-by-image#176]
**Is your feature request related to a problem? Please describe.**
Why do you need copy/paste permissions?

**Describe the solution you'd like**
Remove permissions request

**Describe alternatives you've considered**
Do not require permissions as it used to be

**Additional context**
Requesting unneeded things is bad :)

**Comment by dessant** [comment]
Which browser are you using?

**Comment by ivnnv** [comment]
Chrome Mac: 99.0.4844.83
<img width="376" alt="1" src="https://user-images.githubusercontent.com/23552631/160789191-8f71a8c9-8ba2-4f62-b047-8ada7377fb1c.png">
<img width="328" alt="2" src="https://user-images.githubusercontent.com/23552631/160789208-024dd62a-f46c-44b6-bfbd-9e25eddaa596.png">

**Comment by smolboii** [comment]
i get same thing on Windows: Chrome Version 100.0.4896.60 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/52638226/160790461-0ad78d8f-e7a9-4408-8c78-9a7c0d544d45.png)

**Comment by dessant** [comment]
See the discussion at https://github.com/dessant/search-by-image/issues/114.
