### ISSUE TITLE
Needs permission to things I copy/paste now ?

### ISSUE THREAD

**Issue by FitzcairnHS** [dessant/search-by-image#178]
Why ? I'm afraid i will have to uninstall this great addon

**Comment by dessant** [comment]
See this issue for details: https://github.com/dessant/search-by-image/issues/114

**Comment by Moon1moon** [comment]
Same, I saw a notification in my phone that say this extension wants copy permission
I opened my pc. My browser say same thing. 🙃

**Comment by fattydepp** [comment]
i really wonder why they asking for copy/paste thing.

**Comment by arekm** [comment]
Too bad that this can't be optional (AFAIK it can but makes development harder) or even as a separate extension. I guess right now the only option is to manually load older version of the extension. Unfortunately giving access to clipboard is way, way too much (too many sensitive data there) especially for (in my case) feature that never had a need to use.

**Comment by nascentt** [comment]
Have to remove the addon then.  Seems silly to add intrusive permissions for some random use case.
Hope you create a separate addon without unnecessary clipboard permissions.

Sadly there's no other addon as good as this one was.

**Comment by lilithium-hydride** [comment]
If it helps anyone, Vivaldi now has a built-in image search function. You can set the Image Search Engine to Yandex or whatever your preferred image searcher is, no extensions needed.
