### ISSUE TITLE
Disable/optional clipboard permission

### ISSUE THREAD

**Issue by fhtdtdj** [dessant/search-by-image#179]
Latest version adds clipboard search and therefore requires clipboard access permission. I understand image clipboard search was a user request but this is an obvious privacy/security concern. Why alienate your userbase over a minor feature request? I'm afraid I'll have to stop using this add-on for now.

https://github.com/dessant/search-by-image/issues/114

**Comment by dessant** [comment]
Please don't wast my time by opening new issues.
