### ISSUE TITLE
Share images from web pages

### ISSUE THREAD

**Issue by dessant** [dessant/search-by-image#183]
The browser's native share service may not work for all images on a page, so a button to extract an image from a page for sharing was added last year to Samsung Internet. Now we can enable sharing for Safari 15 and browsers based on Chromium on Windows and Android. The feature will also be enabled on other platforms when they'll support file sharing using the [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#browser_compatibility).

**Comment by dessant** [comment]
The share button can be hidden from the toolbar popup and the context menu from the extension's options on supported platforms.

**Comment by fireattack** [comment]
How does it work? I tried it on lots of image, they all say "the selected image cannot be shared". I use Chrome.

**Comment by dessant** [comment]
@fireattack, which OS?

**Comment by fireattack** [comment]
I use Windows.

**Comment by dessant** [comment]
Thanks for the details, I will hide the button on older Windows versions.
