### ISSUE TITLE
Feature suggestion: Implement reverse search by dragging image

### ISSUE THREAD

**Issue by ericpa06** [dessant/search-by-image#188]
Similar to what this userscripts does:
![image](https://user-images.githubusercontent.com/6937720/164934127-87e2c1d5-871a-4a60-93d3-0cc643a0cfa7.png)
https://greasyfork.org/en/scripts/382944-reverse-google-image-search-anywhere

**Comment by dessant** [comment]
Supporting drag and drop on random web pages would be problematic, the web page could steal your dropped images. Even if we show our user interface in an iframe, the site could just replace the entire user interface of the extension to intercept the image when it is dropped. The script you shared appears to also allow the current web page to access the dropped image.

You can drop images securely on the Browse page, switch to the browse search mode and select an engine to open the page. One day we could allow to open the browse page in a sidebar and keep it open between searches, that would be useful when you need to perform multiple searches and you prefer to drop images.

There's also a plan to integrate the extension in the Share popup on Windows, like we do for Safari, and possibly the context menu of File Explorer. That could also help speeding up searches with local images.

At the moment the fastest way to search for a local image is to copy it from your file manager, then open the extension popup in your browser. The copied image is automatically detected and shown in the Browse search mode, but this feature is unfortunately [not supported in all browsers](https://github.com/dessant/search-by-image/issues/114#issuecomment-1082778558).
