### ISSUE TITLE
Facebook Capture issue

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#194]
Hello Armin,

I have an issue with Facebook when using the capture feature it shows a white overlay that is opaque, I thought it is due to some other extensions / userscripts conflicts or something else (flags) I reset all to default and disabled everything... but I am unable to figure out what is causing it!

I am using Edge (Latest stable version), I am tinkering with HW acceleration and thought it may be the issue but even without any I still see the problem, I am going to do some more investigations but the odd thing is that it happens only in FB so far... the odd part is that inPrivate window and another profile with the same flags it works... I've reset the main profile to default but I still have this issue, I am more after figuring out what causes it than just fixing it by switching to a new profile.

<html>
<body>

Microsoft Edge | 102.0.1245.33 (Official build) (64-bit)
-- | --
Revision | 41285f1c5672f618820f679d5efba8bafa4828de
Operating system | Windows 11 Version 22H2 (Build 25131.1000)
JavaScript | V8 10.2.7.2
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33
Command-line | "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --profile-directory=Default --enable-features=GlobalMediaControlsModernUI,JXL,VaapiVideoDecoder,VaapiVideoEncoder,CanvasOopRasterization --enable-oop-rasterization --enable-unsafe-webgpu --flag-switches-begin --enable-experimental-cookie-features --enable-gpu-rasterization --enable-zero-copy --ignore-gpu-blocklist --enable-smooth-scrolling --use-angle=d3d11 --enable-features=GlobalMediaControlsModernUI,JXL,VaapiVideoDecoder,VaapiVideoEncoder,CanvasOopRasterization,BackForwardCache,CalculateNativeWinOcclusion,FileHandlingAPI,FileHandlingIcons,GlobalMediaControls,HardwareMediaKeyHandling,OmniboxTabSwitchSuggestions,OmniboxTriggerForPrerender2,OverscrollHistoryNavigation,ParallelDownloading,Prerender2,PwaUpdateDialogForIcon,PwaUpdateDialogForName,SystemNotifications,TabHoverCardImages,V8VmFuture,WebUsbDeviceDetection,msAutoplayUserSettingBlockOption,msClickOnceFlag,msEdgeFindAura,msEdgeOmniboxAura,msEdgeQBox,msEdgeShare,msEdgeTabGroupsAutoCreate,msEdgeWebAppSidebar,msEnableDeveloperControlCenter,msEnhancedTextContrast,msExperimentalScrolling,msFavoritesAdminExport,msGroupNotificationsByDomainWinrt,msHideFluentScrollbarsOnPointerLeave,msLinkedAccountData,msMediaFoundationOverride,msNotificationPlatformBridgeWinrt,msOverlayScrollbarWinStyleMasterFlag,msPdfDigitalSignatureRead,msRefreshRateBoostOnScroll,msSourcesPrettyPrintByDefault,msTabGroupsCollapseFreezing,msVisualRejuvMaterialsMenu,msVisualRejuvShowSettings --flag-switches-end

</body>
</html>

**Comment by dessant** [comment]
I haven't been able to reproduce the bug, please let me know when you find a way to replicate it, if the issue is indeed caused by the extension.

**Comment by neoOpus** [comment]
I am still unable to figure out this, other profiles work but the main one I am using for browsing after disabling almost everything I still have this issue... I am trying to solve it myself so if someone else encounters it at least you can redirect it to this case.
