### ISSUE TITLE
this is very nice but lacking some fundamentals

### ISSUE THREAD

**Issue by justsome12** [dessant/search-by-image#202]
dark mode
sorting search engines
grouping in folders (middle click open all)
allow user specific search engines (missing e.g. aliseeks which I need a lot but is not added and I can't)

**Comment by dessant** [comment]
Here are some of the issues you can follow for the topics you listed:

https://github.com/dessant/search-by-image/issues/86
https://github.com/dessant/search-by-image/issues/68
https://github.com/dessant/search-by-image/issues/139
