### ISSUE TITLE
Automatically resize images

### ISSUE THREAD

**Issue by Lenr0k** [dessant/search-by-image#203]
Hi there,

I've noticed that when using your search by image plugin, images are not automatically compressed to the size limit set by search engines. This can result in the image not getting reverse searched.

I think it would be a great idea if your plugin implemented a feature that automatically compressed images to the size limit set by search engines. This would improve the user experience and make your plugin even more useful.

Thanks for your time

**Comment by dessant** [comment]
This should be easy to implement, we have most of the code ready becuase images are already resized for a couple of search engines.
