### ISSUE TITLE
Pimeyes group buy or premium?

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#206]
Wondering if there is some who are interested in making a group buy of Pimeyes service that I find useful but pretty expensive (While I still have few hacks to get some results with it) that can be used with this extension by having it manage it so no one, something like sending them to a pre-configured container that will hold the credentials of the paid account and return the images accordingly... it is just an idea and I know it can be implanted but I don't know much this far about the legality of it, but I am sure there are always way to circumvent by carefully reading their terms and doing it maybe through an LLC, this plan if shared by $328 users make it very interesting to have, so it could be a good source of income also to you that you should explore… I am confident that there are, 1000x from dating scene who are willing to pay $1 / month to have access to that service like some organization already does via your extension that can become a freemium (but please keep all what is already free, free)…

![image](https://user-images.githubusercontent.com/1388336/180597063-35de295d-43db-48c7-b1f5-a663934ec350.png)

**Comment by dessant** [comment]
Their [terms of service](https://pimeyes.com/en/premium-terms) only allows uploading your own images (III. 3.). I think most of their users break the TOS, and if the'd also see a large volume of requests coming from an account, they could shut it down (IV. 4.), so it would be risky to invest into providing this service.

You could look for people on Reddit who may be interested in a group buy: https://www.reddit.com/r/OSINT
