### ISSUE TITLE
Add immerse.zone

### ISSUE THREAD

**Issue by neoOpus** [dessant/search-by-image#207]
Hi Armin,

I found this service and I think it can be added to the list too :)

https://www.immerse.zone/

**Comment by nightkall** [comment]
Great service! it would be nice to have it in the extension. You can search by adding the image URL https://www.immerse.zone/image?url=**HERE** so it shouldn't be hard to **add a custom search engine** option for those types of search engines.

**Comment by dessant** [comment]
Let's track this at https://github.com/dessant/search-by-image/issues/220.
