### ISSUE TITLE
UI looks squished when in overflow menu

### ISSUE THREAD

**Issue by dexeonify** [dessant/search-by-image#208]
**System**

* OS name: Windows
* OS version: 11
* Browser name: Firefox
* Browser version: 105.0a1
* Extension version: v5.2.0

**Bug description**

This is how the extension popup looks normally, when it's in Firefox toolbar:
![image](https://user-images.githubusercontent.com/72267349/185782913-2c8f531a-2e2e-4eb3-a325-0f1701877796.png)
and this is how it looks in the overflow menu, you can barely see the dropdown options:
![image](https://user-images.githubusercontent.com/72267349/185783013-d95d8f99-7284-4b2f-9bed-bbb7f6a8d57e.png)

To add an extension into the Overflow menu, click the hamburger (☰) button > More tools > Customize toolbar, then drag "Search by Image" into the overflow menu. I usually put inactive extensions in the overflow menu for less clutter. But when I do need to use the popup, it's difficult to navigate in the tiny window.

So, is it possible to increase the size of the popup window? It doesn't have to be as big as the one in the Firefox toolbar, just bigger than it is now. Displaying scrollbar is fine.

**Logs**

No logs.

**Comment by dessant** [comment]
Thanks for the bug report! This must be triggered by a recent change, the extension popup was displayed correctly in the past. The bug can also be reproduced in Firefox 103.0.2.

**Comment by dexeonify** [comment]
Nope, I was able to reproduce it as far back as Firefox v95 using `mozregression`. I vividly remember encountering this issue when I first installed it but haven't been bothered to report it.

**Comment by dessant** [comment]
It is caused by a change in the extension, the document height is not set correctly.

**Comment by dexeonify** [comment]
Apparently this got fixed by Firefox's devs themselves not long after this issue is reported (14 days ago).
Ref: [bug 1783972](https://bugzilla.mozilla.org/show_bug.cgi?id=1783972)
Screenshot: 
![image](https://user-images.githubusercontent.com/72267349/188658145-173f13db-0743-410b-b1cc-fdb19fc62e3a.png)
