### ISSUE TITLE
image search from imgur to saucenao fails.

### ISSUE THREAD

**Issue by kotenok2000** [dessant/search-by-image#209]
**System**

* OS name: Windows
* OS version: 11
* Browser name: [e.g. Chrome, Firefox]
* Browser version: [e.g. 60]
* Extension version: [e.g. 1.0.0]

**Bug description**
.Try to search reverse search in saucenao any image from imgur with this extension.

Anonymous GET queries for this image host are blocked due to abuse. Please log in, search via the main page's URL field, or retry with a POST type request...

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
It looks like we will need to use their search form when searching for an image URL. As a workaround you could switch to the "Select image" search mode for now, and that will upload the image instead.

**Comment by RokeJulianLockhart** [comment]
@dessant, I still experience this. [^1]

[^1]: [`https://saucenao.com/search.php?db=999&url=https%3A%2F%2Fimg3.saucenao.com%2Fmadokami%2FManga%2FW%2FWE%2FWEEK%2FWeekly%2520Shonen%2520Jump%2FWeekly%2520Shonen%2520Jump%25202014%2520No.36.cbz%2FP00067.jpg%3Fauth%3D4-tOhevaZAbkI9ZVPTxByw%26exp%3D1773169200&__cf_chl_tk=1VfsssfO57ePQw8lQvPLYNlzmPmd5H44g191xCEtZmI-1772927056-1.0.1.1-HqbJdqKd1h4B2n3t562LGgqEU.2a92SYKGoFUYFkWLw`](https://saucenao.com/search.php?db=999&url=https%3A%2F%2Fimg3.saucenao.com%2Fmadokami%2FManga%2FW%2FWE%2FWEEK%2FWeekly%2520Shonen%2520Jump%2FWeekly%2520Shonen%2520Jump%25202014%2520No.36.cbz%2FP00067.jpg%3Fauth%3D4-tOhevaZAbkI9ZVPTxByw%26exp%3D1773169200&__cf_chl_tk=1VfsssfO57ePQw8lQvPLYNlzmPmd5H44g191xCEtZmI-1772927056-1.0.1.1-HqbJdqKd1h4B2n3t562LGgqEU.2a92SYKGoFUYFkWLw#:~:text=Anonymous%20GET%20queries%20for%20this%20image%20host%20are%20blocked%20due%20to%20abuse%2E%20Please%20log%20in%2C%20search%20via%20the%20main%20page%27s%20URL%20field%2C%20or%20retry%20with%20a%20POST%20type%20request%2E%2E%2E)
