### ISSUE TITLE
private browsing

### ISSUE THREAD

**Issue by Mortasi** [dessant/search-by-image#21]
> A developer has replied to your review of add-on Search by Image - Reverse Image Search.
> 
> Reply:
> Please open an issue on GitHub and explain in more detail what it means to break private browsing on > Android.
> 

I would have thought it obvious, but maybe this just happens to me? If i use it in private mode it will open the image search tab in normal tab.

edit: using firefox

**Comment by dessant** [comment]
The extension API does not yet support opening private tabs on Android.
https://bugzilla.mozilla.org/show_bug.cgi?id=1372178

**Comment by dessant** [comment]
The limitation has been documented in the AMO description.
