### ISSUE TITLE
Pimeyes is broken again

### ISSUE THREAD

**Issue by deltabravozulu** [dessant/search-by-image#210]
**System**

* OS name: Mac OS
* OS version: 12.5.1
* Browser name: Chromium
* Browser version: 95.0.4638.69
* Extension version: 5.2.0

**Bug description**
Pimeyes pushed an update about a month ago to its results page; the upload page seems to have recently changed its behavior such that the search by image script no longer figures out how to inject the image. 

**Logs**

Could not find any of any utility.

**Comment by dessant** [comment]
The fix was tested with the free demo. If you have a paid account, please let me know how it works while you're logged in.
