### ISSUE TITLE
When batch downloading images, folder is not created based on page title in the Image Picka folder

### ISSUE THREAD

**Issue by klehman775** [dessant/search-by-image#211]
**System**

* OS name: Windows 11
* OS version: [e.g. 10]
* Browser name: Firefox
* Browser version: 104.0.2
* Extension version: 0.15.1

**Bug description**

Trying to download batch images but when attempted it just download all to the Image Picka folder in the Downloads folder instead of creating a folder based on the page title. I didn't change any from the default settings, so the default path when saving images is still, Image Picka/${pageTitle}/${index} - ${name}${ext}

**Logs**

N/A

**Comment by dessant** [comment]
This is an unrelated project, I think you wanted to open an issue here: https://github.com/eight04/image-picka/issues
