### ISSUE TITLE
Some way to search by image, even when the image changes when the cursor is placed over it?

### ISSUE THREAD

**Issue by SteegHobland** [dessant/search-by-image#213]
I have the problem that I can't search by image, when the image changes when I place my cursor over it. An example is Youtube thumbnails.

I'd like some way to search by those images, even though that change to something else when I try to select them.

I haven't tried any alternatives, because I don't know any.

**Comment by dessant** [comment]
On YouTube the extension will extract the thumbnail even if the video starts playing on mouse hover, the "Select URL" and Select image" search modes should both work.

In general you can also switch to the "Capture" search mode to search with an area of the page. In this search mode mouse movements will have no effect on the page.

**Comment by dessant** [comment]
And with tricky images that immediately change the image `src` if you move the mouse over them, you can click near the image instead to initiate a search, the search area will expand with 24 pixels to all directions from the place you have touched, and the extension will detect the nearby image.

**Comment by SteegHobland** [comment]
Thank you for pointing out these features! I was not aware of them, and they cover all I need for now.
