### ISSUE TITLE
Strange behaviour when using google-image-direct-view user script

### ISSUE THREAD

**Issue by LurkerHub** [dessant/search-by-image#218]
**System**

* OS: Windows 10 Pro 21H1
* Browser: Firefox developers edition 106b9
* Extension version: 5.3.0

**Bug description**

This is a strange issue involving an interplay between this extension and a user script.

Here's how I can isolate and reproduce it:

1) Create a new Firefox profile

2) Install Search By Image

3) Install Tampermonkey or GreaseMonkey 

4) Install the script from https://greasyfork.org/en/scripts/398189-google-image-direct-view

No customization, everything is at defaults.

5) Navigate to https://www.google.com/search?q=%22Why+We+Love%E2%80%94And+Loathe%E2%80%94The+Humble+Pig%22&tbm=isch

6) Click on the 2nd image (size 374x250)

7) Page will display the image on the right

8) Hover over the image on the right and wait for "image url updated" popup, wait a couple of seconds more then middle-click on the image.

9) The full size image will be loaded in a new tab

10) Right click on the full-size image, select "Search by image" and "google"

11) Google complains that the page is unreachable:
![image](https://user-images.githubusercontent.com/20542915/196576390-1a31a089-08c2-4cbf-a7c8-bd4954e87f88.png)

But wait, there's more!

12) Copy the link from step 9 and paste it into a new tab ( the URL is https://i.natgeofe.com/n/3196357c-b9ff-45f3-98d6-9b02517429f9/01booktalkpig.jpg?w=374&h=250 )

13) Right-clicked on the image, selected "Search by image" and "google"

14) Google is happy:
![image](https://user-images.githubusercontent.com/20542915/196576920-ea094d1a-fbdb-4839-81cb-037e6499b599.png)

The script author claims they cannot reproduce it, so not much help from them

**Comment by dessant** [comment]
I have closely followed the reproduction steps, but I could not trigger the bug in Firefox. The user script loads the full-size image (https://i.natgeofe.com/n/3196357c-b9ff-45f3-98d6-9b02517429f9/01booktalkpig.jpg), and I can search with it on Google.

I'm not sure what is causing the issue on your end, but it's possible that you could avoid it by switching to the "Select Image" search mode from the extension's options, that way the extension will always search with the image file instead of the URL.

**Comment by alexolog** [comment]
Something is happening on my end, but I am at a loss of how to investigate it since I started from a blank state and others are not able to reproduce it.

Any suggestions on how I can get more info?
