### ISSUE TITLE
Context menu for images only

### ISSUE THREAD

**Issue by rapnoize** [dessant/search-by-image#22]
Right now, "Search Image On..." option appears on all available context menus: general context menu (when you right-click on an empty space), selected text CM, and image CM. It would be nice if we get the option to choose where it appears.

Firefox 58

**Comment by dessant** [comment]
Thanks for filing an issue, though it appears to be a duplicate. I've posted an explanation on the previous issue: https://github.com/dessant/search-by-image/issues/14#issuecomment-348826094.

As a quick test, you could try searching for this image with other extensions:
https://www.instagram.com/p/BeJmG7SnE8V/?taken-by=nasa

They will most likely not appear in the context menu.
