### ISSUE TITLE
Add this semantic image search engines that use OpenAI CLIP computer vision AI model

### ISSUE THREAD

**Issue by nightkall** [dessant/search-by-image#220]
Add this **semantic image search engines** that use [OpenAI CLIP](https://github.com/openai/CLIP) computer vision AI model:

[LAION-5B](https://laion.ai/blog/laion-5b/) dataset search engines (5 billion images):
- [ https://rom1504.github.io/clip-retrieval/](https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn5.laion.ai&index=laion5B&useMclip=false&imageUrl=https%3A%2F%2Fi.imgur.com%2FNyURMpx.jpeg)
- [https://haveibeentrained.com](https://haveibeentrained.com/?url=https://i.imgur.com/NyURMpx.jpeg)

[Stable Diffusion](https://en.wikipedia.org/wiki/Stable_Diffusion) galleries:

- [https://lexica.art](https://lexica.art/?q=https%3A%2F%2Fi.imgur.com%2FNyURMpx.jpeg)
- [https://pagebrain.ai](https://pagebrain.ai/promptsearch/?q=https%3A%2F%2Fi.imgur.com%2FNyURMpx.jpeg&page=1)
- [https://openart.ai](https://openart.ai/discovery?q=https%3A%2F%2Fi.imgur.com%2FNyURMpx.jpeg)
- [https://enterpix.app](https://enterpix.app)

and this Reverse image search engine [posted here](https://github.com/dessant/search-by-image/issues/207):

- [https://www.immerse.zone](https://www.immerse.zone)

It would be nice to have these image search engines because they are **good for finding similar** images and useful for people that use Stable Diffusion and other text-to-image generative AI models.

**Thanks** for your fantastic browser extension.

**Comment by jvkap** [comment]
I agree. It would be very interesting to add these options.

**Comment by dessant** [comment]
Thanks for the suggestions! Lexica is already implemented in the latest commit, for the rest of the engines please share an SVG icon if there are any available. I often spend the most time with sorting out the icon of the service, so this would be of great help.

**Comment by jvkap** [comment]
> I couldn't find rom1504, but as far as I understood it has the same database as ''haveibeentrained''. See if these will work here:

Haveibeentrained:

![favicon](https://user-images.githubusercontent.com/83289567/197857687-f7509d8c-ec81-4247-b7f0-c15519c5a8c8.svg)

pagebrain
![mdkwIUlJ_400x400](https://user-images.githubusercontent.com/83289567/197858227-4476d26f-0e02-4de7-b8b3-b58f32374383.svg)

Immerse Zone
![favicon_1_](https://user-images.githubusercontent.com/83289567/197858469-11409799-1074-4a24-a076-60a8f1ba301f.svg)

**Comment by nightkall** [comment]
> Thanks for the suggestions! Lexica is already implemented in the latest commit, for the rest of the engines please share an SVG icon if there are any available. I often spend the most time with sorting out the icon of the service, so this would be of great help.

Thanks for adding Lexica, I edited the post and added two more.

**Comment by nightkall** [comment]
> Thanks for the suggestions! Lexica is already implemented in the latest commit, for the rest of the engines please share an SVG icon if there are any available. I often spend the most time with sorting out the icon of the service, so this would be of great help.

Thanks for adding Lexica, I edited the post and added two more.

**Comment by dessant** [comment]
The following search engines seem to be broken:

https://rom1504.github.io/clip-retrieval/
https://pagebrain.ai/promptsearch/
https://openart.ai/discovery

**Comment by dessant** [comment]
These engines still work:

https://haveibeentrained.com
https://enterpix.app
https://www.immerse.zone

For Have I Been Trained there is a higher resolution image found in the source code of a Substack post that I'll trace to get a vector image: https://substack-post-media.s3.amazonaws.com/public/images/0b8a8789-04e6-4a05-a137-19f23c42110c_727x727.png

Enterpix has a proper SVG icon, but Immerse only has that low resolution favicon that looks bad on a HiDPI display: https://www.immerse.zone/favicon.ico

**Comment by neoOpus** [comment]
[**@dessant**](https://github.com/dessant) commented on [Jun 18, 2023, 12:43 PM EDT](https://github.com/dessant/search-by-image/issues/220#issuecomment-1596204237 "2023-06-18T16:43:43Z - Replied by Github Reply Comments"):
> These engines still work:
> 
> [haveibeentrained.com](https://haveibeentrained.com)  
> [enterpix.app](https://enterpix.app)  
> [immerse.zone](https://www.immerse.zone)
> 
> For Have I Been Trained there is a higher resolution image found in the source code of a Substack post that I'll trace to get a vector image: [substack-post-media.s3.amazonaws.com/public/images/0b8a8789-04e6-4a05-a137-19f23c42110c\_727x727.png](https://substack-post-media.s3.amazonaws.com/public/images/0b8a8789-04e6-4a05-a137-19f23c42110c_727x727.png)
> 
> Enterpix has a proper SVG icon, but Immerse only has that low resolution favicon that looks bad on a HiDPI display: [immerse.zone/favicon.ico](https://www.immerse.zone/favicon.ico)

I can take care of making an SVG if that's what you want

**Comment by dessant** [comment]
Thanks @neoOpus for offering your help! Meanwhile I've reached out to Immerse and we'll use a text portion from the SVG logo they have sent, so all search engine icons are covered now.

```
Hi Armin,

Thanks for the clarification. Please go ahead and use “im” as the icon. We would like to go with “Immerse” as the search engine name. Thanks again!

Business Team,
Immerse.zone by LibAI (Formerly PicUP.Ai)
```

**Comment by dessant** [comment]
Clip Retrieval was also added, but they continue to have intermittent server issues.

Please share any new AI-generated image or dataset search engines you discover by linking it here or in a new issue.

**Comment by dessant** [comment]
Mostly all of these search engines are now broken and will be removed from the extension. If you find any alternatives in the future for querying LAION-5B and other image datasets used for training, please share the links here or in a new issue.

https://github.com/rom1504/clip-retrieval/issues/379
https://github.com/dessant/search-by-image/issues/313

**Comment by neoOpus** [comment]
I found this today, maybe you will be interested to add it... otherwise what about making it possible in the setting to set custom search engines and their icons?!

https://lenso.ai/en

**Comment by neoOpus** [comment]
Glad to see that you are sponsored by Lenso.ai :)
