### ISSUE TITLE
No way to actually use it, on FF Android.

### ISSUE THREAD

**Issue by navid-zamani** [dessant/search-by-image#222]
**System**

* OS name: Android (EMUI)
* OS version: 12 (12)
* Browser name: Firefox
* Browser version: 106.1.0
* Extension version: 5.4.0

**Bug description**
There is no way to actually search by image. No UI element for it, no button.  
I assumed holing on an image would offer a context menu item for it. Maybe in the URL bar, a button next to the one for selecting the search engine. Maybe intl the three dots menu. Maybe in its Add-ons sub-menu. Maybe when selecting the Add-on there, in the daliog tab that opens. Nothing.  
And worse, nothing in the info text, or even on the startpage of this repository…
I can only assume that is must be really obvious … but is broken on Android.
In any case, a help somewhere, to read how to use it, would be useful, if it is actually that hard to find…

So I am stuck with no way to actually use the extension for searching.

**Comment by dessant** [comment]
The extension should be listed in the Add-ons submenu after a web page has been loaded. If it isn't, please post a sreenshot about the browser with the submenu opened.

**Comment by dessant** [comment]
It's also possible that you have opened a private tab, but haven't enabled the extension to run in private browsing.
