### ISSUE TITLE
Support earch engine groups

### ISSUE THREAD

**Issue by alexolog** [dessant/search-by-image#228]
I have 1bout 15 search engines enabled, but 95% of the time I can find what I am looking for on a small subset of the engines

I often fire up searches on all of the engines in the subset because they give me different results, but I have to do it manually since currently I can either search on one engine at a time or on all active engines.

I propose adding the option to search on a configurable subset of engines.  If only one group will be supported, you can call it "favourite search engines" or something to that effect.

**Comment by dessant** [comment]
Let's track this issue at https://github.com/dessant/search-by-image/issues/68.
