### ISSUE TITLE
Chinese Simplified (zh-CN) Language Pack for 5.4.2

### ISSUE THREAD

**Issue by castore** [dessant/search-by-image#229]
[Chinese Simplified (zh-CN) Language Pack for 5.4.2.zip](https://github.com/dessant/search-by-image/files/10147845/Chinese.Simplified.zh-CN.Language.Pack.for.5.4.2.zip)
![options](https://user-images.githubusercontent.com/7022156/205473988-3e3f1ca6-569d-452e-87f9-6305701a8ceb.png)

**Comment by dessant** [comment]
The issue is being tracked at https://github.com/dessant/search-by-image/issues/255.
