### ISSUE TITLE
Context menu item to only appear when image is right-clicked

### ISSUE THREAD

**Issue by domportera** [dessant/search-by-image#230]
**Is your feature request related to a problem? Please describe.**

Right-clicking on non-image elements displays the Search By Image context menu entry

**Describe the solution you'd like**

Only show the context menu entry when an image is right-clicked

**Describe alternatives you've considered**

editing userchrome.css, but I've found no success

**Additional context**

A good place to test this feature is at [this old website](https://www.vortex.com/) as it is html-only with no hidden background images

**Comment by dessant** [comment]
https://github.com/dessant/search-by-image/wiki/Why-is-the-extension-always-visible-in-the-context-menu%3F
