### ISSUE TITLE
Google have changed image search results.

### ISSUE THREAD

**Issue by reelism** [dessant/search-by-image#234]
Due to google totally deprecating google images search, this plugin needs to change to keep the old (google) functionality.

Bing Images search was the closest I could find to actually giving results for searching for identical images.

**Comment by dessant** [comment]
Searching on Google Images is expected to work with the extension. Are you using the latest version? If you have an issue with the latest version, please open a bug report and fill out the issue template properly.

Related issue: https://github.com/dessant/search-by-image/issues/221

**Comment by reelism** [comment]
The point is google images search has completely changed to Google-Lens results, I cannot see a way to search for identical-images on google images, as of today. 

As late as last week this worked as expected, today it does not. 

Try it yourself and see.

**Comment by dessant** [comment]
I don't know how to help you based on the details you've shared. Please see my first comment here and follow the instructions.

**Comment by reelism** [comment]
Thx for reply, but this isn't a bug report, i think it should likely be a feature request. 

AGAIN, Google have changed image searches. 
Issue is with Google, not yr plugin. 

**Is your feature request related to a problem? Please describe.**
Google has deprecated traditional Google-Images-Search. It now gives google-lens related results (a search on a van searches for "van", suggests: "car"), not results for identical images.

Bing Images search remains similar to prior GIS results.

**Describe the solution you'd like**
That Search By Image provides traditional Google Image search-identical-image results.

**Describe alternatives you've considered**
So far, Bing is closest, albeit with significantly fewer, less quality results.
