### ISSUE TITLE
Couldn't upload image on any search service

### ISSUE THREAD

**Issue by Sogl** [dessant/search-by-image#237]
**System**

* OS name: OS X Monterey 
* OS version: 12.6.1
* Browser name: Chrome
* Browser version: 108.0.5359
* Extension version: 5.4.2

**Bug description**

I don't know what happened, but now the search in any service doesn't work.

Yandex:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/7556290/213492767-c2566670-5b7a-41b5-92ee-f245b1d9f8a9.png">

Google:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/7556290/213492953-1a6565f0-a73f-4d0e-b924-5000581acd7e.png">

TinEye:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/7556290/213493335-0f62dbda-23d5-413f-8c47-67804d141b72.png">

etc

**Comment by dessant** [comment]
From the looks of it the image host either prevents hotlinking, or the image format is not supported by these search engines. You could switch to the "Select image" search mode to download the image and convert it before uploading it to search engines.

**Comment by dessant** [comment]
Next time also please don't post negative ratings on the Chrome Web Store and open issues here simultaneously, but first ask for help before you decide to harm a project.

**Comment by Sogl** [comment]
>From the looks of it the image host either prevents hotlinking, or the image format is not supported by these search engines. You could switch to the "Select image" search mode to download the image and convert it before uploading it to search engines.

Thx, it works now. I think it's because the site from which I was looking for images is localhost/dev.

>Next time also please don't post negative ratings on the Chrome Web Store and open issues here simultaneously, but first ask for help before you decide to harm a project.

Not a problem. Review deleted.

I saw that the project has a Github after writing a review.
