### ISSUE TITLE
REQ: enable / disable engines from the fly...

### ISSUE THREAD

**Issue by EC-O-DE** [dessant/search-by-image#24]
from toolbar pop up menu :)

?

**Comment by dessant** [comment]
You've suggested this before, but I don't consider the feature to be that useful for the general user. Frequently enabling and disabling engines is a feature which would be rarely used, yet still clutter the user interface and be a maintenance burden.

**Comment by EC-O-DE** [comment]
I work with many tools, such as this https://github.com/apsun/GoogleImageShell
And then when on Google results I might want to search to same image eg. Yandex - so then I want to temporarily turn Google off.

Other occasion is if i ran into an image eg. on Yandex - that I want to search on Google - also then turning Yandex temporarily off would be very useful.

**Comment by dessant** [comment]
You don't have to turn an engine off the search with the other, just select the engine you want to search with from the context menu or the toolbar popup. Aren't the engines listed separately on your part like on the picture below?

![68747470733a2f2f692e696d6775722e636f6d2f6e6948676e647a2e706e67](https://user-images.githubusercontent.com/7513068/36064784-261a662c-0e99-11e8-95e7-441802cdd4e7.png)
