### ISSUE TITLE
Add option to set enabled engines to "auto" while others can be used manually [re: Pimeyes]

### ISSUE THREAD

**Issue by seanbperiod** [dessant/search-by-image#242]
I love how I can set this to just pull images for me automatically, but not all of us have a paying membership to PimEyes - so I'd like the option to keep the engine enabled so I can use it manually via the dropdown/context menu, but not have it be used for every autorun so I don't use up my free 3/daily runs I get with PimEyes. 

Right now, if I want to delesect PimEyes, I have to open options, deselect it. Close options. Run my task. And if I want to use it, I have to do the same thing over again. 

It would be nice if either through the options or as an enabled check/selection via toolbar/context menu, I can select [for example] PimEyes, to not be autorun, but still be a selectable option to use on it's own. 

Thanks!

**Comment by dessant** [comment]
This use case will be solved by search engine groups, the issue is tracked at https://github.com/dessant/search-by-image/issues/68.
