### ISSUE TITLE
add yandex.com (not .ru) image search

### ISSUE THREAD

**Issue by famicom9x** [dessant/search-by-image#243]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
add yandex.com (not .ru) image search
yandex.ru block my country ip , but .com dont please add yandex .com image search not .ru

**Describe alternatives you've considered**

**Additional context**

**Comment by dessant** [comment]
The extension uses yandex.com, but Yandex probably redirects the page. From which country are you using the extension?

**Comment by dessant** [comment]
It's strange that yandex.com would still redirect to yandex.ru on your end, because the latter domain was recently sold to VK. I guess by .ru you must be referring to ya.ru instead, which is their new portal.

https://en.wikipedia.org/wiki/Yandex#History

**Comment by dessant** [comment]
It's not clear what's happening on your device. For general search engine customization you can subscribe to this issue: https://github.com/dessant/search-by-image/issues/68
