### ISSUE TITLE
Shift + Click on Context Menu Item to open Tab(s) in New Window

### ISSUE THREAD

**Issue by Cr8zyIvan** [dessant/search-by-image#244]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

Shift + Click on Context Menu Item to open Tab(s) in New Window

**Describe alternatives you've considered**

**Additional context**

In the Firefox Bookmark Sidebar, it is possible to Shift + Click on Context Menu Items to open Bookmarks in New Windows, using Shift + Click. Single Bookmarks can be opened or all Bookmarks in a Folder can be opened in a New Firefox Window, using this method.

**Comment by dessant** [comment]
The issue is tracked at https://github.com/dessant/search-by-image/issues/253.
