### ISSUE TITLE
[Feature request] Support keyboard shortcuts for triggering search

### ISSUE THREAD

**Issue by tomeryp** [dessant/search-by-image#246]
It could be useful to support keyboard shortcuts to initiate a search.
As of now, all of the methods to initiate a search for an image have too much steps and mouse gestures,
For example: pressing the action button, choosing an engine, selecting the image, and pressing the search button. or using context menu: right click on an image, hovering on the "search by image" group, and choosing an engine. 

Supporting keyboard interaction with the extension will help productivity, especially for searching multiple images on the same page.

I have created a pull request with a working solution leveraging the extension keyboard commands interface.
This solution adds (configurable) keyboard shortcuts to trigger the image selection / url selection / capture mode (with the top engine in the enabled engines list). The only step left is to select an image.

This [PR](https://github.com/dessant/search-by-image/pull/245) supports chrome, and sets the Ctrl+Shift+[X/Y/Z] shortcuts to initiate image selection, url selection, capture mode.

**Comment by dessant** [comment]
Let's track this issue at https://github.com/dessant/search-by-image/issues/83.
