### ISSUE TITLE
Google Image Search Doesn't Work

### ISSUE THREAD

**Issue by nu111** [dessant/search-by-image#249]
**System**

* OS name: Ubuntu
* OS version: 22.04
* Browser name: Firefox
* Browser version: 112.0
* Extension version: 4.6.0

**Bug description**

1. Have a image to test on
2. Right click the image
3. Click on Search by Image > Google
4. Google Images "homepage" opens up, but no search is fired with the selected image

A video of the issue:
https://github.com/dessant/search-by-image/assets/1246989/7fd962f2-bd75-48b4-b31c-e750e1c6dfcd

Similar issue on Firefox Android:

**System**
* OS name: Android
* OS version: 13
* Browser name: Firefox
* Browser version: 113.2.0
* Extension version: 4.6.0

**Bug description**
1. Have a image to test on
2. Right click the image
3. Click on Search by Image > Google
4. Google Images opens up with a something that looks like a search using a broken image

A video of the issue:
https://github.com/dessant/search-by-image/assets/1246989/6892a60f-21b9-4b82-8359-9ef7867024de

**Comment by dessant** [comment]
Version 4.6.0 is outdated and broken, could you test with the latest version of the extension (5.4.2)?

**Comment by nu111** [comment]
Ok, just curious: isn't it expected that the addon will automatically update itself?

**Comment by dessant** [comment]
Yes, Firefox automatically updates extensions. The version you currently have was followed by an update that has requested a new permission (version 4.7.0), you've probably denied the permission request at the time so Firefox kept the old version installed.

The easiest would be to install it from AMO again, your settings should be preserved: https://addons.mozilla.org/en-US/firefox/addon/search_by_image/

**Comment by nu111** [comment]
I confirm that with version 5.4.2 Google Image Search works fine.

> The version you currently have was followed by an update that has requested a new permission (version 4.7.0), you've probably denied the permission request at the time so Firefox kept the old version installed.

Yes, could be!

For others reading:

on Firefox Desktop I had to manually check for updates
![Screenshot_20230528_180250](https://github.com/dessant/search-by-image/assets/1246989/888dc081-9931-4190-b196-848e07247696)

on Firefox Android I had to delete and reinstall the addon

Thanks for you help and for your time @dessant !
