### ISSUE TITLE
Version page still has previous version at the top

### ISSUE THREAD

**Issue by nollinvoyd** [dessant/search-by-image#251]
Just thought you should know that on the version page the previous version is at the top, and you must scroll down to realize the latest version is there below it.

**Comment by dessant** [comment]
Are you referring to the releases page on GitHub? I'm seeing version 5.6.0 at the top of the page.

https://github.com/dessant/search-by-image/releases

**Comment by nollinvoyd** [comment]
No, it's the Firefox latest version page [https://addons.mozilla.org/en-US/firefox/addon/search-site-we/versions/](url)
