### ISSUE TITLE
"open image" button disappears when you disable context menu 

### ISSUE THREAD

**Issue by seriousgigi** [dessant/search-by-image#256]
like i said i use this extension for opening "unopenable" images but every time clicking sub context menu is annoying so i decided to disable "sub context menu" from settings but it removed "open image" from context menu while search engines exist on context menu.

please look at this problem.

**Comment by dessant** [comment]
Please attach a screenshot of the Options page.

**Comment by seriousgigi** [comment]
changed from "submenu of context menu" to context menu. 

![Screenshot (372) (2jpg)](https://github.com/dessant/search-by-image/assets/83796753/425cf26c-ee41-470b-90a9-e9b5f2235ac8)

this worked for search engine as it is seen on context menu instead submenu.

![Screenshot (373) (2jpg)](https://github.com/dessant/search-by-image/assets/83796753/fb270fb2-32f9-4e06-b6f5-b8be67d5b2b4)

but this option removes "open image" feature from context menu. open image should also exist on context menu.

![Screenshot (371) (2jpg)](https://github.com/dessant/search-by-image/assets/83796753/7571c768-8dc1-4be9-9ef5-a6987f3d9956)

see? open image button doesnt exist anymore.

![Screenshot (374) (2jpg)](https://github.com/dessant/search-by-image/assets/83796753/7d868637-23d9-4a4b-9818-294a5fa491b8)

**Comment by dessant** [comment]
That's how the extension works, you can opt to initiate a search from the context menu, without needing to access a submenu, but in that case all the secondary features, such as opening or sharing an image, cannot be accessed.

The solution would be to allow setting a default action for the context menu and toolbar button, you can subscribe to this issue for updates: https://github.com/dessant/search-by-image/issues/257
