### ISSUE TITLE
Save Instagram video/image addon

### ISSUE THREAD

**Issue by RodrigoDiazDVivar** [dessant/search-by-image#261]
Hi, I see you have worked out a way of precisely always showing your context menu correctly on instagram stories (what all current firefox  addons fail at doing), and getting images from them reliably. I think that if you copied the code of other save ig addons, you could create a context menu save video/image on instagram (or even also twitter, youtube etc) that works reliably.
Literally NONE of the curent firefox addons work for stories because they rely on the name instagram gives to their buttons or wahterver (and they change that periodically).
However, (only) this is one works relaibly on chorme https://chrome.google.com/webstore/detail/fastsave-and-repost/pnlphjjfielecalmmjjdhjjninkbjdod, but I guess he needs to do more manteinance (and bseides i don't like the buttons showing up).
I wonddered if you could adapt it for firefox witha  context menu perchaps :)
Also if you dont like the languange, you could see this one that also works well (but not in stories) on firefox https://addons.mozilla.org/es/firefox/addon/yt-ig-tw-downloader/

**Comment by dessant** [comment]
Hi, I don't plan to work on a similar extension. There's a possibility that Search by Image will be able to extract an open videos in a new tab, not just images, but that feature won't be implemented anytime soon. I think you should fork one of these projects and adapt them to your needs.
