### ISSUE TITLE
Don't appear Extension Icon on toolbar

### ISSUE THREAD

**Issue by array** [dessant/search-by-image#27]
Add on installing exactly, but not appeared Search by image icon on the toolbar.
Browser: Firefox 60 beta01(Developer Editon)
Windows10 64bit Fall Creator update

![2018-03-08_li](https://user-images.githubusercontent.com/179274/37122939-c3baf214-22a5-11e8-9cbc-bfb7cce305e4.jpg)

**Comment by dessant** [comment]
You have a lot of toolbar buttons there, are you sure it's not in the overflow menu?

**Comment by dessant** [comment]
Please do not use extension reviews to report bugs in the future, and especially don't give negative ratings because of breaking changes in Firefox.

If this bug persists, it's best to report it directly to Mozilla.
https://bugzilla.mozilla.org
