### ISSUE TITLE
Indefinite loading when searching image on Google

### ISSUE THREAD

**Issue by CommicKick69ing** [dessant/search-by-image#270]
**System**

* OS name: Windows 10
* OS version: 19045.3324
* Browser name: Chrome
* Browser version: 116.0.5845.111
* Extension version: 5.7.0

**Bug description**
When ever I search for an image through goggle the page & extension indefinitely load until eventually the tab crashes

**Comment by dessant** [comment]
It must have been an issue with Google servers, the search results did not load for a couple of minutes, but right now it seems to be working again.
