### ISSUE TITLE
"Reddit Repost Sleuth" engine broken since July

### ISSUE THREAD

**Issue by Noob729** [dessant/search-by-image#272]
**System**

Firefox 117 on Linux
Search by Image 5.7.0

**Bug description**

When searching any image using the "Reddit Repost Sleuth" engine,
the "Image URL" textbox remains empty, and search never starts.
After a minute, a pop-up states "Something went wrong".

https://www.repostsleuth.com/search?targetImageMatch=60&filterSameAuthor=false

Other extensions:
uBlock Origin

Will test on a fresh profile with only *Search by Image* installed.

**Logs**

```
Error: DOM node not found: input[placeholder="https://redd.it/xyz"]  script.js:2:112767
```

**Comment by Noob729** [comment]
The `Image URL / Reddit Post URL` textbox is now deep within nested div anchors:
```
<div class="v-text-field__slot">
<label for="input-54" class="v-label theme--dark" style="left: 0px; right: auto; position: absolute;">
Image URL / Reddit Post URL
</label>
<input id="input-54" type="text">
</div>
```
https://github.com/dessant/search-by-image/blob/main/src/engines/repostSleuth.js

I suppose it's just a matter of changing this line:
```
const input = await findNode('input[placeholder="https://redd.it/xyz"]');
```

**Comment by dessant** [comment]
The fix will be released today, though searching with an image file seems to be broken on their site, so make sure to always search with an image URL.

**Comment by Noob729** [comment]
Thanks for the quick turn-around :+1:
