### ISSUE TITLE
Google image Search results aren't the same anymore, but gives Google Lens results, Google Lens needs to be disabled from regular image search

### ISSUE THREAD

**Issue by GreenDotBlue99** [dessant/search-by-image#276]
Google image Search results aren't the same anymore, but gives Google Lens results, Google Lens needs to be disabled (by code) from regular image search

* OS name: windows, android
* OS version: 10, 11
* Browser name: vivaldi, firefox for android 
* Browser version: latest stable
* Extension version: latest

**Comment by dessant** [comment]
On my part Google Images returns legacy search results, Google Lens works independently from that. Please share a video of this redirection, are you sure you're using this extension?
