### ISSUE TITLE
Google Image search doesn't seem to be working

### ISSUE THREAD

**Issue by evilhackman** [dessant/search-by-image#278]
**System**

* OS name: Windows 11
* OS version: 22H2 22621.2428
* Browser name: Firefox
* Browser version: 119.0
* Extension version: 4.6.0

**Bug description**
<!--
Whenever I try to search for an image on Google by right-click-> search by image -> Google
Google image search just opens on the empty start page https://www.google.com/imghp?sbi=1 instead of showing any results. This has been going on for months. Seems like the image/ image URL doesn't get submitted to google.
Wonder why no one else reported it? 
Other search engines like Yandex work fine.
I have also Ublock Origin, greasemonkey, Savefrom.net Helper, Video Download Helper, Honey,  installed. Could any of those block the function?
![Screenshot 2023-11-05 173952](https://github.com/dessant/search-by-image/assets/15716642/91ef99d5-d2f0-4f1f-8a32-cdde10a67991)
I tried also to deactivate"use Google local page" but then I am only taken to a google error page stating that image search is too busy at the moment

**Comment by dessant** [comment]
> Extension version: 4.6.0

You should update to the latest version.

**Comment by evilhackman** [comment]
> > Extension version: 4.6.0
> 
> You should update to the latest version.

Thanks. I don't know why it wasn't automatically updating. A simple solution.
Ticket closed!

**Comment by dessant** [comment]
There was a new permission request in version 4.7.0 which you may have not accepted, so the browser could no longer update the extension.
