### ISSUE TITLE
Search by Image - last 5 days doesn't work

### ISSUE THREAD

**Issue by iordanis2000** [dessant/search-by-image#279]
**System**

* OS name: [e.g. Windows, Ubuntu]
* OS version: [e.g. 10]
* Browser name: [e.g. Chrome, Firefox]
* Browser version: [e.g. 60]
* Extension version: [e.g. 1.0.0]

**Bug description**

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by iordanis2000** [comment]
i make the usual action , right click, search all engines and nothing happens, i use this app 1 year now and its first time it does this

**Comment by dessant** [comment]
Ok, could yout fill out the details that were requested in the issue template? Also share a link to a web page where searching does not work.

    OS name: [e.g. Windows, Ubuntu]
    OS version: [e.g. 10]
    Browser name: [e.g. Chrome, Firefox]
    Browser version: [e.g. 60]
    Extension version: [e.g. 1.0.0]

**Comment by iordanis2000** [comment]
OS name: Windows
OS version: 10
Browser name: Firefox
Browser version: 119.0.1 (64-bit)
Extension version: 6.1.0

**Comment by iordanis2000** [comment]
moz-extension://f14766c1-4ef0-48d5-a70a-fc6f1e39ecc1/src/view/index.html?id=a51658b8-13b5-440d-a4e1-94c6515eb15d

**Comment by dessant** [comment]
You've shared an internal link for the image viewer from the extension, not a web page link. Based on what you shared I can't yet reproduce the issue, the extension works for me. Maybe you could record a video of your screen as you are searching so I can get a better idea of what you're doing.

It's also possible that the extension is showing you an error as a notification in Windows, you could check if there are any notifications in the Notification Center, there's a button near the clock in the taskbar to open it.
