### ISSUE TITLE
Cannot search anymore from my device pictures.

### ISSUE THREAD

**Issue by Anubiss23** [dessant/search-by-image#280]
* OS name: Windows
* OS version: 10 build 19045
* Browser name: Firefox
* Browser version: 119.0.1
* Extension version: 6.1.0

the extension always worked for every pics i had in my device, since a few days I'm not able to use it in that way uploading the pics on Firefox and then search with the extension, the pop up that show from mozilla is "content scripts are not allowed on this page" what can be the problem?

**Comment by dessant** [comment]
Please describe how are you searching with a picture from your device, the exact steps you take, and at which point does the error occur. You could also create a video and share it here.
