### ISSUE TITLE
Cannot search images from device

### ISSUE THREAD

**Issue by newone439** [dessant/search-by-image#281]
**System**

* OS name: Windows
* OS version: 22H2
* Browser name: Chrome and Firefox
* Browser version: 119.0.1
* Extension version: 6.1.0

**Bug description**

When dropping a photo from my computer into a new tab within firefox, I right click on the picture and choose Search by image, then Google, then nothing happens. Same thing if I choose All Search engines

**Comment by dessant** [comment]
Please visit this page in Chrome: chrome://extensions/?id=cnojnbdhbhnkbcieeekonklommdnndci

Once you are on that page, create a screenshot and attach it to this issue, make sure that the following rows are visible on the image:

![screenshot1](https://github.com/dessant/search-by-image/assets/7513068/c90e96c5-8d63-4db6-9add-e4722938a21f)

**Comment by newone439** [comment]
![Uploading 1.jpg…]()

**Comment by dessant** [comment]
Attach the image again and wait for it to load before posting the comment, otherwise it will not be sent.

**Comment by newone439** [comment]
![1](https://github.com/dessant/search-by-image/assets/150562647/c16fb4b3-f461-46b5-a4af-cccec0111cfe)

**Comment by dessant** [comment]
Turn on the "Allow access to file URLs" option on that page and restart the browser, then the extension should work. On Firefox you must have also restricted the extension's access to `file://` URLs, maybe by turning on some anti-fingerprinting feature in about:config, that's why it does not work.

**Comment by dessant** [comment]
Were these issues also opened by you?

https://github.com/dessant/search-by-image/issues/280
https://github.com/dessant/search-by-image/issues/279

**Comment by newone439** [comment]
No, that is a different user.

**Comment by newone439** [comment]
Great, that worked for Chrome. I will see what I can come up with on firefox. Thanks for your help.

**Comment by dessant** [comment]
No problem, I'm glad it was sorted out. :yum:
