### ISSUE TITLE
[Engine request] Yahoo Auctions

### ISSUE THREAD

**Issue by Hawking312** [dessant/search-by-image#282]
Hi, thank for your great work. 
Because my english verry so I cant write long. Im sorry for that.
Please add https://auctions.yahoo.co.jp/# to search engine, thank you so much

**Comment by neoOpus** [comment]
> Hi, thank for your great work. Because my english verry so I cant write long. Im sorry for that. Please add https://auctions.yahoo.co.jp/# to search engine, thank you so much

Please use AI services for translation and proofreading. There are plenty of solutions like this one [Sider](https://sider.ai/invited?c=53d0f07e358ecdd42ddbc2289d2c2642), so you no longer need to apologize or restrict yourself.

**Comment by dessant** [comment]
Yahoo Japan blocks visitors from the EU, so Yahoo Auctions cannot be accessed either. Search engines with such behaviors will rarely be considered for inclusion.

This is what EU and UK visitors see when they open the link above:

```
From Wednesday, April 6, 2022, Yahoo! JAPAN is no longer available in the EEA and the United Kingdom

Please be informed that from Wednesday, April 6, 2022, Yahoo! JAPAN’s services are no longer available to our users in the EEA (European Economic Area) and the United Kingdom, as it has been determined by Yahoo! JAPAN that providing a continuous service environment in these regions would be difficult. Please note that services listed under “Services available after Wednesday, April 6, 2022” below will continue to be available.

Please note that all Yahoo! JAPAN services are accessible after this date if access is made from Japan.

We sincerely apologize for any inconvenience this may cause and thank you for your understanding.

*For more information on the member states of the EEA, please click [here](https://www.mofa.go.jp/mofaj/area/osce/s_kikou.html).

Services available after Wednesday, April 6, 2022 in your region
Yahoo! JAPAN Mail
PayPay Card (former Yahoo! JAPAN Credit Card)
ebookjapan

*Some[ Yahoo! JAPAN Mail ](https://mail.yahoo.co.jp/)functions will be restricted. Please click here for details. (Japanese only)
```
