### ISSUE TITLE
[Engine Request] Add Search on Saucenao[dot]com 

### ISSUE THREAD

**Issue by SirLimonada** [dessant/search-by-image#287]
Saucenao[dot]com is a website that allows you to do find the source of pictures in twitter, deviantart and other internet websites incredibly quickly, it would be great if it was listed as an option.

**Comment by dessant** [comment]
It's already supported, you can enable the search engine from the extension's options.

**Comment by SirLimonada** [comment]
My bad, didn't know there was a whole lot of different search engines hidden there, thanks a lot!
