### ISSUE TITLE
google search error

### ISSUE THREAD

**Issue by aqtsalt** [dessant/search-by-image#289]
**System**

* OS name: Windows
* OS version: 10
* Browser name:Firefox]
* Browser version: [e.g. 60]122
* Extension version: [e.g. 1.0.0]612

**Bug description**
error with google search

**Logs**Error: API response: 429, <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://www.google.com/search?tbs=sbi:AMhZZisKkx6VxCz4zpHl57wrw4j7N07pDliG6FfrZDBuAkZbVtI0sRwUYgDOHyBLGZwIGVmswFs1qIyIvF3d9DyavnvDHKobc3p2UuN5ZtuAV8TNfUZ8oU_1Wuavpjph_1JmNB1mSqFLuWCQF8crBf5Hc1wH5irUzXyNZ3pK3NSRi9SZR3vpWqSh7cKFBnibw-x4XxXNvS5c7MUyMpgVptdSc9Vs6bLPbu2_1Qqj4qOkWd9AcjC7DwlInhrq6dCQ50g31xRb4MUmRZdYu92uHM32i0fFxfEkIl271WLtVzEt-nJAW-ugIfTSCRiEkBwXe8_1gppm34uwh5kX8pzMOPb_1tMFj7JgjQLmisyjg1Fq4O-Md7wR2z3JJr5ou0zPhay7I5CiNPJV-AV188mtG_1OBrg0y0OxizFje_1DA</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px; overscroll-behavior:contain;" onload="e=document.getElementById('captcha');if(e){e.focus();} if(solveSimpleChallenge) {solveSimpleChallenge(,);}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form id="captcha-form" action="index" method="post">
<noscript>
<div style="font-size:13px;">
  In order to continue, please enable javascript on your web browser.
</div>
</noscript>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>var submitCallback = function(response) {document.getElementById('captcha-form').submit();};</script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b" data-callback="submitCallback" data-s="CuNLkxw4hqOTfEwR2z97P8Dfky7DN1YXO7KaG4Y9yOU2qrvWMElZHTSALw-lBCvDvtOJbfLorcHQQQ-DXllSitYeKSg6PCfImKuwUPmY3Xcix8wmzuYfybabIxb0IbSLWntsAZpKnTelGPERIODQYcV9YvE9gi8iM5doJxyeNQ97jKl0LpqisK7o4lLshw5fHH7G32-ngMPZMDI3gjX96wfg2bFRSUB9TT0ZS0j1HZSbXV9yKyMrR4MCn9rQcC-yKUBjruD7ZwN8Wb_nYjLN_tKZfcpxTbw"></div>

<input type='hidden' name='q' value='EgS4S90DGKfD1a0GIjAqMtF03hgD6Y7sLhgY1hYBIBZwd7KF_barxEiWRi2c3GGwIYrcZVujUEr3SjRnfmUyAXJKGVNPUlJZX0FCVVNJVkVfTkVUX01FU1NBR0VaAUM'><input type="hidden" name="continue" value="https://www.google.com/search?tbs=sbi:AMhZZisKkx6VxCz4zpHl57wrw4j7N07pDliG6FfrZDBuAkZbVtI0sRwUYgDOHyBLGZwIGVmswFs1qIyIvF3d9DyavnvDHKobc3p2UuN5ZtuAV8TNfUZ8oU_1Wuavpjph_1JmNB1mSqFLuWCQF8crBf5Hc1wH5irUzXyNZ3pK3NSRi9SZR3vpWqSh7cKFBnibw-x4XxXNvS5c7MUyMpgVptdSc9Vs6bLPbu2_1Qqj4qOkWd9AcjC7DwlInhrq6dCQ50g31xRb4MUmRZdYu92uHM32i0fFxfEkIl271WLtVzEt-nJAW-ugIfTSCRiEkBwXe8_1gppm34uwh5kX8pzMOPb_1tMFj7JgjQLmisyjg1Fq4O-Md7wR2z3JJr5ou0zPhay7I5CiNPJV-AV188mtG_1OBrg0y0OxizFje_1DA">
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">

<div style="font-size:13px;">
<b>About this page</b><br><br>
This network is blocked due to unaddressed abuse complaints about malicious behavior. This page checks to see if it's really a human sending the requests and not a robot coming from this network. <br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.  In the meantime, solving the above CAPTCHA will let you continue to use our services.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may be asked to solve the CAPTCHA if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div>

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
You could try logging out from your Google account, or change some account settings, please see this issue for details: https://github.com/dessant/search-by-image/issues/290

Though keep in mind that Google has deprecated the legacy image search service, and it may stop working at any time. The extension supports more than 40 reverse image search engines, and the best option would be to start exploring them and transition away from Google's deprecated service.
