### ISSUE TITLE
No results anymore from Google

### ISSUE THREAD

**Issue by colemar** [dessant/search-by-image#290]
**System**

* Windows
* 10
* Chrome
* Browser version: 121.0.6167.85
* Extension version: 6.1.2

**Bug description**

Google reverse image search comes out always empty.
It worked until about yesterday.

**Logs**

```
Where do I get the logs?
```

**Comment by dessant** [comment]
I can't reproduce the issue. Are you testing the extension from Italy? What does empty mean? Please show a screenshot of the search results tab.

**Comment by colemar** [comment]
Yes, from Italy.

Google obviously should at least know these images:
![image](https://github.com/dessant/search-by-image/assets/3066000/f2dbebfb-8f6b-4f8f-8b91-1ea18f0f13e1)

But if I open the first picture and make a reverse search using search-by-image I get this:
![image](https://github.com/dessant/search-by-image/assets/3066000/7d80b5b5-434b-498c-84af-ba8f0d0e22f1)

**Comment by colemar** [comment]
I tested more thoroughly, both in Chrome and Firefox:

- if I am logged in Google with my google account I get no results
- if I disconnect the google account and retry the reverse search I get many results
- if I log in again and retry the reverse search I get no results

This happens both from Italy and from USA (via VPN).

**Comment by colemar** [comment]
How could I complain to Google since this kind of reverse image search is unofficial? (I believe)

**Comment by dessant** [comment]
There is no point in contacting Google because they have already deprecated this service, it was replaced by Google Lens. Google keeps this service accessible for now if you request the URL directly, but the issues you're experiencing are inevitable, and the entire service may be shut down in the near future.

**Comment by MarkyMarkDE** [comment]
I found the problem for image search with g*.
If you are not logged in your account on the same browser it works well (if not, clear cache and cookies for g*).
If you logged in your account in the same browser it don't work.

Check out the follow account privacy settings in your g* account:

![Linked_google_services_01 (1)](https://github.com/dessant/search-by-image/assets/12845477/12707ffd-0faf-43b5-b27b-7173d6a8769c)

Enable the following settings

![Linked_google_services_02](https://github.com/dessant/search-by-image/assets/12845477/7149380c-11a4-4026-b634-ebb79340d979)

then it should work again.
Seems that g* now requires to enable this or image search and maybe other things don't work anymore.

**Comment by colemar** [comment]
@MarkyMarkDE Thank you very much, now it works!
What I don't understand is that the other accounts (they never stopped working) completely miss the Linked Google Services box. It is just not there in the account Data & Privacy settings page.
Perhaps this is related to the fact that only my main account has subscribed Google One.

**Comment by MarkyMarkDE** [comment]
> @MarkyMarkDE Thank you very much, now it works! What I don't understand is that the other accounts (they never stopped working) completely miss the Linked Google Services box. It is just not there in the account Data & Privacy settings page. Perhaps this is related to the fact that only my main account has subscribed Google One.

Please do not try to understand g*, you will always lose :wink:

**Comment by dessant** [comment]
Thanks for sharing a workaround, let's keep this issue open for some time for better visibility.

**Comment by wa-Nadoo** [comment]
It seems, the list of enabled by default search engines should be revised. From my experience, the most useful engines (in Europe) are Google Lens, Yandex, Bing. The Google Images should be disabled by default as legacy. The same for TinEye, I don't see any useful results in it for a very long time.

**Comment by Vorffeed** [comment]
Thank you very much for the solution

**Comment by colemar** [comment]
> It seems, the list of enabled by default search engines should be revised. From my experience, the most useful engines (in Europe) are Google Lens, Yandex, Bing. The Google Images should be disabled by default as legacy. The same for TinEye, I don't see any useful results in it for a very long time.

Google Lens is slanted towards small items and does a poor job of finding images similar to the whole input picture. Google Images was better but it seems to have declined. Yandex at some time surpassed it and is now by far the most useful for general reverse image search.

**Comment by rudolphos** [comment]
Google Lens has never worked for me, it never finds anything relevant so did the 'legacy' google reverse image search for the past 2 years, while yandex and bing usually finds it. Also yandex can show reverse-searched images from archive.org which google doesn't even index.

**Comment by G-D-B-9-9** [comment]
For me it was nagging about 3rd part cookies not being enabled



> **System**
> 
> * Windows
> * 10
> * Chrome
> * Browser version: 121.0.6167.85
> * Extension version: 6.1.2
> 
> **Bug description**
> 
> Google reverse image search comes out always empty. It worked until about yesterday.
> 
> **Logs**
> 
> ```
> Where do I get the logs?
> ```

For me it was nagging about 3rd party cookies not being enabled

**Comment by csengh** [comment]
please someone helps me for Google image search for **Firefox** as MarkyMarkDE's solution for Crome.

unfortunately all image search comes out always empty

**Comment by MarkyMarkDE** [comment]
> please someone helps me for Google image search for **Firefox** as MarkyMarkDE's solution for Crome.
> 
> unfortunately all image search comes out always empty

no, my solution works in all browsers, this is a google account privacy setting

**Comment by Dentoo** [comment]
> > please someone helps me for Google image search for **Firefox** as MarkyMarkDE's solution for Crome.
> > unfortunately all image search comes out always empty
> 
> No, my solution works in all browsers, this is a Google account privacy setting thing.
> 
> EDIT: tested now again and all is working well. Make sure that you have **ALL** privacy settings in your Google Account be enabled!

what? how?

**Comment by csengh** [comment]
> No, my solution works in all browsers, this is a Google account privacy setting thing.
> 
> EDIT: tested now again and all is working well. Make sure that you have **ALL** privacy settings in your Google Account be enabled!

Firefox don't have Linked Services in Privacy and Security, where can I find this option for Firefox?

**Comment by Dentoo** [comment]
Where in the google account?

**Comment by Dentoo** [comment]
I can confirm that after checking all boxes it works again

Thanks @MarkyMarkDE for the screenshots!

**Comment by berendengelbrecht** [comment]
It still always fails in Firefox, tested today with latest version of the plugin. If I search for same image in Google Chrome it works fine. For now I'm using Google Lens in Firefox, but I would prefer to use the **Search by image** plugin :(

**Comment by burnuser** [comment]
Google Images does not work for me as Search Engine with "Search by Image", neither in Firefox, nor in Chrome (no login in Google at all).

Suggestion to resolve this problem for all users (old and new) and get rid of "Does not work!" reviews:
1.) Make "Google Lens" default (+ placed at first position in Search engines list)
2.) In Context menu connect "Google" entry by default to "Google Lens" instead of "Google Images" - also in existing installations!
3.) Deactivate (or remove) "Google Images" by default

**Comment by MarkyMarkDE** [comment]
> Google Images does not work for me as Search Engine with "Search by Image", neither in Firefox, nor in Chrome (no login in Google at all).
> 
> Suggestion to resolve this problem for all users (old and new) and get rid of "Does not work!" reviews: 1.) Make "Google Lens" default (+ placed at first position in Search engines list) 2.) In Context menu connect "Google" entry by default to "Google Lens" instead of "Google Images" - also in existing installations! 3.) Deactivate (or remove) "Google Images" by default

Lens is not possible, we don't get a URL to submit the picture to Google Server!

**Comment by MarkyMarkDE** [comment]
Hope the DEV do NOT remove the current Google Image search by default, for me and other users it always worked!
**It is only required to enable all Privacy Option in the Google Account, that's all.**

**Comment by burnuser** [comment]
1. "Lens is not possible": Lens is already an existing (and working) option in the Search engines list. The only problem is, it is not the default "Google" Search engine.
2. "Lens is not an equivalent replacement": If the old (and maybe better) Search engine is depreciated, it does not matter. The default must be future proof. And Google Lens is already the used image search engine by Google (Desktop) Browser search itself. (See image search results URL: https://lens.google.com/search?...)
3. "There are only some user adjustments necessary": The extension must work out of the box for all users. Or "It does not work" complaints and increasing bad ratings are unavoidable. 
Of course, complete removing of the old Search engine is not necessary. But it should be deactivated by default, for at least new/simple users.

**Comment by dessant** [comment]
We could inject a notice in the page to inform users about the deprecation when there are no search results, and replace Google Images with Google Lens for new installations, while keeping Google Images there in a disabled state. I think that should cover the issue while the deprecated search engine still works for some people.

**Comment by MarkyMarkDE** [comment]
> 1. "Lens is not possible": Lens is already an existing (and working) option in the Search engines list. The only problem is, it is not the default "Google" Search engine.

oha, I have investigated little and played around (not much extensive) and have not found a proper way to submit the image via Lens.
That we have Lens as working Option included, I have overseen :see_no_evil:
Big Sorry!

**Comment by Syntax7error** [comment]
@MarkyMarkDE 's [workaround](https://github.com/dessant/search-by-image/issues/290#issuecomment-1933298771) works for Firefox (there is no need to tick the 'Google' box).

**Comment by TommyHolmberg** [comment]
I managed to make the urls work, but not the image capture. I'm not able to decipher the upload protocol.

It says that the project doesn't accept pull requests, but you are welcome to review my solution here @dessant 
https://github.com/dessant/search-by-image/compare/main...TommyHolmberg:search-by-image:fix-google-search-by-url

**Comment by dessant** [comment]
Hi @TommyHolmberg, we already support Google Lens, it can be enabled from the extension's options.

**Comment by colemar** [comment]
I use Search by Image v. 6.1.2 on Chrome v. 123.0.6312.59
I experience no issues anymore with Google Images after doing this:
https://github.com/dessant/search-by-image/issues/290#issuecomment-1933298771

**Comment by MarkyMarkDE** [comment]
> I use Search by Image v. 6.1.2 on Chrome v. 123.0.6312.59 I experience no issues anymore with Google Images after doing this: [#290 (comment)](https://github.com/dessant/search-by-image/issues/290#issuecomment-1933298771)

sure, the Privacy Stuff _MUST_ be enabled, otherwise nothing worked.

**Comment by AlmostHuman34** [comment]
> I found the problem for image search with g*. If you are not logged in your account on the same browser it works well (if not, clear cache and cookies for g*). If you logged in your account in the same browser it don't work.
> 
> Check out the follow account privacy settings in your g* account:
> 
> ![Linked_google_services_01 (1)](https://private-user-images.githubusercontent.com/12845477/303201862-12707ffd-0faf-43b5-b27b-7173d6a8769c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjI3OTUsIm5iZiI6MTcxNjUyMjQ5NSwicGF0aCI6Ii8xMjg0NTQ3Ny8zMDMyMDE4NjItMTI3MDdmZmQtMGZhZi00M2I1LWIyN2ItNzE3M2Q2YTg3NjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAzNDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZGIzZTYyNWUwNjdhODFiYzAwOTQxMTkzZjkzZjYwY2NjYWM5ZTcyM2M2N2Q1MzI3NzQxNjNmMmU1MzdhNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pERFYuda-HQ_dZ89gcxhGum9Y2BuwJwRfiBojCN2Q6Y)
> 
> Enable the following settings
> 
> ![Linked_google_services_02](https://private-user-images.githubusercontent.com/12845477/303201972-7149380c-11a4-4026-b634-ebb79340d979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjI3OTUsIm5iZiI6MTcxNjUyMjQ5NSwicGF0aCI6Ii8xMjg0NTQ3Ny8zMDMyMDE5NzItNzE0OTM4MGMtMTFhNC00MDI2LWI2MzQtZWJiNzkzNDBkOTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAzNDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOTM4ZTMyMmY3ZWQwNTAyMWUxYmRhOTFkNGFhNmU0OWFmMmYzMjkyMGQzMzczZjNlMWU2NzE1ZGI2YmU5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FOFVTt3Hj09DK0O_Juz0w5bkdKXyLBWyTFlX4_z8fL8)
> 
> then it should work again. Seems that g* now requires to enable this or image search and maybe other things don't work anymore.

You are absolute legend! It works like in the times before! Bless you!

**Comment by aleximgs** [comment]
When I search an image instead of the result being directed from google image, its from the home google, do I have to change some settings?
![sample](https://github.com/dessant/search-by-image/assets/170721317/0056806b-99ab-4c2a-94ca-d1d63e06ffd7)
and older results were like:
![sample2](https://github.com/dessant/search-by-image/assets/170721317/cc0ac931-53ea-42d6-bc38-3aa67c5850fc)

**Comment by dessant** [comment]
The next version will add a notice when there are no image search results.

![notice](https://github.com/dessant/search-by-image/assets/7513068/e9c8e287-4797-4c87-8c69-722678e33ab1)

**Comment by dessant** [comment]
I've created a short guide based on your findings which will be linked from the search results notice, you can find it here: https://github.com/dessant/search-by-image/issues/309

**Comment by DB9-max** [comment]
> > I found the problem for image search with g*. If you are not logged in your account on the same browser it works well (if not, clear cache and cookies for g*). If you logged in your account in the same browser it don't work.
> > Check out the follow account privacy settings in your g* account:
> > ![Linked_google_services_01 (1)](https://private-user-images.githubusercontent.com/12845477/303201862-12707ffd-0faf-43b5-b27b-7173d6a8769c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjI3OTUsIm5iZiI6MTcxNjUyMjQ5NSwicGF0aCI6Ii8xMjg0NTQ3Ny8zMDMyMDE4NjItMTI3MDdmZmQtMGZhZi00M2I1LWIyN2ItNzE3M2Q2YTg3NjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAzNDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZGIzZTYyNWUwNjdhODFiYzAwOTQxMTkzZjkzZjYwY2NjYWM5ZTcyM2M2N2Q1MzI3NzQxNjNmMmU1MzdhNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pERFYuda-HQ_dZ89gcxhGum9Y2BuwJwRfiBojCN2Q6Y)
> > Enable the following settings
> > ![Linked_google_services_02](https://private-user-images.githubusercontent.com/12845477/303201972-7149380c-11a4-4026-b634-ebb79340d979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MjI3OTUsIm5iZiI6MTcxNjUyMjQ5NSwicGF0aCI6Ii8xMjg0NTQ3Ny8zMDMyMDE5NzItNzE0OTM4MGMtMTFhNC00MDI2LWI2MzQtZWJiNzkzNDBkOTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDAzNDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOTM4ZTMyMmY3ZWQwNTAyMWUxYmRhOTFkNGFhNmU0OWFmMmYzMjkyMGQzMzczZjNlMWU2NzE1ZGI2YmU5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FOFVTt3Hj09DK0O_Juz0w5bkdKXyLBWyTFlX4_z8fL8)
> > then it should work again. Seems that g* now requires to enable this or image search and maybe other things don't work anymore.
> 
> You are absolute legend! It works like in the times before! Bless you!

What google services you need to link?

**Comment by dessant** [comment]
Version 7.0.0 was just released, and these are the changes related to this issue:

* A notice is injected when you search for an image URL on Goggle Images and there are no search results, this message informs you about the deprecation of the legacy reverse image search service and links to the workaround for viewing search results: https://github.com/dessant/search-by-image/issues/309
* Google Lens has been renamed to Google, and the legacy search service has been renamed to Google Images
* Google Lens was moved to the top of the search engine list, and enabled if Google Images was also enabled
* Google Images is now disabled by default for new installations
