### ISSUE TITLE
disable possible related search

### ISSUE THREAD

**Issue by ususdushdusd** [dessant/search-by-image#291]
Hi I am currently requesting the possible related search to be disabled when reverse image searching a google image
This can be added in the next update 
![cupkkake is back for kerororoororme](https://github.com/dessant/search-by-image/assets/157147952/c8463e91-f279-474e-bbe0-250642de66ea)
Like this

**Comment by dessant** [comment]
Google has deprecated the legacy reverse image search service, and it may stop working at any time, so there's no point in implementing any new features for it.

**Comment by ususdushdusd** [comment]
**Is there a way to disable this feature**
