### ISSUE TITLE
Image search through Google is not working, does not display results

### ISSUE THREAD

**Issue by Matheus2103** [dessant/search-by-image#293]
**System**

* OS name: [e.g. Windows, Ubuntu]
* OS version: [e.g. 10]
* Browser name: [e.g. Chrome, Firefox]
* Browser version: [e.g. 60]
* Extension version: [e.g. 1.0.0]

**Bug description**

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
https://github.com/dessant/search-by-image/issues/290
