### ISSUE TITLE
Request: slim down the app almost 3MB extra addon for every tab is too much - and I only have 2 search engines selected

### ISSUE THREAD

**Issue by DB9-max** [dessant/search-by-image#294]
Ad I only have 2 search engines selected 🤷

Browsers Chrome/Kiwi and Firefox - stable versions on Android.

I remember sometimes Search by Image being heavy on desktop too.

The extension is getting fatter all the time.

It could be slimmer. Of have lite-version.

Suggestion 😺

**Comment by dessant** [comment]
By "3MB extra addon for every tab" are you referring to RAM usage, or something else? From where are you getting this data?

**Comment by dessant** [comment]
Let me know if you have anything to share, and we'll reopen the issue.
