### ISSUE TITLE
能增加分组功能吗？

### ISSUE THREAD

**Issue by xiwensong** [dessant/search-by-image#296]
因为我批量搜索的时候不想一次性打开所有的搜索引擎，所以希望有分组功能，我可以把想要批量使用的搜索引擎都放在分组里。
或者可以给给搜索引擎增加“不参与批量搜索”的设置，也能解决问题

**Comment by Dentoo** [comment]
Go to options and uncheck the search engines you do not want to use.

**Comment by dessant** [comment]
The feature request is tracked here: https://github.com/dessant/search-by-image/issues/68
