### ISSUE TITLE
Yandex.com provides russian text when using image search

### ISSUE THREAD

**Issue by mzso** [dessant/search-by-image#298]
**Is your feature request related to a problem? Please describe.**
Well. Yandex provides russian text for descriptions, suggestions, and in the input-field when showing image search results. So I guess it may be a bug in the site itself.

**Describe the solution you'd like**
Maybe there's an easy way to bypass this via some url or post parameter, when the image is sent to yandex that the addon could do.

**Additional context**
![kép](https://github.com/dessant/search-by-image/assets/4479090/423bfe49-d766-4d17-a1c4-b5bf6ef0de93)

**Comment by dessant** [comment]
I think this is inevitable, Russian text will sometimes be served on Yandex, even if the locale is set to English.
