### ISSUE TITLE
Changing order of engines via drag'n'drop only works when dev tools is open

### ISSUE THREAD

**Issue by krisu5** [dessant/search-by-image#299]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 124.0.1
* Extension version: 6.1.2

**Bug description**
Normally search engine order drag'n'drop doesn't work at all, but when I select correct element on dev tools, it starts working for that specific engine that I selected.

**Logs**

Didn't generate any logs.

**Comment by dessant** [comment]
You need to click on the search engine and hold it steady for 120 ms for it to become draggable. I know this is annoying and can be difficult to discover, but it's a workaround for supporting scrolling over the list with a pen input on mobile devices.

The options UI is being redesigned and there will be a dedicated handle for rearranging list items rather that the whole list item being grabbable, and that should no longer interfere with scrolling.

Ref https://github.com/dessant/search-by-image/issues/68.

**Comment by krisu5** [comment]
> You need to click on the search engine and hold it steady for 120 ms for it to become draggable. I know this is annoying and can be difficult to discover, but it's a workaround for supporting scrolling over the list with a pen input on mobile devices.

Ahh, I see. Well now I know.
