### ISSUE TITLE
Add option to use main context menu for individual search engines instead of submenu

### ISSUE THREAD

**Issue by nicknack23** [dessant/search-by-image#30]
Submenus are so painful to navigate (`right click - move down to option - click` becomes `right click - move down to option - wait for submenu - move right - move down to option - click`). I'd much rather just have a couple of extra entrys in the main context menu. You seem to be liberal with configuration options, could we have an option for this as well?

**Comment by dessant** [comment]
I'd like to have this feature too, but extensions are allowed to create only a single top-level context menu item. The only solution is to install the extension a second time (after changing the uuid in the mainfest if you're using Firefox).

**Comment by dessant** [comment]
I couldn't quickly find any Chrome or Firefox bug report on the matter, only the docs, as a reference:
https://developer.chrome.com/extensions/contextMenus#usage
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus#Creating_menu_items

If you open or find an existing bug report for your browser, please share here.

**Comment by nicknack23** [comment]
I see, thanks for explaining. I'll try the double extension idea and see if it works for me.
