### ISSUE TITLE
add an option to paste from clipboard

### ISSUE THREAD

**Issue by diieg707** [dessant/search-by-image#301]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by diieg707** [comment]
add an option to paste from clipboard.

example: paste from clipboard ->then choose the site (google, yandex, bing etc)

**Comment by dessant** [comment]
Pasting images from the clipboard is supported on most platforms in the Browse search mode.
