### ISSUE TITLE
[Feature Request] Open image-search tabs next to currently active tab instead of all the way to the right/down

### ISSUE THREAD

**Issue by fourteen-1** [dessant/search-by-image#302]
**Is your feature request related to a problem? Please describe.**
### **The problem is that when you have too many tabs open, like while doing research, using this addon makes the new image search tabs open all the way down (in case you navigate tabs using a vertical tab manager) or all the way to the right (horizontal default tab bar). This is incredibly counter-productive since you need to scroll up and search for the tab you originally searched the image from.**

**Describe the solution you'd like**
### **Make the image search tab(s) open next to the currently active tab (the tab the image-search was initiated from)**

**Describe alternatives you've considered**
### A toggle in the settings to enable "Open search tabs under currently active tab", so everyone's happy!

**Additional context**
I'm using this extension as an add-on on the latest version of Firefox on a Windows 10 22H2 system and I primarily use the right-click context-menu to access this program.

**Comment by dessant** [comment]
New tabs are always opened next to the current tab, and it should work as expected with a horizontal tab bar. Vertical tab managers often behave oddly and place new tabs in a different group if `openerTabId` is not set, but that causes issues in Firefox.

If your feature request is related only to vertical tabs, you can subscribe to this issue for updates: https://github.com/dessant/search-by-image/issues/182

If you are really seeing new tabs being opened at the end of the tab strip with the default horizontal tab bar, please share more details about the steps you take to reproduce the issue.
