### ISSUE TITLE
Saucenao search does not go to the search page automatically

### ISSUE THREAD

**Issue by Recyclex** [dessant/search-by-image#305]
Clicking search doesn't do anything either, need to copy and paste the link again to proceed.

![firefox_2024-05-13_21-03-04](https://github.com/dessant/search-by-image/assets/15883662/26e3a3ac-0a4d-4c7f-9ffe-1a33b91c54b5)

**Comment by dessant** [comment]
I've tested in different browsers and could not reproduce the bug. The issue template is there for a reason.
