### ISSUE TITLE
Yandex search no longer works

### ISSUE THREAD

**Issue by jolywho** [dessant/search-by-image#308]
![Снимок экрана 2024-05-18 112954](https://github.com/dessant/search-by-image/assets/39102987/1f2d9353-9215-47f8-b5aa-3bc993cdfa36)

**Comment by dessant** [comment]
Have you also left this review?

https://addons.mozilla.org/en-US/firefox/addon/search_by_image/reviews/2076619/

**Comment by Gitubhu** [comment]
Yandex works for me, can you access yandex.com normally?

**Comment by Gitubhu** [comment]
![Captura de pantalla (337)](https://github.com/dessant/search-by-image/assets/37759562/1e775df3-3624-47e4-9d86-25683f25d078)

**Comment by Gitubhu** [comment]
Yandex works for me, can you access yandex.com normally?
![Uploading Captura de pantalla (337).png…]()

**Comment by Gitubhu** [comment]
Yandex works for me, can you access yandex.com normally?
![Captura de pantalla (337)](https://github.com/dessant/search-by-image/assets/37759562/92aefea1-c75d-4b41-94fd-bbcd924ceee0)

**Comment by dessant** [comment]
I assume the review about Yandex not working came from the same person, and now it was updated to say that everything is working fine. Still, it would have been great to know the error message that was logged in the console. If this becomes a widespread issue, I'm sure someone will fill out the issue template in a new bug report.
