### ISSUE TITLE
Extension disappears from context menu.

### ISSUE THREAD

**Issue by ringofyre** [dessant/search-by-image#311]
**System**

* OS name: Debian
* OS version: Testing
* Browser name: Thorium
* Browser version: Version 124.0.6367.218 (Official Build) stable
* Extension version: 7.0.0
**Bug description**

```

**Comment by dessant** [comment]
Please share more details about the issue. When does the context menu disappear, does it happen after an option change? When it happens, can you still open the toolbar popup of the extension, or is the popup affected too at the same time?

Are you able to reliably reproduce the issue in your browser? Please enable Developer mode in chrome://extensions and turn on "Collect errors" for the extension to catch any exception thrown by the background script.

**Comment by skibiditoilet356** [comment]
Also experiencing this even after changing extension settings and reinstalling. Toolbar popup works.

> Please enable Developer mode in chrome://extensions and turn on "Collect errors" for the extension to catch any exception thrown by the background script.

Where to look for "exception thrown by the background script"?

**Comment by dessant** [comment]
Let me know if the issue is still present.
