### ISSUE TITLE
Add an option to mirror images prior search

### ISSUE THREAD

**Issue by gichtl** [dessant/search-by-image#315]
Sometimes images are just mirrored horizontally so that they cannot be found by most reverse searches.

It would be nice to have an option which mirrors the picture prior search.

**Comment by dessant** [comment]
Adding a simple image editor to the viewer would be ideal, let's track this at https://github.com/dessant/search-by-image/issues/201.

**Comment by gichtl** [comment]
An integrated image editor might be useful if one wants do more complex modifications or crop the image first. But I think that this will overload the plugin. There are already several online image edutors available like https://www.online-image-editor.com/, from which s-b-i can be run.

There ale also a lot of mirror / flip / rotate image online available, but they require a new tab, several extra keystrokes for copy-and-paste the url and some additional mouseclicks

I like the charm to have a simple (re)search for the mirrored image without any further invention by a simple mouseklick.
