### ISSUE TITLE
How to debug it on Firefox?

### ISSUE THREAD

**Issue by directentis1** [dessant/search-by-image#316]
**System**

* OS name: Ubuntu
* OS version: 24.04.4
* Browser name:  Firefox
* Browser version: 128.0.3 (64-bit)
* Extension version: 7.1.0

**Bug description**

For some strange reason neither Seach by Image nor Web Archives works on my main Firefox Instance - although it does work in the a new temporary profile.

 Add-ons appear in the Toolbar, but clicking on them doesn't bring up any functions/popups - it doesn't seem to work..

 I'm not sure how to debug it?
I tried to remove and reinstall it many times but doesn't work.

 Error on console as below when clicking on Add-on symbol from Toolbar on any website as below.

**Logs**

```
Uncaught (in promise) Error: An unexpected error occurred undefined
    Fn moz-extension://41533a27-0567-47f3-9509-016e7cf5a647/src/background/script.js:2
    InterpretGeneratorResume self-hosted:1417
    AsyncFunctionThrow self-hosted:808
    (Async: async)
    <anonymous> moz-extension://41533a27-0567-47f3-9509-016e7cf5a647/src/background/script.js:2
    <anonymous> moz-extension://41533a27-0567-47f3-9509-016e7cf5a647/src/background/script.js:2
    <anonymous> moz-extension://41533a27-0567-47f3-9509-016e7cf5a647/src/background/script.js:2

```
![image](https://github.com/user-attachments/assets/85753646-7a65-4a7b-92ad-aff109b6f0a6)

When clicking on `self-hosted:1417` and `self-hosted:808` from Console logs, it appears like this.
![image](https://github.com/user-attachments/assets/f76c1f81-28a0-4147-be22-2f8397021d69)

**Comment by dessant** [comment]
I don't know what could cause the issue in your browser profile, maybe you have turned off some browser features in about:config that breaks the extension. I think your best bet is to check which browser features were turned off in the profile and try to make the same changes in the new profile to see which one breaks the extension.

**Comment by directentis1** [comment]
@dessant Hmm, I'm not sure what options I changed, but let me try.,,.. but is there a better way to debug instead of messing around 😅

Because these two add-ons were developed by you and both encountered the same error, I guess it's related to some common library..
