### ISSUE TITLE
Extension doesn't work correctly on newest Safari Technology Preview

### ISSUE THREAD

**Issue by Wulgaren** [dessant/search-by-image#319]
**System**

* OS name: MacOS Sonoma 
* OS version: 14.6.1
* Browser name: Safari Technology Preview
* Browser version: Release 201 (Safari 18.0, WebKit 19620.1.2)
* Extension version: 7.1.0

**Bug description**
I can't use the capture or select image functions (can't select anything nor does the purple button show up)

**Comment by dessant** [comment]
Version 8.0.1 was just released to maintain compatibility with Safari 18, you can read about the issues in this thread: https://github.com/dessant/search-by-image/issues/325

Please let me know if you see any other issues with the latest version. You may need to restart Safari after the extension is updated and you notice that content scripts are still not injected in web pages, this is another regression in Safari 18 that impacts Manifest V3 extensions.
