### ISSUE TITLE
Switch the names of "Google" & "Google Images" 

### ISSUE THREAD

**Issue by Shae-Clark** [dessant/search-by-image#322]
**System**
* OS name: Windows
* OS version: 11
* Browser name: Chrome
* Browser version: 128.0.6613.114
* Extension version: 7.1.0

**Bug description**
When I click search on "Google Images" in the context menu it searches in the main Google search
![Clip_2024-09-02_19-00-49](https://github.com/user-attachments/assets/cafcc7df-e20c-4edf-a2f3-106ec8c123d7)

& when I click search "Google" it searches in Google Images 
![Clip_2024-09-02_19-04-29](https://github.com/user-attachments/assets/c59649f8-4eb8-4334-bb27-65fe0fac9701)

So it's backwards.

Is there a way we can rename the options ourselves or switch the names of them on your end

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by BarnMTB** [comment]
The "Google Images" one is from the older [Search-by-image](https://www.youtube.com/watch?v=t99BfDnBZcI) feature in the Google Image search.
It's a part of [Google Image search](https://www.google.com/imghp), and was never a part of [the main "Google" search](https://www.google.com/), so the "Google Images" name is more fitting.

The new "Google" one is the newer one that's powered by Google Lens. 
It's now a part of [the main "Google" search](https://www.google.com/), and it can be accessed on [the main Google page](https://www.google.com/) (something that Google Search-by-image has never got). So it'd make less sense to give it the name "Google Images"

It's even replacing the old "Google Images" one. The old Search-by-image option that has been on the [Google Image search](https://www.google.com/imghp) for so long has been replaced by the new one powered by Google Lens.
It also seems like Google is on their way to replace the old Search-by-image in Chrome with the newer Google Lens one.

So it wouldn't make much sense to reverse the name. 
One has been a long-time feature of [Google Images](https://www.google.com/imghp), never making it onto [the main Google search](https://www.google.com/). 
Another is being embraced as a part of [the core Google search](https://www.google.com/), even slowly replacing the old one.

**Comment by dessant** [comment]
The legacy Google Images reverse image search service has been deprecated by Google a long time ago and will be removed in the near future from this extension.
