### ISSUE TITLE
Github Project Description Missing Popular Browser.

### ISSUE THREAD

**Issue by Jer-C** [dessant/search-by-image#324]
**Is your feature request related to a problem? Please describe.**

In the Github project description, which shows on the top right of the page on desktop browsers, there is an `About` section. The section reads as follows:
"Browser extension for reverse image search, available for Chrome, Edge and Safari"

This led me to initially pass over this project, as I use Firefox. I was later corrected by a member of the community.

**Describe the solution you'd like**

I would like Firefox to be added to the list of browsers in the project description. This makes sense to do, since it is one of the big 3:
Chromium (Chrome, Opera, and Edge)
Safari
Firefox

**Describe alternatives you've considered**

Alternatively, replacing the word "Edge" with the word "Firefox" could be done if space is a major concern, though I wouldn't recommend this. Edge and Chrome use very similar extension stores, so extensions available for one are often available for the other as well. If space in the description is constrained, then listing them both could be considered redundant.

But really this is just a request to add Firefox to the list, so it doesn't get passed up by others who just read the description like I did.

**Additional context**

This description is also shown as a summary on several pages leading to this project page. This is shown
- when someone links to the project (as would be done on Discord or other social media)
- when browsing [Dessant's profile](https://github.com/dessant) of hosted projects (such as if they enjoyed one project and wanted to see what else the author had done)

**Comment by dessant** [comment]
Thanks for the suggestion, the repository description snippet is used to direct attention to where we see it being the most beneficial, and it may change over time.
