### ISSUE TITLE
Problems with SEARCH BY IMAGE extension

### ISSUE THREAD

**Issue by TOPPISTAMPA** [dessant/search-by-image#328]
Hello, the setting of this extension no longer works for google image, it only connects me to google lens.
If I understand correctly, it will never be the same again, I am an advertising graphic designer and it was essential for me, do you know how to give me an alternative?

**Comment by dessant** [comment]
Google has deprecated the legacy reverse image search service, and there is nothing we can do about this. Google Images is still accessible from the extension, but it doesn't work for everyone. If you're lucky, you may be able to get it working by following this guide: https://github.com/dessant/search-by-image/issues/309
