### ISSUE TITLE
Google Lens search interface was replaced with a fresh horror, can the old one be brought back?

### ISSUE THREAD

**Issue by mzso** [dessant/search-by-image#334]
**Is your feature request related to a problem? Please describe.**
New interface sucks

**Describe the solution you'd like**
If the old Lens interface can be dug up and used it would be nice, similarly to the old reverse image search.

**Comment by dessant** [comment]
I'm not sure what do you mean by the old Lens interface, but in any case this project has no influence over how search results are shown. If you find a way to access the layout you're talking about, please share it here in the future. Regarding the legacy reverse image search service, check out https://github.com/dessant/search-by-image/issues/309.

**Comment by mzso** [comment]
Well, maybe it wasn't released for everyone? I only see it since a week or two.
The new layout is like this:
![kép](https://github.com/user-attachments/assets/d1a73870-0fa9-4f4c-bc41-4b19d11d3ab0)
I couldn't even find how to access the translate and OCR features. It turns out you need to click that miniature. It opens in a doorhanger and is really crappy:
![kép](https://github.com/user-attachments/assets/fca720ff-a0b0-4b8e-b112-3ce3a556ea87)
Translation is just as compressed and horrible:
![kép](https://github.com/user-attachments/assets/13ac0e57-fdfe-45a7-be64-e4d6a5fa9c40)
