### ISSUE TITLE
TinEye no longer works

### ISSUE THREAD

**Issue by globau** [dessant/search-by-image#336]
**System**

* OS name: macOS
* OS version: 15.1
* Browser name: Firefox
* Browser version: 132.0.1
* Extension version: 7.1.0

**Bug description**

Steps

1. copy image
2. change mode to Browse
3. select TinEye

Expected

- TinEye search

Actual

- https://www.tineye.com/ without any search results

**Comment by globau** [comment]
The context menu option works, and the element SBI is looking for still exists.  Perhaps a timing issue?

**Comment by p3ngwin** [comment]
+1

**Comment by mzso** [comment]
Until recently it seemed to sometimes work, sometimes not. But right now it seems to consistently fail. Only the the Tineye main page is opened.

**Comment by dessant** [comment]
They could have been testing some changes that were now deployed for all users, if it continued to intermittently work until now. A new version will be published with the fix in the next few days, let me know if the issue reappears when the "Select image" search mode is in use.
