### ISSUE TITLE
Select & upload is not working on firefox

### ISSUE THREAD

**Issue by Sahariza** [dessant/search-by-image#39]
^

**Comment by dessant** [comment]
Please share more details. Which site and image? I need to be able to test to see what is the cause of the issue.

**Comment by Sahariza** [comment]
:/
When i'm trying to search local file:/// image, addon doesn't upload it and just trying to search by url.
Please just try it yourself. It's 1.14.0 bug, 1.13.0 works fine.

**Comment by dessant** [comment]
Now that you've shared that it's an issue with searching file:// urls, I've tested it and can reproduce the bug. For future reference, local images loaded in tabs should also upload when the "Select" search mode is used, file:// image searching is a feature that predates the "Select & Upload" search mode.
