### ISSUE TITLE
Versions after 1.14.1 Don't Work With Firefox 52.9.0ESR on Windows 10

### ISSUE THREAD

**Issue by Voideka** [dessant/search-by-image#41]
When using Firefox 52.0.9 ESR on Windows 10, newer versions of Search By Image (1.15.0 and 1.16.0) are non-functional. I've tried with a fresh profile and ruled out add-on conflicts. The context menu option does not show up, and the nav-bar button does nothing.

**Comment by dessant** [comment]
@Voideka, thanks for noticing and reporting the bug, a new version has been published with the fix.
