### ISSUE TITLE
New Feature: Open search tab in the background.

### ISSUE THREAD

**Issue by jedikalimero** [dessant/search-by-image#44]
When you use SBI by right clicking on an image and selecting a search engine in the submenu, the search engine tab opens in the foreground (a new tab opens and Firefox changes focus to this tab). If you want to open it in the background and keep focus in the current tab, there is apparently no way to do it.

I suggest that by selecting the search engine with the Middle Mouse Button or with CTRL + Left Mouse Button, the tab should open next to the current tab but without changing focus to it, keeping the user in the current tab.

Similarly should happen if the user has configured opening new pages in a new window instead of a new tab (it is rare, but there are people like that).

**Comment by dessant** [comment]
Opening new tabs in the background is already supported, visit the options page to enable it.

![screenshot from 2018-09-22 19-23-49](https://user-images.githubusercontent.com/7513068/45919382-1cf8a400-be9d-11e8-864c-aee65d70b34b.png)

Opening new windows is not planned to be implemented at this time.

**Comment by jedikalimero** [comment]
Yes, I know. But this option open new tabs in the background ALWAYS

**Comment by dessant** [comment]
Based on your initial issue, I got the impression that you were not aware of the possibility to open new tabs in the background at all.

Modifying the behavior on the fly when the context menu is used should also be possible to implement, but only for Firefox, see support for the `modifiers` property.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/OnClickData#Browser_compatibility
