### ISSUE TITLE
New User Question

### ISSUE THREAD

**Issue by ShadetreeSam** [dessant/search-by-image#45]
Hi,
I just added the Search by Image extension to my Google Chrome browser, and I'm not sure if I'm using it correctly. What I want to do is search the Internet for a person's face, which I have on my computer in a .jpg file. I clicked on the extension, kept the default of "All search Engines," an then selected Upload from the dropdown menu. I expected a popup to open that would allow me to select the image file I wanted to search for, but nothing happened. Can you tell me how to use this extension to do what I described above? 
I'm using the extension for a Chrome browser running on Windows 10, both of which are fully up-to-date.
Thanks very much for your help,
--Ralph

**Comment by dessant** [comment]
If you have selected "Upload" from the menu in the upper-right corner, then clicked "All search engines", a new tab should have opened from where you can select a local image.

![screenshot from 2018-10-07 20-34-06](https://user-images.githubusercontent.com/7513068/46584792-73a2d800-ca70-11e8-9aae-6d9a2f63f069.png)

I cannot reporduce the issue you're having, try turning on error collection on the extension page: chrome://extensions/?id=cnojnbdhbhnkbcieeekonklommdnndci

Then repeat the steps you did before, and see if there is any error listed on the extension page.

**Comment by dessant** [comment]
You may not have clicked the "All search engines" button, let me know if it still doesn't work.
