### ISSUE TITLE
Secondary context sub-menu?

### ISSUE THREAD

**Issue by uNderdog101** [dessant/search-by-image#47]
99% of my searches are done by right-clicking an image and then "All search engines" in the sub-menu, using my pre-selected generic engines (Google, Bing, Yandex, Tineye, KarmaDecay), and all is well. However, once in a blue moon I need to search an image using an engine that isn't in my selection, and _only_ that one, and to do so would entail going into the options and selecting it and de-selecting all the others.

Would it be possible to add a secondary sub-menu that contained _all_ the engines for single search selection? Maybe at the bottom of the "Search by Image" it would say "Other engines" and would pop out a menu with all the options?

Also, unrelated side-note instead of creating another post; Could you add ImgOps.com as an engine option? I know it's not an actual engine, but it would be pretty sweet to have right-click access to its functionality, and the only other option I've found is a clunky bookmarklet.

**Comment by uNderdog101** [comment]
> ImgOps is not planned at this time.

Could it be, please :pray: ?

**Comment by dessant** [comment]
> Could it be, please :pray: ?

For now this extension is for reverse image search only.

**Comment by dessant** [comment]
@oli787, as discussed on Twitter, make sure to open a new issue, and fill out the issue template entirely.

**Comment by dessant** [comment]
Tracking at https://github.com/dessant/search-by-image/issues/68.
