### ISSUE TITLE
[Not an issue] FYI, there is a copy of your extension on AMO not respecting the license

### ISSUE THREAD

**Issue by FatOrangutan** [dessant/search-by-image#49]
https://addons.mozilla.org/en-US/firefox/addon/fast-image-search/

It even links to this repo as its `Homepage`.

**Comment by dessant** [comment]
The listing has been reported, thanks for letting me know!

**Comment by dessant** [comment]
The listing is still up. Besides the copyright violation, the other important issue is the way the extension is presented.

The homepage is set to this repo, and the extension has a page requesting contributions in my name, missleading users into thinking that I'm the maintainer of that listing.

I'd urge everyone to report the extension and mention in reviews that it is not controlled by me.

**Comment by dessant** [comment]
The extension is gone.
