### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by Keith94** [dessant/search-by-image#5]
There's no changelog for the new version, so I'm curious what these permissions are for?
>Access your data for all websites
Display notifications to you

**Comment by dessant** [comment]
You're right, I'll publish a changelog from now on. Quite a lot has changed actually.

A new parser was implemented, which is executed in the tab when you select an image, the `executeScript` API requires host permissions to work, and that is why `<all_urls>` is added in the permission list. This new parser allows for finding mostly any image present under the selected area, not just `<img>` elements.

In the previous version the context menu item only appeared when you've opened it above an `<img>` element, but now it will attempt to find an image under any selected area, and show a notification if no image was found (though the notification was tested only on linux).

**Comment by Keith94** [comment]
Sounds good :) Thanks for the explanation!

**Comment by dessant** [comment]
Fixed in https://github.com/dessant/search-by-image/commit/f7a33745616053b25edf9d19e2a92ddccdc154a0.
