### ISSUE TITLE
Baidu search not working

### ISSUE THREAD

**Issue by ReporterX** [dessant/search-by-image#51]
**System**
* OS name: Windows
* OS version: 7
* Browser name: Firefox
* Browser version: 66.0.3
* Extension version: 1.19.0

**Bug description**
1. Go to https://www.google.com/search?q=happy&tbm=isch#imgrc=_
2. Right click that image (as shown below)
![screenshot 6](https://user-images.githubusercontent.com/8235338/56106270-ef776300-5f72-11e9-95bb-a05a898e9bd4.jpg)
3. Search by Image > Baidu

It failed to do image search at Baidu.  
Note: If you click to see the larger size of the image and then do an image search, it works though.

**Comment by dessant** [comment]
Hi, thanks for the bug report! I'm a bit busy these days but I'll look into it next week and release a fix.

**Comment by dessant** [comment]
It seems Baidu has deployed a new version of image search which loads results from graph.baidu.com and it is very slow. The old service can still be used while searching with an image URL, so we'll use the new service only when uploading images for now.
