### ISSUE TITLE
Upload doesn't work on Opera

### ISSUE THREAD

**Issue by M45T3Ryu** [dessant/search-by-image#52]
would be cool if you could select in which sites to upload and which not to upload 

Also.. maybe remove the "Search" confirmation on Capture? It just feels unresponsive having to do extra steps just to start te search when you already selected. 

I know its a safety measure but I think "auto-force searching on capture" would be really cool

**Comment by dessant** [comment]
The issue title appears to be a bug report, and the issue body seems to contain two feature requests. Please open separate issues for each bug report and feature request, and fill out the issue and feature request templates. Make sure to provide sufficient details for the bug to be reproducible.
