### ISSUE TITLE
TinEye - bypass google captcha?

### ISSUE THREAD

**Issue by atomGit** [dessant/search-by-image#53]
TinEye recently implemented google's idiotic and privacy invading captcha and i'm wondering if that can be bypassed, possibly through [their API](https://api.tineye.com/)?

maybe it will help to look at this code...
https://addons.mozilla.org/en-US/firefox/addon/tineye-commercial-api-searc/

**Comment by dessant** [comment]
I can search on TinEye without solving a captcha, how do you trigger it?

**Comment by atomGit** [comment]
it must a privacy related preference - if i find which one i'll let you

**Comment by dessant** [comment]
Ok, let me know if you find a way to reproduce the issue, and I'll reopen the bug report.

**Comment by atomGit** [comment]
TinEye made a change apparently in that they now require more resources from both google.com and gstatic.com and i had the necessary stuff blocked with uMatrix

sorry, i should have tested this with a clean profile first, but all was working prior so i skipped that step :)
