### ISSUE TITLE
Upload doesn't work on Opera

### ISSUE THREAD

**Issue by M45T3Ryu** [dessant/search-by-image#54]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Opera 
* Browser version: 60.0.3255.59
* Extension version: 1.19.0 (Opera Latest)

**Bug description**
Upload mode doesnt work on Opera I tried on Chrome and it does work easily, when I use Upload or Capture mode on Opera I get "default webpages" as result 

There is an example img

Img searched:
![opera_w3kqthuywo](https://user-images.githubusercontent.com/2993425/57172211-995b4a00-6dd1-11e9-83e2-84dc4b21bf15.png)

Result:
![opera_hFI9BghQX9](https://user-images.githubusercontent.com/2993425/57172213-a6783900-6dd1-11e9-8ae9-62ea57519cc3.jpg)

**Comment by dessant** [comment]
The "Allow access to search page results" option must be checked for the extension on the chrome://startpage/extensions page, otherwise it may not work as expected.
