### ISSUE TITLE
Image capture not searching 

### ISSUE THREAD

**Issue by oli787** [dessant/search-by-image#59]
**System**

* OS name: [e.g. Windows, Ubuntu] windows
* OS version: [e.g. 10] 10
* Browser name: [e.g. Chrome, Firefox]   Firefox
* Browser version: [e.g. 60]    69.0.2
* Extension version: [e.g. 1.0.0]  
windows
10
Firefox
69.0.2
1.21.2
**Bug description**

When i use the right click function the tool works fine
when i use the capture option to look at a specific part of the image it will only search in google
it wont search yandex baido bing or tineye. 
**Logs**

```
// REPLACE WITH LOGS
```

**Comment by oli787** [comment]
its not populating the search in  any of the search engines apart from google, if i crop the image and search manually if gets results.

**Comment by dessant** [comment]
I'm having trouble understanding the exact steps you take and what you see on the screen. Please create a video about the entire process of using the extension.

**Comment by oli787** [comment]
Startpage.com Search results - Mozilla Firefox ...
<https://drive.google.com/file/d/1pF7m9iCYJv_pDLJO9LWMV4HGCgDAzYVy/view?usp=drive_web>

**Comment by dessant** [comment]
Interesting, the pages do open, but the script which perfoms the search is not injected. There should be an error somewhere in the console log (Ctrl+Shift+J), please check it.

If you will not see any error, make sure to disable all your other extensions and test again. It is possible that one of them interferes with Search by Image.

**Comment by oli787** [comment]
These are the faults which have been logged

**Comment by dessant** [comment]
Did you intend to share some logs? There is nothing in your previous message.

**Comment by oli787** [comment]
Hi Armin a shared an image i will upload it again

**Comment by oli787** [comment]
its not letting me upload an image can i send it directly to you?

**Comment by dessant** [comment]
Upload it to Imgur and share the link.

https://imgur.com/upload?beta

**Comment by oli787** [comment]
https://imgur.com/a/3C0z54l

**Comment by dessant** [comment]
Let's search only with Yandex, copy the logs from the browser console after searching with it alone.
Also check the logs in a different console that logs errors only for the current page, you can open it with Ctrl+Shift+K while you're on the Yandex tab. Try to copy recent logs from both of these places.

When you are done with all of this, please disable ALL of your extensions, except this one, then restart the browser, and try to search again. It is possible that one of your other extensions is causing an issue. Share what was the result of this test.

**Comment by dessant** [comment]
You must find a way for me to reproduce the issue, because it works on my device, and so far nobody else has reported this issue.
