### ISSUE TITLE
when searching all search engines, it just search on the first 5.

### ISSUE THREAD

**Issue by panderlad** [dessant/search-by-image#60]
You are mentioning on the description of the add that can search on these Search engines:

    Google Images
    Bing Images
    Yandex.Images
    Baidu Image Search
    Sogou Images
    Qihoo 360 Images
    Mail.ru Image Search
    Getty Images
    iStock
    Shutterstock
    Adobe Stock
    Depositphotos
    Jingdong
    Taobao
    Alibaba China
    Pinterest
    TinEye Reverse Image Search
    Karma Decay
    trace.moe (WhatAnime)
    SauceNAO
    Iqdb
    Ascii2d

///

But when searching all search engines, it just search on the first 5.

So why?

**Comment by dessant** [comment]
See my answer here: https://github.com/dessant/view-page-archive/issues/13#issuecomment-545508926
