### ISSUE TITLE
yandex.ru support

### ISSUE THREAD

**Issue by rampaa** [dessant/search-by-image#61]
I find yandex.ru to be better than yandex.com at reverse-searching images. So if possible, I would like to be able to specifically use yandex.ru instead of yandex.com. I think this can easily be achieved by splitting Yandex.Images into "yandex.com Images" and "yandex.ru Images" in the settings.

I am using a different add-on in addition to yours just for yandex.ru support but I would rather achieving the same result with just one add-on if possible.

**Comment by dessant** [comment]
I plan to add support sometime next year for customizing search engines. You'll be able to configure multiple instances of the same search engine with different options, such as locale.

**Comment by dessant** [comment]
Tracking at https://github.com/dessant/search-by-image/issues/68.
