### ISSUE TITLE
Search by Image update rejected from the Chrome Web Store

### ISSUE THREAD

**Issue by dessant** [dessant/search-by-image#63]
The latest version of the extension has been repeatedly rejected from the Chrome Web Store. Reviewers are again taking issue with the description, and now also the screenshots. The listed policy violations are vague, and reviewers did not clarify which screenshot or paragraph in the description they find problematic.

The last time this has happened I've attempted to communicate with them, and they ended up removing the extension entirely from the store, listing further nonsense policy violations, a decision which was reversed after I've made the [discussion with reviewers](https://github.com/dessant/search-by-image/issues/57) public.

Since reviewers are not willing to share any actionable information that would lead to the latest version of the extension being published, I see no other recourse but to appeal to the public again.

I'm tired of arguing with the employees of a megacorp to justify the existence of my open source projects, and I feel sick every time I have to fight for the results of my free labor to reach users.

It is appalling to see Google subject developers to this treatment, and censor open source projects out of existence.

**Comment by dessant** [comment]
Search by Image 2.0.0 was submitted with the screenshots and the description currently published on the [Chrome Web Store](https://chrome.google.com/webstore/detail/search-by-image/cnojnbdhbhnkbcieeekonklommdnndci). The new version was rejected.

---

Chrome Web Store Developer Support <chromewebstore-dev-support@google.com>	Tue, Dec 24, 2019 at 3:17 PM
To: Armin Sebastian <*****@gmail.com>

Dear Developer,

Your Google Chrome item "Search by Image" with ID: cnojnbdhbhnkbcieeekonklommdnndci did not comply with our policies and was removed from the Chrome Web Store.

Your item did not comply with the following section of our Program Policies:

"Spam and Placement in the Store"

- Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.
- Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.
- Screenshots must demonstrate the functionality of the extension in action.


Once your item complies with Chrome Web Store policies, you may request re-publication in the Chrome Web Store Developer Dashboard. Your item will be reviewed for policy compliance prior to re-publication.

If you have any questions about this email, please respond and the Chrome Web Store Developer Support team will follow up with you.


Important Note:

Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform.

This may also result in the suspension of related Google services associated with your Google account.


Sincerely,

Chrome Web Store Developer Support

**Comment by dessant** [comment]
I thought they must have objected to the outdated screenshots, some buttons were added to the extension since they were taken, and the layout of the options page has changed, although they represent the functionality of the extension quite well.

I've released version 2.1.0 since the last submission, so I've submitted it for review with a set of new screenshots taken in Chrome.

Here are the submitted screenshots and the description for Search by Image 2.1.0:

<p>
  <img width="200" src="https://i.imgur.com/pbQ2RKV.png">
  <img width="200" src="https://i.imgur.com/79hmyEz.png">
  <img width="200" src="https://i.imgur.com/entsCeu.png">
  <img width="200" src="https://i.imgur.com/hxBn7xT.png">
  <img width="200" src="https://i.imgur.com/NC2xecL.png">
</p>

---

Search by Image is a browser extension which enables you to initiate a reverse image search from the right-click context menu or the browser toolbar, and comes with support for more than 20 search engines.

Images positioned at the selected area are detected regardless of how they were embedded in the page. The extension also supports uploading local images, searching for video frames, capturing details within images, and searching for images from private sites.

The continued development of Search by Image is made possible thanks to the support of awesome backers. If you'd like to join them, please check out https://armin.dev/go/patreon

A diverse set of reverse image search engines are supported, which can be toggled and reordered from the extension's options. Visit the wiki for the full list of supported search engines.

https://github.com/dessant/search-by-image/wiki/Search-engines

A handful of search modes are offered that serve different use cases. The search mode can be set independently for the context menu and browser toolbar from the extension's options.

Search modes:
  • Select (context menu and toolbar): select an image on the page, then search for the image URL, whenever possible. Blob and data URLs will still be handled as image uploads. This is the default search mode.
  • Select & upload (context menu and toolbar): select an image on the page, then fetch the image, possibly from the browser cache, and upload it. This search mode is preferred for sites which do not allow direct linking of images or are otherwise private.
  • Capture (context menu and toolbar): select and capture a page area, then upload it.
  • Upload (toolbar): select or drop an image from your device, or paste it from the clipboard, then upload it.
  • URL (toolbar): search for an image URL.

Features:
  • Search with a single engine, or all enabled ones, directly from the top-level context menu item, or the browser toolbar button (see options)
  • Detect any image on the page, including those declared in CSS and pseudo-elements
  • Select the desired image from a dialog when multiple images are found
  • Search for images from private sites (see search modes)
  • Search for local images
  • Search for the current video frame

The context menu item is always visible, unless it is disabled. Visit the wiki for more details.

https://github.com/dessant/search-by-image/wiki/Why-is-the-extension-always-visible-in-the-context-menu%3F

The image you select during a search is sent to the requested third-party service, such as Yandex.Images. Visit the extension's privacy policy for more information.

https://github.com/dessant/search-by-image/wiki/Privacy-policy

The extension is also available for Edge, Firefox and Opera: https://github.com/dessant/search-by-image#readme

Reviews are not monitored for bug reports, please use GitHub for issues and feature requests.

https://github.com/dessant/search-by-image

**Comment by dessant** [comment]
Search by Image 2.1.0 was also rejected with the exact same list of policy violations.

---

Chrome Web Store Developer Support <chromewebstore-dev-support@google.com>	Mon, Dec 30, 2019 at 12:50 PM
To: Armin Sebastian <*****@gmail.com>

Dear Developer,

Your Google Chrome item "Search by Image" with ID: cnojnbdhbhnkbcieeekonklommdnndci did not comply with our policies and was removed from the Chrome Web Store.

Your item did not comply with the following section of our Program Policies:

"Spam and Placement in the Store"

- Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.
- Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.
- Screenshots must demonstrate the functionality of the extension in action.


Once your item complies with Chrome Web Store policies, you may request re-publication in the Chrome Web Store Developer Dashboard. Your item will be reviewed for policy compliance prior to re-publication.

If you have any questions about this email, please respond and the Chrome Web Store Developer Support team will follow up with you.


Important Note:

Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform.

This may also result in the suspension of related Google services associated with your Google account.


Sincerely,

Chrome Web Store Developer Support

**Comment by dessant** [comment]
It's not clear why was the latest submission rejected, so I've contacted them to ask for more information.

---

Armin Sebastian <*****@gmail.com>	Thu, Jan 2, 2020 at 11:32 AM
To: Chrome Web Store Developer Support <chromewebstore-dev-support@google.com>

Hi,

All of the newly submitted screenshots show the extension's user interface on Chrome, and the description clearly states the purpose and features of the extension. Please share which screenshot and description paragraph does not comply with your policies, and specify the policy sections that are not being followed.

Thanks,
Armin Sebastian

**Comment by dessant** [comment]
They have responded, but they haven't shared any details about which screenshot or description section in against their policy.

The reply does not contain any actionable information, only a list of policy violations (with some sections in bold) which do not seem to apply to the extension listing.

---

Chrome Web Store Developer Support <chromewebstore-dev-support@google.com>	Fri, Jan 3, 2020 at 9:02 AM
To: Armin Sebastian <*****@gmail.com>

- Description does not go with the functionality of the item.
- Unclear Description.
- Title does not match with the Description.
- Scrapped Content in the Description.
- Copying Description from other items in the store.

Dear Developer,

Your item, "Search by Image," with ID: cnojnbdhbhnkbcieeekonklommdnndci , did not comply with our Developer Program Policies and was removed from the Google Chrome Web store. 

Your item did not comply with the following section of our policy:

Products must not contain false or **misleading information**, including in the content, title, icon, description, or screenshots.


Here are some specific checks you can conduct to ensure your item complies with our policies.

- **Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.**
- Screenshots must demonstrate the functionality of the extension in action.

If you’d like to re-submit it, please modify the item so that it complies with the policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal.

*Please keep in mind that after you resubmit your item, it will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published only if the item passes that review.

*Important Note

Repeated or egregious violations of the policies may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted items will continue to be subject to the Chrome Web store program policies and terms of service.


Thank you for your cooperation,

Chrome Web Store Team

**Comment by dessant** [comment]
The description clearly states the functionality and the available features of the extension. It's worth noting that during the [previous takedown](https://github.com/dessant/search-by-image/issues/57) they have objected to the full list of search engines being included in the description, that's why I'm only linking to it.

I cannot afford to argue with Google employees that send me copy-pasted snippets as replies, and force me to experiment with different screenshots and description versions in the hopes that one variation might pass their arbitrary review, while being reminded in every single rejection message that I might lose my Google account if I continue to submit versions which do not comply with their policies.

Google's approach to communication and extension reviews is cruel and unjust, and it hurts open source projects and their users.

If you feel the same way, please make your voices heard.

**Comment by dotproto** [comment]
Thanks for tagging me on Twitter. I'm working on getting in the habit of checking my GH notifications more often, but for the moment Twitter and chromium-extensions are the most reliable ways to reach me.

Often in situations like this I end up looking into the rejection and coming back to the dev with more details on the nature of the violation. I don't quite understand the rejection in this case and have reached out to the review team for clarification. Unfortunately, I don't expect to hear back until next week at the earliest.

**Comment by dotproto** [comment]
Could you please resubmit the draft? This will enable the reviewers to take another pass at it.

**Comment by dessant** [comment]
@dotproto, thanks for looking into this, the listing has been resubmitted.

**Comment by dotproto** [comment]
Awesome, once it is reviewed it should be back in the store. 👍

**Comment by dessant** [comment]
@dotproto, thanks for helping to reinstate the extension, the latest version is now live. I don't know what's going on with the reviewer team, they continue to initially reject updates for my other extensions with the same list of policy violations.

https://github.com/dessant/youtube-autoplay/issues/3
https://github.com/dessant/youtube-video-quality/issues/4

Autoplay Settings for YouTube has been approved after I've contacted them, while Video Quality Settings for YouTube remains to be seen.

**Comment by dessant** [comment]
@dotproto, I have submitted version 2.1.1 a month ago and the review is still pending. Since then I have released version 2.2.0, but I can no longer submit updates until the extension is tuck in pending review for the previous version. Could you take a look at the status of the extension?

**Comment by SunilLazarus** [comment]
Hi @dotproto, 

I also recevied the same email and not sure on what to change in order to get published. All the descriptions, screenshots are clear. Appreciate any inputs on this. thanks in advance

ID: mkefclgpnimobkolhofhpcjpjibkmhna

Spam and Placement in the Store"
•	Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.
•	Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.
•	Screenshots must demonstrate the functionality of the extension in action._

**Comment by Poopooracoocoo** [comment]
@dotproto another extension that's been affected by chrome web store reviewers is session buddy. there are various others too
