### ISSUE TITLE
[Feature request] Support for swisscows

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [dessant/search-by-image#64]
Can you please add support for [swisscows](https://swisscows.ch/web?culture=en&query=images)?

**Comment by dessant** [comment]
I can't find any reverse image search tool on that site. Could you point me in the right direction?

**Comment by Vulgaris-Viridis** [comment]
Sorry my bad, I've recently discovered them and i assumed they have reverse image search integrated like most of others. I've just checked and you are right. Thanks for taking time to look into this @dessant. Much appreciated
