### ISSUE TITLE
Allowing to create groups of reverse search engines to match differents contexts

### ISSUE THREAD

**Issue by secou** [dessant/search-by-image#71]
**Problem.** Now that there's plenty reverse search engines in the list (and that's  wonderful!), I am faced with the following problem. 

Different contexts lead me to use different groups of reverse search engines:
- investigations related to a decontextualization of news photos
- identification of real persons
- identification of false profiles
- analysis of images containing logos/brands 

**Solution?** It would be great to let us create "contexts": groups of reverse search engines and having the ability to "call" them in a specific context.

A bit like [the "Context" browser plugin](https://github.com/kdzwinel/Context) does to manage plugins in Chrome/Brave.

**Comment by dessant** [comment]
I agree that it would be awesome to have this feature! There's a plan to introduce customizable search engine groups, though it's most likely a good few months away due to lack of time. The issue is tracked here: https://github.com/dessant/search-by-image/issues/68
