### ISSUE TITLE
Yandex Search does not work, if you use proxy and "Select & Upload" option

### ISSUE THREAD

**Issue by nlboom** [dessant/search-by-image#72]
Yandex Search does not work, if you use proxy and "Select & Upload" option in settings. In the previous version search worked. 
![655656565645544545](https://user-images.githubusercontent.com/15813558/78814250-fe062800-79d6-11ea-8241-017866fc0f05.png)

**Comment by nlboom** [comment]
What do I need to indicate so that my ticket is not closed?

**Comment by Darwin1546** [comment]
I can confirm this issue and it's contain enough information.
When you tries to search local image on yandex. You will receive error and default page: https://yandex.ru/images/?rdrnd=735291&redircnt=1586770903.1
![изображение](https://user-images.githubusercontent.com/63585283/79111252-bf91b400-7dae-11ea-904b-8fbe96ac712e.png)
![изображение](https://user-images.githubusercontent.com/63585283/79111346-ef40bc00-7dae-11ea-9814-372548b4a975.png)
