### ISSUE TITLE
Chinese Simplified (zh-CN) Language Pack

### ISSUE THREAD

**Issue by fox010** [dessant/search-by-image#75]
[Chinese Simplified (zh-CN) Language Pack.zip](https://github.com/dessant/search-by-image/files/4578748/Chinese.Simplified.zh-CN.Language.Pack.zip)

![image](https://user-images.githubusercontent.com/23356274/81031882-6d7d1380-8ec0-11ea-994c-885d4c27a240.png)

**Comment by dessant** [comment]
Thanks for your contribution! I'm going to set up a Crowdin project in the near future and import the translated strings there for validation.

**Comment by dessant** [comment]
The issue is being tracked at https://github.com/dessant/search-by-image/issues/255.
