### ISSUE TITLE
Capture searching in Chrome incognito

### ISSUE THREAD

**Issue by deadclicks** [dessant/search-by-image#76]
* OS name: Windows 10
* Browser: Chrome 81
* Extension version: 2.1.0

**Bug description**
When I do a Capture search in an incognito window the extension opens the results in a normal window, I think the expected behavior would be to open the results in the same incognito window.. can you please fix this?

**Comment by dessant** [comment]
Thanks for the bug report! I have reproduced the issue, and the `Search & upload` mode is also affected.
