### ISSUE TITLE
Can't open options

### ISSUE THREAD

**Issue by B0pol** [dessant/search-by-image#77]
**System**

* OS name: Android
* OS version: 9
* Browser name: Firefox Preview (a.k.a Fenix)
* Browser version: 5.0, also happens with nightly.
* Extension version: 2.2.1

**Bug description**

1. Open search by image on **Firefox Preview**.
2. Click on the three dots menu
3. Click on "options"

--> Nothing happens. It should open options and I should be able to select the search engines I want.

I originally reported here: https://github.com/mozilla-mobile/fenix/issues/10591 but this repo is maybe more appropriate?

**Comment by dessant** [comment]
The upstream issue is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1619766

**Comment by dessant** [comment]
Until this is fixed in Firefox Preview, the settings of the extension can also be opened from the add-ons page of the browser.
