### ISSUE TITLE
Yandex image search fails 100% of time with firefox

### ISSUE THREAD

**Issue by s1raz1** [dessant/search-by-image#80]
**System**

* Windows 
* 10 x64
* Firefox
* 77.0.1 x64
* 2.2.1

**Bug description**
Just select any image with firefox and search for it asking to use yandex and it will always end up with image couldnt be loaded. Now if you open the same image using google as image search engine then use the image google opened and search for it asking to use yandex the same image will be loaded with no problem. 
With firefox directly asking yandex to search image will always fail to load .

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by llacb47** [comment]
Just tested with this page: `https://http.cat/`

Works fine.
