### ISSUE TITLE
Tapping options does nothing in Firefox Preview

### ISSUE THREAD

**Issue by leela52452** [dessant/search-by-image#81]
**System**

* OS name: [e.g. Windows, Ubuntu] android
* OS version: [e.g. 10] 9
* Browser name: [e.g. Chrome, Firefox] firefox preview
* Browser version: [e.g. 60] 5.2.0
* Extension version: [e.g. 1.0.0] 2.2.1

**Bug description**

firefox preview 5.2.0

* visit en.wikipedia.org
* three dot menu
* addons
* search by image
* three dot menu
* options
![Screenshot_20200619-184235_Firefox Preview](https://user-images.githubusercontent.com/52065244/85136777-a9312a00-b22f-11ea-807d-e49311c6b61a.jpg)

it does nothing. is this intentional ?
**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
This is an upstream bug, see this issue for details: https://github.com/mozilla-mobile/fenix/issues/10591

**Comment by dessant** [comment]
The bug has been fixed in GeckoView 79, and it's already live in Firefox Nightly.
