### ISSUE TITLE
Support Dark Theme

### ISSUE THREAD

**Issue by xmha97** [dessant/search-by-image#86]
Hi, Please support the system-wide dark theme. (like [View Image](https://github.com/bijij/ViewImage) extension)

<details>
    <summary>GIF image</summary>
    <img src="https://user-images.githubusercontent.com/23485114/87686958-6749c400-c79a-11ea-996e-abf0bbffe6cb.gif">
</details>

**Comment by TotalCaesar659** [comment]
I've made the PR [here](https://github.com/dessant/search-by-image/pull/79).

**Comment by xmha97** [comment]
> I've made the PR [here](https://github.com/dessant/search-by-image/pull/79).

Thanks.

**Comment by dessant** [comment]
Dark mode was implemented in version 5.5.0, the update should arrive in the next few days.

**Comment by xmha97** [comment]
Thanks 👍
