### ISSUE TITLE
Ability to set a main search engine for the context menu

### ISSUE THREAD

**Issue by PhilippeCadieux** [dessant/search-by-image#87]
**Is your feature request related to a problem? Please describe.**
Not really a problem but more of a very minor QoL thing. I generally want to search via Google for like 99% of my reverse image searches but sometimes I still need to look up using other websites. Right now this means that no matter what, I need to use the submenu of the contextual menu everytime I want to do a search.

**Describe the solution you'd like**
I think being able to set a "main" search engine that would show up directly in the contextual menu but then also still having the submenu option next to it to give me access to all the other engines would be a great solution for this.

**Describe alternatives you've considered**
Nothing I can really think of right now

**Additional context**
As mentionned above, this is obviously an extremely minor QoL thing but I thought I'd still suggest it because I think this would make this already great addon even better! 

Thanks!

**Comment by dessant** [comment]
Hi Philippe! I'd find the feature useful, but there is a browser limitation: extensions are only allowed to have one top-level context menu item, and multiple menu items are just folded in a submenu by the browser.

If you're on Chrome, you could sidestep the limitation by installing the extension for a second time from a local folder, here are the latest packages for every browser: https://github.com/dessant/search-by-image/releases

After you've installed a second instance of the extension, disable all search engines from the extension's options, except Google, and that will add a top-level context menu item for your search engine.
