### ISSUE TITLE
option to upload a local image

### ISSUE THREAD

**Issue by reembar** [dessant/search-by-image#9]
I would love to see an option to upload a local image from the computer to one or all of the image search engines, like in this Firefox extension:
https://addons.mozilla.org/en-US/firefox/addon/who-stole-my-pictures/

**Comment by dessant** [comment]
I agree, it's definitely an option which would be nice to have. I may add it in a toolbar popup because the feature is not tied to a specific tab context, and because I've been wanting to have a popup for the extension anyway for Android support.

**Comment by dessant** [comment]
Until this is implemented, there is a workaround. You can open the local image with Firefox and you should be able to search for it from the context menu. Though you may get less relevant results in certain cases because the image has to be converted while it is extracted from pages with file:/// URLs.

**Comment by reembar** [comment]
I tried it, but I get an error messages "Something went wrong. Reload the page before searching again" and reloading wouldn't change it. Also, in similar extensions, sending the local file location as the URL won't give results in the websites, because the interface for sending the files in them is different.

**Comment by dessant** [comment]
Could you open the Browser Console (Ctrl + Shift + J) and check if there is an error log when you try to search for the local image?

**Comment by reembar** [comment]
No. There is no error log entry in the console.

**Comment by dessant** [comment]
I'll try to reproduce it, what is your OS and Firefox version?
If your image is private, could you share some data about it, like the resolution, file size and extension? 

Do you get the same error if you save this image on your drive, then open the saved file in a tab and search for it? https://i.imgur.com/GXtrnQk.jpg

The image was successfully uploaded on my part with Firefox 55.0.3:
https://www.tineye.com/search/e7f2e40b36ba79258d07214b9edc44a2bbd86f89/

**Comment by reembar** [comment]
I use Chrome 61.0.3163.100 (64-bit) on Windows 10. I used Firefox until recently, when they decided to drop the support in the legacy extensions, and now I try to find replacements to them in Chrome... Anyway, I downloaded the image and tried to search for it, and got the same error message...

**Comment by dessant** [comment]
Ah, the file:/// image search is only available for Firefox because the security features of Chrome block the extraction of images from file:/// pages.

**Comment by dessant** [comment]
Here's a teaser. 😋

![screenshot from 2017-10-10 20-48-07](https://user-images.githubusercontent.com/7513068/31401953-1e445310-adfd-11e7-9293-6260ca40ccfe.png)
![screenshot from 2017-10-10 20-48-15](https://user-images.githubusercontent.com/7513068/31401955-1e6b4c18-adfd-11e7-8445-8a220e443e17.png)

**Comment by reembar** [comment]
Maybe, if you can't upload local image directly through Chrome, this menu can link in Chrome to the upload page of each search engine... BTW you are missing TinEye...

**Comment by reembar** [comment]
I thought of making a simple cgi for webpage from which you can upload local image to all those services, but fear of the bandwidth...

**Comment by dessant** [comment]
TinEye will be there, I just haven't taken care of an icon yet.

Yes, this will be available the same way for all supported browsers. It will work by selecting the Upload search mode, then clicking on a search engine, that will bring up a file selection dialog wihich will also allow to select multiple files.

From there the extension takes care of uploading to the selected engines and shows the results as usual.

**Comment by dessant** [comment]
Local image uploads will be available in the next version, it will be released in the next couple of days.

**Comment by dessant** [comment]
@reembar, version 1.4.0 has been published, local file uploads are available from the toolbar button popup.

**Comment by italiani** [comment]
why upload and select not work in 57 beta?
can move the upload button to the context menu?

**Comment by dessant** [comment]
@italiani, you'll have to share more details about what are the steps you're taking and what doesn't work exactly, it works on my part.

The context menu is for taking actions in the context of the page, uploading local images has no relation to the current web page, that's why the feature is accessible from the browser toolbar instead.

**Comment by italiani** [comment]
I just press ypload and no further reaction

**Comment by dessant** [comment]
@italiani you have to select upload, then click on the search engine you want to upload to. A page will open in a new tab where you can drop your images, or select them with the file picker.

**Comment by italiani** [comment]
oh difficult but I figured it out

**Comment by EC-O-DE** [comment]
Add switchers to that pop-up so that users can choose the engines to use when right click image...

**Comment by dessant** [comment]
@EC-O-DE, the search engines can be configured on the options page.

**Comment by EC-O-DE** [comment]
Yes at the options page. But quite many times engines needs to be changed "on the fly" - so it would be quick to do from a pop-up :) 

Here's an image of other ext having a pop-up I described:

![unnamed](https://user-images.githubusercontent.com/9984842/32474992-35db96ec-c378-11e7-8ec0-3b9d1beca0a2.png)
### (Do not use that ext it tracks every search u make)

Could similar to this be added?

**Comment by dessant** [comment]
@EC-O-DE, thanks for the suggestion, but I don't plan to add engine toggling to the popup at this time.

**Comment by EC-O-DE** [comment]
I hope u consider for future release :)
