### ISSUE TITLE
Extension stops working from time to time

### ISSUE THREAD

**Issue by adamkkkkkk** [dessant/search-by-image#94]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Chrome
* Browser version: 85.0.4183.102
* Extension version: 3.1.0

**Bug description**

The extension stops working from time to time. I haven't noticed any particular action that stops it. Disabling/Re-enabling the extension from settings gets it working again.

**Logs**

No logs.

**Comment by dessant** [comment]
What does "stops working" mean? Please describe in detail the steps you take and what you see as a result.

**Comment by adamkkkkkk** [comment]
> What does "stops working" mean? Please describe in detail the steps you take and what you see as a result.

Sorry for not clarifying earlier. What I meant was that it stops showing up in the right-click context menu. Turning it OFF/ON fixes that temporarily. 

I still haven't identified which action of mine gets it to stop showing up in the context menu. It's just that during my regular usage, it disappears from there. Also, after turning it OFF/ON, I'll have to reload the tab for it to actually work there since it does show up but reloading of the page is needed.

**Comment by dessant** [comment]
When the extension disappears from the context menu, does it continue to appear and remain usable from the browser toolbar?
