### ISSUE TITLE
Icon search-by-image not appear

### ISSUE THREAD

**Issue by ArnauBS** [dessant/search-by-image#95]
For firefox (81.0 64bits linux Mint)
After extension installation, appear in extension list, and we can configure extension.
But the icon not appear.
Not appear in the taskbar.
Not appear in the contextual menu.
Not appear in the customization stock icons.
Appear in the shortcuts configuration, but only in the list without shortcuts declared.
The result we can't use this extension
Thank you

**Comment by dessant** [comment]
So you can only open the options page of the extension and you only see [these](https://camo.githubusercontent.com/12187c13f89723d86251ff1cf398b931a66afb6b/68747470733a2f2f692e696d6775722e636f6d2f71424b577257312e706e67) widgets?

**Comment by dessant** [comment]
I think I've seen similar behavior once in Firefox about a year ago, but I don't think it's an extension bug. Try testing with a fresh browser profile and see if it works.
