### ISSUE TITLE
Implement better CSS url() function parameter parsing

### ISSUE THREAD

**Issue by mkeroppi** [dessant/search-by-image#97]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 81.0.1
* Extension version: 3.1.0

**Bug description**
Certain images on discuss.com.hk are detected as broken link; e.g.,
background-image:url('https://cdn.discuss.com.hk/t/3c2710/f/320x320/filters:extract_cover()/https://img.discuss.com.hk/d/attachments/day_201011/20201011_0e4f118b79b726be1169UXilRwXQknXp.jpg');

See also: https://github.com/kubuzetto/behind/issues/6#issuecomment-707532691

**Logs**

```
// REPLACE WITH LOGS
```

**Comment by dessant** [comment]
Thanks for the bug report!

https://developer.mozilla.org/en-US/docs/Web/CSS/url()
