### ISSUE TITLE
Does Search by Image make any connections to a sever?

### ISSUE THREAD

**Issue by throwaway282630101** [dessant/search-by-image#98]
Hi. Before I ask my question thank you for making this app, it's really great! :)

But it didn't say in the "about this extension" if it contacts a sever in anyway. Is any type of data sent back to anything?

**Comment by dessant** [comment]
The extension uploads images to the search engines you select, other than that, when the contribution page is opened (:yellow_heart: button), the page requests a json file from my server with the current funding goals and progress, but no data is sent to the server.

That's about it, the extension does not collect and send any of your data in the background.
