### ISSUE TITLE
Toolbar menu not shown if just one search engine seleced

### ISSUE THREAD

**Issue by StefRe** [dessant/search-by-image#99]
**System**

* OS name: Windows
* OS version: 10
* Browser name: Firefox
* Browser version: 83
* Extension version: 3.4.1

**Bug description**

If only one search engine is selected, then clicking the toolbar icon directly enters the default search mode chosen in the options menu without showing the toolbar popup. While this behavior is desired for the context menu (i.e. the only search engine is shown in the main context menu, not in a submenu) it's not so ideal for the toolbar icon as you don't have access anymore to the popup menu (![grafik](https://user-images.githubusercontent.com/19879328/100120334-22384b80-2e78-11eb-8b13-6a957cf56345.png)) and other search modes.  

*Steps to reproduce:*
* open options and deselect all but one search engine
* click the toolbar icon --> no popup shown, goes straight to search mode

*Suggested behavior:*
I think even when just one engine is selected and there's no choice to make you should nevertheless show the toolbar popup for the reasons explained above.

**Comment by dessant** [comment]
I agree, and I think this should be configurable. The plan is to be able to explicitly select a search engine group or and individual engine for searching directly from the toolbar icon or the top level context menu item, and it will be implemented along with search engine groups (https://github.com/dessant/search-by-image/issues/68).
